### ISSUE TITLE
Crash Team Racing (PAL) : Graphical Glitches

### ISSUE THREAD

**Issue by Dasha-98** [notaz/pcsx_rearmed#100]
Hi,

I open this issue as I observed few graphical glitches on Crash Team Racing.
The glitches I discovered are:
- In pause menu (in-game)
- Textures on few tracks like "Park Coco" or "Slide Coliseum".

Note: I play with r22 version.

**Comment by notaz** [comment]
I'm guessing this has since been fixed. Feel free to reopen if not.
