### ISSUE TITLE
Driver (PAL) : cannot "retry"

### ISSUE THREAD

**Issue by j2k15** [notaz/pcsx_rearmed#101]
Hi,

I observed an issue in Driver (PAL) game.
The "retry" option is quitting the game rather than retrying the mission.

Note: I play with r22 version.

**Comment by jose1711** [comment]
I can confirm this behaviour on RPI3 and GP2x. There are also some more reports of the same at https://retropie.org.uk/forum/topic/4029/ps1-games-that-have-bugs-in-retropie.

**Comment by AssCabbage** [comment]
This is still an issue in the latest build.
