### ISSUE TITLE
Tombi 2 (PAL) Sound Slowdown

### ISSUE THREAD

**Issue by Klauserus** [notaz/pcsx_rearmed#102]
Hi I have sound slowdowns in Tombi 2. It come from time to time. First Level you can test it. If you need more software information, let me know.

Raspberry Pi 3 B+
Retropie 4.3
PCSX Rearmed r22

You need Driver Informations?

**Comment by sigmacitizen** [comment]
I've had similar experiences with Tomba 2 US on stage one, after the track loops once it skips to the track "Coal-Mining Town (Cursed)" and plays the song incorrectly. 

Raspberry Pi 3 and oDroid4uX

**Comment by gingerbeardman** [comment]
This is the same as #122

**Comment by notaz** [comment]
I think this is working correctly now. Feel free to reopen if not.
