### ISSUE TITLE
Suikoden 2 (PAL) won´t start

### ISSUE THREAD

**Issue by Klauserus** [notaz/pcsx_rearmed#103]
This Game won´t start. Not the PAL Version or the Patched Version of the Game. I push the start Button and it goeas after blackscreen back to psx menue

PS: Final Fantasy 9 PAL same problem.

Raspberry Pi 3 B+
Retropie 4.3
PCSX Rearmed r22

**Comment by notaz** [comment]
I think this is working correctly now. Feel free to reopen if not.
