### ISSUE TITLE
Star Ocean (PAL) glitches

### ISSUE THREAD

**Issue by Klauserus** [notaz/pcsx_rearmed#104]
Star Ocean: The Second Story has glitches on the 2d character Models. 
You can see it at best, when you go to the menü befor the first fight begin. I have created this picture. not a screenshot but it looks like the same in game.

<a href="http://www.bilder-upload.eu/show.php?file=36a427-1514121960.jpg" target="_blank"><img src="http://www.bilder-upload.eu/thumb/36a427-1514121960.jpg" border="1" alt="Bilder-Upload.eu - share DEINE Bilder" /></a>

Raspberry Pi 3 B+
Retropie 4.3
PCSX Rearmed r22

**Comment by notaz** [comment]
I don't see any obvious issues in the menu on the latest version and your image link is dead. Assuming fixed, you can reopen if there is still an issue.
