### ISSUE TITLE
CDROM Support - Debugging

### ISSUE THREAD

**Issue by adamboutcher** [notaz/pcsx_rearmed#113]
Hi,

I'm trying to hack CDROM Support into a emulator build and I'm currently stuck...

I have managed to make the core load a cople of games from CD by symlinking an ISO file to the CDROM device in linux (ln - s /dev/sr0 game.iso). The games load and gets past the bios screen but then they usually just hang.

Doom - Plays an FMV slowly, then hangs on "Loading" prior to the menu
Rayman - The language menu works then hangs on the Ubisoft Logo

I can confirm data is being read from the CDROM albeit slowly for the FMVs and then the transfer stops dead at the point of the hang, iostat shows 0bits and the drive eventually spins down.

I was wondering if there is anything I can do to test and better debug this?

**Comment by notaz** [comment]
Symlinking won't work as the games need the raw mode2 sectors. Proper low level commands to cd driver are needed. Perhaps something can be found in other emu sources. Anyway closing as not planned.
