### ISSUE TITLE
Sony stole your work for their Playstation Classic !

### ISSUE THREAD

**Issue by AngelSora** [notaz/pcsx_rearmed#114]
Not really an issue, their just selling this for a 100$ without any credit given to you and the team.

**Comment by mudlord** [comment]
They released the source. **Its completely legally legit**. Regardless of the ethics involved, which doesn't matter to companies, no matter the size.

**Comment by joaov-ferreira** [comment]
Actually, it gives credit to the team, as they included it in the open source projects list.

IMHO, i think this is very positive. Most of the big open source projects are backed by huge companies. It would be really nice if some of sony could help support this project, but unfortunately, I really don't see they going in this direction.

**Comment by AngelSora** [comment]
Okay then, sorry to have bothered you !
