### ISSUE TITLE
Is libX11 really required for raspberry pi?

### ISSUE THREAD

**Issue by drwulsen** [notaz/pcsx_rearmed#115]
I'm porting pcsx_rearmed targeted at libretro from your repository to the gentoo ebuild system for myself.
Once I've figured out what I need to, I'll ship it back to the gentoo maintainer, for review and use.

However, there's one thing puzzling me a little. In the configure script, it searches for the VideoCore stuff.
Once found, it sets need_xlib.

Question: When I'm running on a raspberry pi and haveing it run as plugin for kodi-18 (which I have run without X, just on the framebuffer) - that dependecy could be omitted, or is there an objection?

Sorry to bother you with that.

**Comment by notaz** [comment]
The dependency was either for VideoCore or standalone UI and not needed.
