### ISSUE TITLE
[Request] Full framebuffer emulation support

### ISSUE THREAD

**Issue by roflcopter777** [notaz/pcsx_rearmed#117]
It has come to my attention that no version of PCSX ReARMed currently supports full framebuffer emulation This is evident in battle transition effects that heavily rely on FB in Squaresoft games. This issue is especially noticeable on the Playstation Classic and the libretro versions of PCSX ReARMed, when the battle swirl, well, looks rather off. 

When compared to how it's emulated on Mednafen or BeetlePSX , you can see that it looks 1:1 to the real thing: Yes they are more accurate, but surely, a compromise could be made? Maybe the NEON GPU plugin being ported? 

[img]https://i.imgur.com/JHR4Kod.jpg[/img]
![image](https://user-images.githubusercontent.com/15101626/52167950-a1c3bc00-26e0-11e9-83eb-c5faf6cf19c5.png)

Now, obviously full FB effects are more demanding on the CPU, and it's been revealed the Classic uses a 

MediaTek MT8167A SoC processor

- Quad Core ARM Cortex A35 at 1.5 GHz
- PowerVR GE8300 GPU 
- 1 GB DDR3 RAM 

I don't know what the requirements would be to implement it, or if if can even run a game with the framebuffer fully emulated or some kind of compromise to where it only uses FB where needed and then disables it. Is this possible? Thank you.

**Comment by notaz** [comment]
It's not related to hw requirements and was a plain NEON GPU bug that has been since fixed.
