### ISSUE TITLE
Slight desync issue in Crash Team Racing's intro

### ISSUE THREAD

**Issue by gameblabla** [notaz/pcsx_rearmed#118]
Hello,
i noticed that the intro played differently in CTR than the way i remembered : 
it does not completely play the music in the very first intro before the loading.
See how it runs on PCSX-Rearmed here (this is the NTSC version)
https://www.youtube.com/watch?v=QynnJ7EXGyw

Pay very close attention before the loading screen, notice that the music stops before it can even finish.

Now, here's Mednafen, which runs said intro like on real hardware (or very close to it)
https://www.youtube.com/watch?v=B4eNb2-mCPY

Notice the difference ? In Mednafen (and real hardware), said music actually finishes before the loading screen.
Btw, said game refuses to run on spu_null and HLE freezes before the crate appears. Also, using the IRQ hack (i heard that CTR messes with those too) makes it stuck at the first screen.
I strongly suspect that the SPU is the culprit but i'm not sure where exactly.

I know that Peops SPU had a hack for it here
https://github.com/emukidid/pcsxgc/blob/927b803b58a5b250f9b209c21b070214de5133bc/PeopsSpu109/PEOPSspu.c#L1147
It looks like the SPU plugin is already doing so though ?

**Comment by gingerbeardman** [comment]
This could be the same as #122

**Comment by gameblabla** [comment]
Merging both 
https://github.com/notaz/pcsx_rearmed/pull/184
and
https://github.com/notaz/pcsx_rearmed/pull/183

fixes the desync issue in Crash Team Racing's intro !
The first fix was initially for Zeus fight in Xenogears but it seems to also fix other games as well.
This could also be a fix for #122

**Comment by gameblabla** [comment]
I re-tested my changes just in case and it does fix the issue so yay.
