### ISSUE TITLE
CFLAGS not correctly recognised

### ISSUE THREAD

**Issue by xnemesis** [notaz/pcsx_rearmed#120]
I've checked out the most recent revision from git. ./configure recommends that I use armv7 for -march as the CFLAGS. I have armv6 but it continues to try to force me to use armv7:

CFLAGS="-march=armv6zk -mfpu=vfp -mcpu=arm1176jz-s" ./configure
Warning: compiling for NEON, but not ARMv7?
You probably want to specify -mcpu= or -march= like this:
  CFLAGS=-march=armv7-a ./configure ...

I am using a raspberry pi zero w, I have tried just with -march, with -march and -mfpu, and as above. The values are taken from the GCC safe compile flags.

**Comment by derpeg** [comment]
The warning is emitted because the configure script fails to disable NEON if it detects something < ARMv7  -- e.g. the ARMv6 used on the Pi Zero. Can be worked around by passing  `--disable-neon`.

`CFLAGS="-mcpu=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard" ./configure --disable-neon`
