### ISSUE TITLE
Wrong content streamed from CD in certain situations (save states included)

### ISSUE THREAD

**Issue by gingerbeardman** [notaz/pcsx_rearmed#122]
This has been bugging me and I'm happy to have finally found the cause. Sorry to say that it appears to be limited to PCSX ReARMed. Beetle PSX does not have this problem.

## Problem
CD access is out of whack, resulting in incorrect audio/video playing in certain circumstances.

## Game
Jun Classic C.C. & Rope Club
http://redump.org/disc/29981/

I'm using redump verified CUE & BINs as I'm a dumper of this game. Merging to a single BIN, ISO, CHD, PBP does not help. 

## Background
This is a golf game with lots of audio tracks (music, description of each hole, digitised sound effects of wind, water, rain, birds). There are also short thumbnail FMV clips that play when you hit a good shot.

## Save States
- State 0, Beetle PSX [JUNROPE.state.zip](https://github.com/notaz/pcsx_rearmed/files/2922563/JUNROPE.state.zip)
- State 1, PCSX ReARMed [JUNROPE.state1.zip](https://github.com/notaz/pcsx_rearmed/files/2922560/JUNROPE.state1.zip)

These were made using RetroArch 1.7.6 PCSX-ReARMed r22 v0370856.
I get the same problem on Nintendo Switch, which is where I noticed it.

## How to Reproduce
1. Load chosen core (Beetle/PCSX)
2. Load game content
3. Load save state (0/1)

## Expected Results
- ball comes to rest, yardage displays 
- short FMV clip in lower right corner "nice shot!"
(Beetle PSX does this)

## Actual Results
- ball comes to rest, yardage displays
- two CD Audio tracks, both short phrases, followed by the thumbnail FMV clip that is cut short
(PCSX does this)

## Screenshot
This is the final facial expression of the person in the FMV; this is never seen using PCSX.

![screen shot 2019-03-02 at 22 30 45](https://user-images.githubusercontent.com/49612/53688443-f4be7c80-3d3b-11e9-956a-ae66f3fceade.png)

## Analysis
It seems to me that PCSX seeks CD tracks at incorrect locations, somehow?

So the drive seeks to a point before the FMV and ends up in a CD Audio track, playback begins and goes through two Audio tracks not stopping at either of their end points, and then finally playback gets to the start of the FMV and it proceeds to play, but by now the "playback duration" is almost exhausted and so the FMV is cut short.

The amount of error seems to increase with the number of CD tracks.

There are many other situations with this game where the wrong audio/video plays.

Let me know if I can be of further assistance with this one.

**Comment by gameblabla** [comment]
You might be onto something !
PCSX-Rearmed is based on PCSX-Reloaded so i thought i would check the other forks to see if they exhibit the same issues.
I tried PCSX-Reloaded (https://github.com/gameblabla/pcsxr) and PCSXR NXGP (https://github.com/iCatButler/pcsxr) and they also suffer from the same issue. (at least for CTR)

So i would suggest you try your golf game on PCSXR and see if it exhibits the same issue. (it probably will)

**Comment by gingerbeardman** [comment]
You are indeed correct, it seems to be a longstanding bug. 

It happens with PCSX-Reloaded 1.9.95 (SVNREVISION) on macOS.

Interestingly the random number generator but be seeded differently because with the same choices the game picks a different caddy, so it's a different person shown in the FMV.

![screen shot 2019-03-03 at 12 07 08](https://user-images.githubusercontent.com/49612/53694929-03914780-3dad-11e9-9ee5-3850ceb4032b.png)

Here'd a freeze/save state: 
[SLPM86080-000.pcsxrstate.zip](https://github.com/notaz/pcsx_rearmed/files/2923073/SLPM86080-000.pcsxrstate.zip)

**Comment by gameblabla** [comment]
As i noticed in my CTR issue, after i took my 2 patches that came from the PCSX Redux project,
it fixed the desync issues i had in CTR !

I believe this could also fix this one.
See
https://github.com/notaz/pcsx_rearmed/issues/118#issuecomment-898795930

**Comment by gingerbeardman** [comment]
Thanks, I'll have to wait for it to be merged

**Comment by gameblabla** [comment]
@gingerbeardman Libretro merged my PR so at least as of now, libretro's fork has my fix
https://github.com/libretro/pcsx_rearmed/pull/536

Another tester told me it fixed the freeze issue in FF8 after Lunar Cry FMV.

**Comment by notaz** [comment]
Assuming this is fixed, reopen if not.
