### ISSUE TITLE
Bad input delays/no input registered in certain games

### ISSUE THREAD

**Issue by arnoldsecret** [notaz/pcsx_rearmed#128]
Some games have some serious delays in input, these games are:

Beyblade
Carmageddon
Cubix Robots for Everyone - Race'n Robots
[Inuyasha - A Feudal Fairy Tale](https://www.reddit.com/r/PlaystationClassic/comments/abbnbt/no_idea_how_to_fix_this_inuyashaa_feudal_fairy/)
Shaman King - Spirit of Shamans

Some games don't recognize inputs at all

Ace Combat 3 - Electrosphere (Japan) - inputs get recognized after attract fmv plays.
Cowboy Bebop
Silhouette Mirage

**Comment by arnoldsecret** [comment]
bottom part is duplicate of https://github.com/libretro/pcsx_rearmed/issues/161, with a 20$ bounty as of this writing.

**Comment by arnoldsecret** [comment]
for reference, https://www.reddit.com/r/PlaystationClassic/comments/abbnbt/no_idea_how_to_fix_this_inuyashaa_feudal_fairy/

**Comment by retro-wertz** [comment]
at least for KoroKoro, its only the libretro port that has the input broken. it happened during the introduction of multitap code. building the standalone or a libretro port from the master commit from this main repo does not have the input issue (for the said game at least).

**Comment by arnoldsecret** [comment]
moved issue to libretro#271.
