### ISSUE TITLE
Buggy/Team Losi RC Racer polygon issues...

### ISSUE THREAD

**Issue by retro-wertz** [notaz/pcsx_rearmed#129]
original post is here: https://github.com/libretro/pcsx_rearmed/issues/216

tested with Buggy/Team Losi RC Racer and polygon issue for the game is gone (seen in vid is gone https://drive.google.com/open?id=1X5BIoE6f6Ch-UPX2bhTZFVGIhamvUIYN) (probably would fix other polygon-related issue in that list)

first bad commit: https://github.com/notaz/pcsx_rearmed/commit/b3254af90fafc88bd1b40566de65a0471771c8d5#diff-024f187f4553e97d07ec1407595d2c54

sent a PR for the proposed fix but not entirely sure if a revert or rework is required since BOUNDS_ is a macro to other macros (A1/A2/A3 and F())

tested on linux x64 (non-dynarec)

**Comment by leranger** [comment]
Hi
The problems appears in Colin McRae Rally PAL in the first race in Greece.
So, I have tried your patch on (non dynarec for both) : 
- libretro core on windows 64bits
- standalone on linux 64bit
I have not seen glitches during my tests so it seems your patch fixed the issue
thanks
