### ISSUE TITLE
Audio issues on retroarch

### ISSUE THREAD

**Issue by ghost** [notaz/pcsx_rearmed#131]
somehow there's a sort of scratching sound when i play a game like resident evil and or other games. I have tried all i could to fix it but somehow it won't go away. However when i play other games on the snes or other emulators it isn't there. Is there a way to fix this issue?

**Comment by retro-wertz** [comment]
i believe you can change default audio driver during compile. one of it would work better than the other i guess.

**Comment by notaz** [comment]
There are some filtering options that might help. Anyway this needs a more precise description, closing for now.
