### ISSUE TITLE
 problem of a game freezing that I encountered while was playing The Legend of Dragoon using pcsx-rearmed emulator

### ISSUE THREAD

**Issue by chel1** [notaz/pcsx_rearmed#132]
Good day. I want to inform you about a problem of a game freezing that I encountered while was playing The Legend of Dragoon using pcsx-rearmed emulator. The emulator is assembled for Raspberry PI 3+ microcomputer, Rasbian distribution. The original bios "scph-1001.bin" is used.
The problem is as follows.
In the second CD of the game after the battle against Lenus and Regol the Dragon there is a cutscene in which Lenus dies and the dragoon spirit goes to Meru. After the cutscene the victory window is shown and party members get experience points for the battle. Then the screen blackens and the game doesn't go any further.
I copied a memory card with the game savefile before the battle against Lenus and Regol the Dragon into Epsxe-1.6 emulator. I won the battle, watched cutscene and experience distribution. After the screen blackens the game continued playing in Epsxe-1.6 emulator. I got to a game save point and overwrote the save file. Then switched back to pcsx-rearmed, loaded overwritten savefile and the game continued playing well.
The problem with game freezing also occured in PCSX-Reloaded emulator for Windows.
The memory card with the savefile before the battle is in attachments to this letter.
[LegendOfDragoonCD2.zip](https://github.com/notaz/pcsx_rearmed/files/3037260/LegendOfDragoonCD2.zip)

**Comment by notaz** [comment]
I have no way to verify this because of not knowing how to play this game. There have been many updates since so I'll just guess the problem is fixed as some other known similar ones. But feel free to reopen if there is still an issue.
