### ISSUE TITLE
[Video] Jade Cocoon Graphical Glitches

### ISSUE THREAD

**Issue by Tsubajashi** [notaz/pcsx_rearmed#140]
Hi!
Today i wanted to start playing Jade Cocoon, and have found that weird graphical issue where my hp bar, or any other bar really, goes beyond its actual area where it should be.
if someone tells me how to log everything from inside retroarch, ill gladly upload the log.
![grafik](https://user-images.githubusercontent.com/21346945/62505864-958af980-b7fe-11e9-8016-3a3764dfd0ea.png)

I hope that issue gets resolved quickly, as i do not know what else will is affected by it.

**Comment by notaz** [comment]
The HP bars look ok in the current version, closing.
