### ISSUE TITLE
[3ds cia] tekken : how to have music cd track playing ?

### ISSUE THREAD

**Issue by fraf** [notaz/pcsx_rearmed#143]
Hi,

If anyone might have a step by step guide for this it will be kind !
I tried several game iso rip of tekken for exemple.
Impossible to have audio cd track playing in game.
Chd/bin/cue none works.

Help me thanks.

PS: I use the nighty build as of today of pcsx rearmed with new 3ds

**Comment by fraf** [comment]
Here the list of ps1 with cdda tracks : 
https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/List_of_PlayStation_games_with_CD_audio_tracks.html

**Comment by FateForWindows** [comment]
This project has no 3DS support. As stated in previous closed threads, this belongs in the Libretro fork's issue tracker.

**Comment by fraf** [comment]
Problem solved in retroarch 1.8.4. Now cdda music are played !
