### ISSUE TITLE
Video playback in Galerians is incorrect / sections out of order

### ISSUE THREAD

**Issue by ttmcmurry** [notaz/pcsx_rearmed#145]
When playing Galerians (SLUS-00986) on my Android Tablet or Lakka Odroid-XU4, all video playback sequences are out of order on the left portion of the screen.  See the images below, same behavior occurs on more than 1 platform.   This glitching is not present when using Beetle PSX / Beetle PSX HW.  

Turning Enhanced resolution on/off doesn't make a difference.  

**Lakka Software Versions**
Retroarch (Lakka) - Nightly Oct 12, 2019 / ea7e682253 - 2.3x Branch - Odroid-XU4
PCSX-ReARMed - r15-950-g915cd7d (Sep 10, 2019)

**Android Software Versions**
Retroarch - 1.7.9 (Oct 7, 2019) / Google Play Store
PCSX-ReARMed - r22 eb6943e
Android - 9 (Official Samsung SM-T387T)
Kernel - 3.18.120-16738276 (Sep 5, 2019)
Patch - September 1, 2019

![Galerians (USA) (SLUS00986)-191019-001531](https://user-images.githubusercontent.com/44306558/67137593-0ccd0880-f206-11e9-8534-08109f3e6359.png)
![Galerians (USA) (SLUS00986)-191019-001405](https://user-images.githubusercontent.com/44306558/67137595-0fc7f900-f206-11e9-8bf9-0bdbfaef5605.png)

**Comment by gameblabla** [comment]
I had a similar issue with R-types's intro and the fix was to change the MDEC BIAS in the source code.
I have a PR to fix that :
https://github.com/notaz/pcsx_rearmed/pull/186
