### ISSUE TITLE
Permission to add PCSX ReARMed to Steam as free DLC for RetroArch

### ISSUE THREAD

**Issue by twinaphex** [notaz/pcsx_rearmed#150]
Hi there,  we would like to seek your permission to include PCSX ReARMed as a core as free DLC for RetroArch on Steam. 

The user would have to manually install this, it would be freely made available.

If there's anything you are unsure of or are hesitant about, don't hesitate to bring it to our attention. We will always go with whatever you decide.

**Comment by notaz** [comment]
As long as this does not conflict with GPL in some way it's fine.
