### ISSUE TITLE
NFS: High Stakes freeze on odroid XU4

### ISSUE THREAD

**Issue by inteyes** [notaz/pcsx_rearmed#151]
Hello!

Need For Speed 4 - High Stakes in some cases can stuck while running with dynarec enabled. When this happens, the image freezes and a short musical loop repeats, but seems like emulator still operational (I can open it's menu, load \ save state etc). As far as I can see, this happens only when dynarec set to "On", and never occur when it's "Off".

## Steps to reproduce

Start game like this:

One Player -> Hot Pursuit -> Duel -> Kindiak Park with Weather set to "On" -> Race two laps and watch replay.

Sometimes game stucks on first lap, sometimes on second (more often here). If you are able to finish the race then it can stuck on watching replay too.

## Device/OS/platform/architecture

Odroid XU4 running Ubuntu 18.04.3 LTS / Linux 4.14.157-171 armv7l / PCSX-ReARMed r22-92-g0d9eed8
Using original PS BIOS file instead of HLE
Dynarec set to "On"
Using .bin/.cue image, US region SLUS-00826

I attached a savestate where the game already hangs and a log file down below.
[pcsxr_files.zip](https://github.com/notaz/pcsx_rearmed/files/4092836/pcsxr_files.zip)

I'm not that experienced with debugging / coding, but if there will be need any tests or information I will be glad to provide.

Regards

**Comment by notaz** [comment]
The dynarec has since received a lot of fixes and this is assumed fixed. Feel free to reopen if not.
