### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by pcercuei** [notaz/pcsx_rearmed#153]
Most of the source files in libpcsxcore/ are GPLv2+, which means that they can be used together with LGPLv3-licensed code. However, some of these files don't have any license header (gte_divider.c, gte_divider.h, gte_arm.h, gpu.h, gte_neon.h, memmap.h, memmap_win32.c, psxmem_map.h) and fall under the license described in the COPYING file which is GPLv2 (not GPLv2+), and as such prevent PCSX to be linked with LGPL libraries.

Since the number of authors on these files is low, it'd be great to have their license changed to GPLv2+.

**Comment by notaz** [comment]
Are you saying it's only the files you mentioned, or are there more?

**Comment by pcercuei** [comment]
These are only the ones from libpcsxcore, there are some more outside, e.g. plugins/gpu_neon/psx_gpu/psx_gpu_4x.c, and very few header files (e.g. in include/) have a license header specified.

**Comment by twinaphex** [comment]
Notice two files listed here were by us, so I pushed a PR here to at least get these two files covered -

https://github.com/notaz/pcsx_rearmed/pull/154

**Comment by notaz** [comment]
@twinaphex's patch is merged and I've added some headers. However gte_divider.c came directly from PCSX-Reloaded (was called gte_divider.h there), so I don't know what to do with that.

**Comment by pcercuei** [comment]
The "latest" official PCSX-Reloaded is [here](https://github.com/edgbla/pcsxr), but it does not have a gte_divider.h. There is one in [pops-gte](https://github.com/ogamespec/pops-gte) but the code is a bit different, the LUT is much smaller. So I have no idea where the code comes from.

**Comment by notaz** [comment]
Looks like it came from https://github.com/edgbla/pcsxr/commit/20acfdc954a451cf6ec57aa2385c4fe410d0840b which was still in place at the time of forking.

**Comment by pcercuei** [comment]
I contacted edgbla, he has no idea how to contact the original author, but he suggested me to just use MAME's GTE divide code for that, which is licensed under the BSD-3-Clause:
https://github.com/mamedev/mame/blob/80bc38691c49c24bca76636c78a61cc0e3fafd19/src/devices/cpu/psx/gte.cpp#L292

And it doesn't use a big 64 KiB LUT, so that's probably better...

**Comment by pcercuei** [comment]
I created PR #156.

Btw, the reason why this is important is that I have my own dynarec (https://github.com/pcercuei/lightrec) under LGPL and we've been plugging it in PCSX. It's starting to work really well and supports many architectures. Is that something you'd want contributed back to your repo, or should I keep it separate?

**Comment by notaz** [comment]
I don't know, I'm not able to do much with this project nowadays anyway so if a better fork emerges it might be even better. If it stays here I'd like to see it not getting worse on slow ARM hardware, there are better emulator options for fast hardware anyway.

**Comment by notaz** [comment]
I assume this is resolved now, feel free to reopen if not.
