### ISSUE TITLE
failed to create context?? RPI4 on X11

### ISSUE THREAD

**Issue by ghost** [notaz/pcsx_rearmed#158]
HI!
I am experiencing an odd thing after compiling the project...
I am running on master mesa, everything its fine on my driver AFAIK... but somehow the gui wont show up like it did on rpi3

pi@raspberrypi:~/Escritorio/pcsx_rearmed $ ./pcsx 
plat_sdl: using 1920x1080 as fullscreen resolution
plat_sdl: overlay: fmt 59565955, planes: 1, pitch: 1280, hw: 0
warning: video overlay is not hardware accelerated, not going to use it.
* failed to add service - already in use?

**Comment by Askmewho** [comment]
solved removing the rpi propietary driver stuff on configure. It should be removed, both rpi3/4 runs on mesa by default now.

**Comment by notaz** [comment]
The standalone build is mostly unmaintained, however improvement patches would still be accepted.
