### ISSUE TITLE
Speed problem after core update on 27.04.2020

### ISSUE THREAD

**Issue by tauonelectronics** [notaz/pcsx_rearmed#161]
Hello.
I was using your plugin in retroarch for a long time. 
Today with the latest update of the core speed has dropped to an unplayable fps.
Might be bug introduced in 92db7708f2fd2a26ea730d761a60a582a646405a commit?

**Comment by dankcushions** [comment]
wrong repositary:  https://github.com/libretro/pcsx_rearmed
