### ISSUE TITLE
Save cfg for loaded game not working

### ISSUE THREAD

**Issue by oss81** [notaz/pcsx_rearmed#163]
I'm using the standalone pcsx-rearmed on pi zero. When changing the config in a game and select "Save cfg for loaded game", the next time I load the game, the global config is loaded and not the previously saved one.

I've had a quick look in the sources and found that loading the "per game config" is done only in function romsel_run() in "frontend/menu.c"

`
if (menu_load_config(1) != 0)
		menu_load_config(0);
`

Shouldn't this be done in menu_init() as well?

**Comment by MackValentine** [comment]
Same problem :/
Anyone ?

**Comment by notaz** [comment]
It was expected that the game would be loaded through the menu. Anyway patched it now, better later then never I guess.
