### ISSUE TITLE
Add CHD support

### ISSUE THREAD

**Issue by iax2RqPZbq** [notaz/pcsx_rearmed#166]
CHD allows for optimal, lossless compression, and is supported in many other emulators (including MAME). It is superior to PBP.

I want to check thoughts on adding CHD support (there is a previous closed issue #107). It is supported in the libretro fork; we wouldn't need to use any code from it directly, but maybe some of it can easily be copied over. We can otherwise use `libchdr` directly.

**Comment by gameblabla** [comment]
I have done a PR that does just that for PCSX Rearmed :
https://github.com/notaz/pcsx_rearmed/pull/188

Sadly notaz is currently busy so he can't test my patches yet but if you compile it and apply my patches, it will work.
(I tested it and it's pretty nice)

I may look into merging the async CD option later for platforms with slow storage access.

**Comment by gameblabla** [comment]
It's merged so that can be closed. I've tested it and it works. For the async patch, i'll do that later.

**Comment by notaz** [comment]
But it's not added to the build yet?

**Comment by gameblabla** [comment]
Oh right yeah, it needs to be manually enabled in config.mak for now... I said that i would wait for https://github.com/notaz/pcsx_rearmed/pull/187 but if i introduce a PR to enable CHD support, it risks conflicting with it.
https://github.com/notaz/pcsx_rearmed/pull/187 is a big patch though... Should i do a PR for enabling CHD in configure and worry about https://github.com/notaz/pcsx_rearmed/pull/187 later ?

**Comment by Formedras** [comment]
Does the PR code support child CHDs? It would be nice to be able to store (for example) a SotN Randomizer disc image as just a child CHD and link it to the full disc, rather than having both full-size images on a drive.

**Comment by notaz** [comment]
It just uses libchdr so supports whatever that supports. If there is still something missing please open another issue.
