### ISSUE TITLE
PBP sector offset is incorrect; "sector <negative value> is past img end" error

### ISSUE THREAD

**Issue by iax2RqPZbq** [notaz/pcsx_rearmed#167]
`cdread_2048`, `parseccd`, `parsecue` and `parsetoc` all add an offset of 2 seconds (150 frames) to the track start times (grep for `2 * 75`); however this isn't present in `parsepbp`.

Because of this, some disc images that are valid for any of the other formats (including verified good dumps), when converted to PBP will not run (depending on if the disc requires seeking to the beginning of disc; some games work some don't) and instead we get a variation of "sector <negative value> is past img end".

Most existing PBP files seem to have been created with an offset of 2 seconds baked in, this means when converting them back to the raw disc image the CUE/TOC information will be incorrect (as it includes the 2 second offset).

This should be an easy fix; we can just update `parsepbp` to check if it has the offset (account for the existing files that were converted to work), and if not add it.can just update `parsepbp` to check if it has the offset (account for the existing files that were converted to work), and if not add

**Comment by notaz** [comment]
I haven't seen the .pbp files you describe. If this is still relevant you can submit a patch.
