### ISSUE TITLE
Strange visual artifact with Enhanced resolution (slow) enabled (Parasite Eve 1)

### ISSUE THREAD

**Issue by sinistar77** [notaz/pcsx_rearmed#168]
Raspberry Pi 4 8GB
Retropie installation
lr-pcsx_rearmed package

pcsx_rearmed_neon_enhancement_enable = "enabled"

See odd artifact at the bottom of the screen.  With neon_enhancement_no_main = "enabled" there isn't any artifact.
![IMG_20200727_104926](https://user-images.githubusercontent.com/39780476/88569674-01f69e00-cff8-11ea-819e-c3056395bbc5.jpg)

**Comment by dankcushions** [comment]
the libretro core you're using is hosted here: https://github.com/libretro/pcsx_rearmed

the issues with the enhanced resolution are known and documented here: https://retropie.org.uk/docs/Playstation-1/#video-double-internal-resolution - it's a hack so I doubt they will be fixed, and there's noone actively developing that side.

please use the retropie forum to log bugs in the first instance. we can direct you to the right place :)

**Comment by sinistar77** [comment]
Noted, apologies if any cycles were wasted with this issue notice.
