### ISSUE TITLE
Resize window / scaling

### ISSUE THREAD

**Issue by louisabraham** [notaz/pcsx_rearmed#169]
Hi, I compiled from source and I cannot find how I can resize the window. I have a  1080 monitor and it's small as hell, I cannot imagine how it would be on a 4K.

**Comment by louisabraham** [comment]
What is strange is that I don't appear to have the same options in the display menu.

Out of those options https://github.com/notaz/pcsx_rearmed/blob/master/frontend/menu.c#L1306 I only have "Video output mode" and "Software Filter".

**Comment by notaz** [comment]
If you select overlay output (it depends on hw if it's available or not) it should allow you to resize the window.

Anyway there are no plans to develop the UI, it is expected that people use libretro version of this emulator with a frontent of their choice.
