### ISSUE TITLE
Final Fantasy VIII - GF Boost icon does not flash during summon

### ISSUE THREAD

**Issue by OmegaPhil** [notaz/pcsx_rearmed#17]
Not sure if this is too specific a bug for here. 

When you summon a GF with Boost ability learnt, during parts of the summon sequence a small image of a finger pointing at a square button appears - when this does, you are supposed to hammer square to get the boost from 75 to 255 (IIRC). Not all of the sequence allows you to boost - parts of it forbidden - a cross icon appears over the hand and any square press resets the count.

On the PlayStation, the hand icon flickers for a short time just before the cross icon appears - **this flickering does not happen on pcsx-rearmed, so you just see the hand icon and suddenly a cross**.

Makes boosting a GF rather challenging :) Will probably have to remember the seconds on which I can boost.

I can provide a save if needed.

**Comment by notaz** [comment]
x86 has not switched to the neon gpu and there are no plans to maintain the peops one, closing.
