### ISSUE TITLE
No gamepad in Tomb Rider 1

### ISSUE THREAD

**Issue by noiseshaade** [notaz/pcsx_rearmed#170]
In epsxe like emulators works well
Tried to change bios

![image](https://user-images.githubusercontent.com/61594968/90269617-e3c9d400-de26-11ea-8baa-66a636b587a1.png)
Also same problem (no reaction on gamepad) in Hashiriya - Ookami-tachi no Densetsu

**Comment by noiseshaade** [comment]
![image](https://user-images.githubusercontent.com/61594968/90273073-5ee1b900-de2c-11ea-8900-5912b47bbecb.png)
Works okay if chose standart gamepad, no analog or dualshok

**Comment by notaz** [comment]
The game likely doesn't support dualshock, other emulators probably emulate the compatibility mode dualshock which is the same as selecting 'standard' here.
