### ISSUE TITLE
[Audio] Squaresoft Xenogears sound effects are inaccurate and distorted

### ISSUE THREAD

**Issue by jmaneyrol69** [notaz/pcsx_rearmed#171]
## Description

Most of Xenogears sound effects (ambiance, gunshot, effects in the option screen, etc.) are inaccurate and distorted.
Music, XA and video audio are not affected.

## Game versions

Seems to affect every versions I have tried (JAP, US/NTSC), including the undubbed patched version.

## PCSX version

This has always been present since early PCSX and still present with its various forks (Reloaded, ReARMed, PCSX4ALL).

## OS

Windows, Linux, Android

## Plugins

Default

## Misc.

ePSXe, Mednafen and Duckstation are the only emulators for ARM I know which render Xenogears sound effects properly.

**Comment by jayare5** [comment]
Can this be fixed? I ask because PCSX ReARMed is an abandoned emulator, but if it's possible for others to come in and fix it, I'd be willing to help with a bounty at least... :D

**Comment by taquitoboy** [comment]
> 
> 
> Can this be fixed? I ask because PCSX ReARMed is an abandoned emulator, but if it's possible for others to come in and fix it, I'd be willing to help with a bounty at least... :D

This has been an issue with the sound plugin used in rearmed - P.E.Op.S. DSound v1.9.
I've known this for the longest time. I believe Eternal SPU v1.50 should be able to give you better sound, but I don't know how to do this

**Comment by gdniw** [comment]
I have the same issue.

**Comment by notaz** [comment]
Is this still an issue in the latest version? I'm not familiar with this game and don't know how it's supposed to sound.

**Comment by notaz** [comment]
This has now been fixed, the menu sound a least. Note that you also need to set "Sound Interpolation" to "Gaussian" for this game or there will be occasional minor crackling. If something still sounds wrong in this game feel free to reopen.

**Comment by jayare5** [comment]
I just tested this, it sounds great!!!! Man, PCSX ReARMed is behaving a lot better these days, I am really glad to see this and a whole lot of other improvements including proper scaling!! Thank you so much notaz.
