### ISSUE TITLE
Crash on GPi Case with recalbox 7.1.1 with pi zero w

### ISSUE THREAD

**Issue by D4rkF4ce** [notaz/pcsx_rearmed#176]
Crashs every time on start. Try multiple games (games always have both files bin + cue) with Libretro PCSX_REARMED game is starting but super slow, nearly unplayable :( 

(all 6 bios files for psx in bios folder. Green thumb from bios check on GPi)

Does anybody have the same issues?

BR,
D4rk!

**Comment by notaz** [comment]
You need to at least post some logs as it's impossible to help you with the information provided. Closing as there is nothing I can do.
