### ISSUE TITLE
Final Fantasy 7 (NTSC U/C) quits to desktop after first battle in game

### ISSUE THREAD

**Issue by vitmich** [notaz/pcsx_rearmed#177]
Hello,

It looks like on current version of PCSX-Rearmed on Windows Final Fantasy 7 is unplayable on default settings in Retroarch (1.9.2 - current stable). After begining of game when cloud jumps out of train and first battle with two EX-Soliders is ending Retroarch is hangin and few second later quits to the desktop. This problem is also present on current steam version. I tried both versions - standalone and steam. Only fix for this is disable Dynamic Recompiler. So I play without Dynamic Recompiler and FF7 is working without issues.

**Comment by dagazik** [comment]
It looks like these problems are related: https://github.com/libretro/pcsx_rearmed/issues/503

**Comment by notaz** [comment]
I've pushed a fix that is likely fix these issues, but I don't know when it's going to reach the libretro fork.

**Comment by dagazik** [comment]
Thanks for fix. In the latest version, dynarec works without crashes. :slightly_smiling_face:
