### ISSUE TITLE
Rakugaki Showtime japan

### ISSUE THREAD

**Issue by kounabi22** [notaz/pcsx_rearmed#178]
The game is not responding to the controls when you enable the multitap option side a or side b or both.
It support 4 players but only 2 is enable with multitap option off.

**Comment by gameblabla** [comment]
> The game is not responding to the controls when you enable the multitap option side a or side b or both.
> It support 4 players but only 2 is enable with multitap option off.

This is an oversight in the source code : it only polls for 2 controllers. I don't think he was planning on supporting 4 controllers but it is possible to fix that. (i believe libretro's fork fixed it already)

**Comment by notaz** [comment]
I assume this is fixed by now. Feel free to reopen if not.
