### ISSUE TITLE
Screen vibrating with some PAL games

### ISSUE THREAD

**Issue by RavenKilit** [notaz/pcsx_rearmed#179]
I have a problem with the Grinch and Bugs & Taz time buster eu/pal. while it show the publisher and the loading screen it's all ok, but when I'm on the menu and during the game the screen starts vibrating up and down. If I set the skip frame to 1 it stops vibrating,(I tried 3 different pal rom)
I have not this problem with the us rom

https://youtu.be/3VPd8U_Nb5I

**Comment by notaz** [comment]
This should be fixed in the latest version.
