### ISSUE TITLE
Game crashed 5 hours into play, game saves not present in memcard after restart

### ISSUE THREAD

**Issue by lukeplausin** [notaz/pcsx_rearmed#180]
I was playing a game for about 5 hours in PCSX reARMed and it crashed - a totally normal thing to happen when running games on an emulator.

When I restarted I was disappointed to find that none of the saves I'd made in the session were on the memory card. The state of the memory card was exactly like it was at the start of the session, so it seems as though PCSX reARMed didn't write any of the data to disk during that 5 hour session.

It seems as though PCSX reARMed hasn't saved anything during the session. I think it would be better if PCSX flushed memory card data to disk now and then in case a crash happens.

Running on Retropie/Raspberry Pi 3 (recent build)

**Comment by dankcushions** [comment]
are you using lr-pcsx rearmed? if so, you’re in the wrong repository, and retroarch already has the option to auto-save to disc periodically: https://www.reddit.com/r/RetroPie/comments/4dj2v0/help_setting_up_autosave_intervals/

**Comment by lukeplausin** [comment]
> are you using lr-pcsx rearmed? if so, you’re in the wrong repository, and retroarch already has the option to auto-save to disc periodically: https://www.reddit.com/r/RetroPie/comments/4dj2v0/help_setting_up_autosave_intervals/

Thanks for the info - I didn't know this comes from retroarch. I'll try this
