### ISSUE TITLE
Controller not working in PCSX ReARMed (Kodi, IAGL)

### ISSUE THREAD

**Issue by drrak** [notaz/pcsx_rearmed#181]
_Translator:_
Controller not working in PCSX ReARMed. Tried setting up every kind of PS controller and nothing. I tried the Beetle PSX emulator and the controller worked, but this emulator is poorly optimized.

Please help.

PS. I don't use RetroArch only [IAGL](https://github.com/zach-morris/plugin.program.iagl).

_RPi4, LibreELEC 9.97.1, Kodi 19.1, IAGL 3.0.3_

**Comment by Gorole** [comment]
I Have same issue

**Comment by notaz** [comment]
As it's works in RetroArch this can not be the core's fault. If you proof otherwise feel free to reopen.
