### ISSUE TITLE
Worms Pinball: No graphics/garbage in Language screen

### ISSUE THREAD

**Issue by gameblabla** [notaz/pcsx_rearmed#197]
The game successfully boots since https://github.com/notaz/pcsx_rearmed/commit/dc0ee8d424293ea687a137ec1ca0440f88a1e5a5 on both HLE and Sony BIOS.
However, when you get to the language screen after the memory card screen, it would either have corrupted (green looking) graphics or absolutely nothing at all. (so in effect, it will still display the last remnant in the framebuffer)

If you press X/START, it would get to the titlescreen normally (and you won't get further graphical corruption).

This could be caused by either of those things :
- CDROM timings (they are still not quite accurate)
- DMA
- GTE (and related timings for it)

**Comment by notaz** [comment]
I think this is fixed by now.
