### ISSUE TITLE
Moon Remix RPG Adventure - Game freezes during Clis's concert cutscene

### ISSUE THREAD

**Issue by webbedspace** [notaz/pcsx_rearmed#211]
When you begin this cutscene (which is about 80% through the game), the stage is dark, but spotlights are timed to come on alongside the vocals in the music track (see image below taken from Beetle PSX). In the Rearmed libretro core r22 c54faa9, the spotlights never come on and the game appears to freeze/softlock.
![Moon Remix RPG Adventure (Japan)](https://user-images.githubusercontent.com/83939/131616034-a13fc200-daf6-4c23-b4b0-f1d7499c2a80.png)

Note that there is another concert cutscene in the game, which does not have this issue.

**Comment by gameblabla** [comment]
A memory card save that starts before said cutscene would be nice as the game is quite long.

**Comment by notaz** [comment]
This appears to work now, closing.
