### ISSUE TITLE
Hot wheels Turbo Racing (requires proper emulation of GPU busy state)

### ISSUE THREAD

**Issue by gameblabla** [notaz/pcsx_rearmed#217]
So there's a PS1 game, Hot Wheels : Turbo Racing, that relies on proper emulation of GPU busy states otherwise, it will black screen after the intro.
PCSX Reloaded actually has a hack for that game called "Enable GPU busy state" which is implemented plugin-side.
However for Rearmed, this won't work (i already tried), requiring us to probably implement it within psxdma.c.

The hack can be seen in action here
https://github.com/gameblabla/pcsxr/blob/6484236cb0281e8040ff6c8078c87899a3407534/pcsxr/plugins/dfxvideo/gpu.c#L1586

**Comment by notaz** [comment]
I've added some approximation which seems to be good enough for this game.
