### ISSUE TITLE
Request for adding Aarch64 dynarec 

### ISSUE THREAD

**Issue by Ntemis** [notaz/pcsx_rearmed#218]
This legendary emulator that is now considered to be the most used is in great needs to support the aarch64 dynarec too as arm32 hardware is steadily getting obsolete now days and new boards coming out are aarch64 only

**Comment by iconoclusterdotexe** [comment]
You are absolutely right. Pcsx_rearmed can run a very large amount of games and it's so sad to hear it hasn't a dynarec support for aarch64. I hope someone works to make it possible.

**Comment by dankcushions** [comment]
the [libretro port](github.com/libretro/pcsx_rearmed) supports the lightrec dynarec which supports aarch64 and others, but it's [not particularly quick](https://github.com/libretro/pcsx_rearmed/issues/523).

my understanding is that pcsx_rearmed chiefly exists as a super-fast arm32 psx emulator. to that end it has a custom arm32 dynarec and neon gpu plugin. to be honest, if you have a device capable of aarch64 you can probably run other more general-purpose psx emulators like duckstation, which probably have same/more compatibility. 

all that said, i believe lightrec was implemented in pcsx_reloaded standalone, so i guess could be ported here, but maybe it's expanding the focus/support overhead too far for an emulator which has a specific target.

**Comment by Ntemis** [comment]
Then how about porting the duckstation aarch64 dynarec to pcsx_rearmed?
And no duckstation is not better just because it cant support oglesv2 api at all so it has to fallback into software rendering and that sucks on the likes of all aarch64 boards with lima support

**Comment by gameblabla** [comment]
The only thing close to that would be to merge lightrec from the libretro fork to this one.
This would at least speed it up on decent ARM64 platforms but i understand that this may not be enough for some people.

**Comment by Ntemis** [comment]
Lightrec doesnt work its tested in various scenarios and always failed to float. Is a broken dynarec and i see no hope

**Comment by notaz** [comment]
FWIW I've got something working and pushed it, it works for me on r-pi4 with 64bit distro, everyone is welcome to test it on their setups.

**Comment by m4xw** [comment]
I will get to it when I find some free time, good stuff.
@Gillou68310 wanted to work on this himself as well, so he might be also interested.

**Comment by Ntemis** [comment]
@notaz You the man! Thank you for reviving this emulator for future generations.
Kudos for an amazing work as always.
