### ISSUE TITLE
Problem with Logitech Dual Action Gamepad (G-UD8)

### ISSUE THREAD

**Issue by ydamigos** [notaz/pcsx_rearmed#22]
Hi everyone,

I use the last PiMAME 0.7.7 image on my raspberry pi and run the pcsx-reARMed. 
I have a strange problem with my Logitech Dual Action Gamepad (G-UD8).
All buttons work correctly except for the analog sticks and d-pad.
pcsx-reARMed sees the left analog stick as button /0x00 and not as an analog stick at all.
D-pad is not working at all.
The left analog stick works fine in the pcsx menu where you select the BIOS and other configuration options, including button mapping.

Here is my button mapping from the pcsx.cfg

binddev = sdl:Logitech Logitech Dual Action
bind \x00 = player1 UP
bind \x00 = player1 DOWN
bind \x00 = player1 LEFT
bind \x00 = player1 RIGHT
bind \x00 = player1 L3
bind backspace = Fast Forward
bind escape = Enter Menu
bind \xA0 = player1 SQUARE
bind \xA1 = player1 CROSS
bind \xA2 = player1 CIRCLE
bind \xA3 = player1 TRIANGLE
bind \xA4 = player1 L1
bind \xA5 = player1 R1
bind \xA6 = player1 L2
bind \xA7 = player1 R2
bind \xA8 = player1 START
bind \xA9 = player1 SELECT
bind \xAB = player1 R3
bind f1 = Save State
bind f2 = Load State
bind f3 = Prev Save Slot
bind f4 = Next Save Slot
bind f5 = Toggle Frameskip
bind f6 = Take Screenshot
bind f7 = Show/Hide FPS
bind f11 = Toggle fullscreen

**Comment by notaz** [comment]
Closing this since it's 10 years old and is unlikely to ever get fixed. Things like that are more likely to work by running the emu as a libretro core through RetroArch or whatever.
