### ISSUE TITLE
To Heart (Japan) (Disc 1) freeze when first met a character.

### ISSUE THREAD

**Issue by bulzipke** [notaz/pcsx_rearmed#225]
This is a very old issue.
This game freezing when first meet a character.

To reproduce this bug, proceed as follows.
```
START(始めから)
NAME CHOOSE(決定)x4
NAME CONFIRM(はい)
A button press until meet character. (probably takes about 2 minutes) 
```

As far as I know, it occurs not only in pcsx but also in epsxe, vgs, and bleem.

However, this does not happen in mednafen / swanstation.
Let me know if there's anything I can help with.

Thank you :)

**Comment by gameblabla** [comment]
Can confirm. This does not happen on PCSX Reloaded but does hang in PCSX Redux.
I mean like huh.... how odd.

**Comment by gameblabla** [comment]
Apparently this is one of the few games to require GPU busy states.
A changelog also listed the following games :
"To heart, Ishin No Arashi, Dukes hazzard Racing for Home, Hot wheels: turbo racing, U.P.P"

However in PCSX reloaded this works even without GPU busy state hack being enabled. I guess though that i would need to implement at least partially GPU busy states.

**Comment by notaz** [comment]
This one is quite nasty as a combination of gpu drawing/dma/cpu timing has to fall withing a certain timing window for it to see the busy/idle bit that it wants or else the game softlocks itself. For now (or forever) I've resorted to a hack.
