### ISSUE TITLE
IOS < 6.1 JB Ipad4 screen flashes and reboots when pcsx_rearmed core is loaded

### ISSUE THREAD

**Issue by jack4455667788** [notaz/pcsx_rearmed#23]
I and several others have been having an issue where even attempting to load the core on JB 6.0 ipad4 causes the screen to flash briefly, and reboot the device.  Other emulators that reportedly require JIT to function work without issue (PPSSPP, and the NDS4IOS).  Is there some special build required for 6.0? Please tell me there is!! 

I wish I didn't have to do this! Apparently I caused this issue myself when I chose to stay put at 6.0 jailbroken (as users in 6.1.2 even on the ipad4 do not have this issue)

Assuming you respond as I expect you will (that there is nothing you can do to test or resolve because you yourself are at 6.1.2 and it's working there), is there anything I could try/do to help the process? I have already searched for log files, but it appears the crash is so instantaneously severe that none are made.  I would love to capture a crash report for you (if that would help)... Where should I look for instructions on how to accomplish that (keeping in mind that I only have a snow lepoard hackintosh at my disposal currently).

I will do whatever possible to get this working, please give me orders! In any case, thank you so much for your hard work!! From what I have read, your pcsx_rearmed rocks! (and I am dying to try it myself)

**Comment by notaz** [comment]
JB problems from 2014 are unlikely relevant any more, closing.
