### ISSUE TITLE
[REQ] WiiU Dynarec support

### ISSUE THREAD

**Issue by Ploggy** [notaz/pcsx_rearmed#238]
I apologise if I have made this same issue before I honestly cant remember, I looked through the issues list and cant see it so I think I haven't :P

Would it be possible to add JIT support for the WiiU? Some work had been done to bring the WiiSX Dynarec to the WiiU, with some success but the games speed if still pretty slow..
https://youtu.be/OiUVsAKBMC8

Here is the last devs work on WiiU if it helps at all :)
https://github.com/embercold/pcsx_rearmed

**Comment by notaz** [comment]
It's possible to get ari64's dynarec to support more architectures but it's tons of work that's not very fun, especially without having the hardware.

**Comment by Ploggy** [comment]
I don't want to speak for other people but I'm pretty sure a WiiU could be arranged?

**Comment by Ploggy** [comment]
Also there is a WiiU Bounty.. https://github.com/libretro/RetroArch/issues/4852

**Comment by notaz** [comment]
To do something like that purely for the money would take many times more than what that bounty is offering. Perhaps if some other project with ari64's dynarec (like mupen64plus) gains a powerpc backend it will become more realistic to port it over. Doing it from scratch, even somebody motivated would be in a high risk of burnout, as it can be seen in the thread you linked.

**Comment by Ploggy** [comment]
I think the main reason Embercold burned out was because he didn't have the hardware and by the time it was offered he didn't want it and had enough :P
But you are right it is a big ask, I've ask all the PS1 devs I can think of and none of them were interested.. 
Embercold seemingly came out of nowhere and decided to take a stab at it. I'll always be grateful he got us that close, he basically wrote a graphics driver for us :P (another reason for the burnout probably) If you look at the vid you can see we're not a million miles away.. But coming from a non-dev I guess that doesn't mean much :P

**Comment by Ploggy** [comment]
Hi, I have a update on this issue :)
Work is ongoing to bring Lightrec support to the WiiU by zcrc! emulation speed now in most games is actually pretty good, 2d games are fullspeed but alot of 3d games are still running below fullspeed in most cases, threading is being discussed as a solution to that :)

CDDA is also not currently working, we just get static whenever a CDDA audio track plays.
I wanted to ask if you have any idea on how to fix this? zcrc says its an endian issue since CDDA plays fine on little endian.
If CDDA support was fixed alot of games will become fully playable which would help alot while the 3d speed issue is tackled :)

I have a vid of current progress, you can see the issue with CDDA when Rayman plays (@2:52)
https://www.youtube.com/watch?v=hYItuKhgW9E&feature=youtu.be&ab_channel=Ploggy

**Comment by notaz** [comment]
I've patched the cdda as well as the messed up fade in-outs visible in your video.

**Comment by Ploggy** [comment]
Thank you SO much I saw your commits earlier but wasn't sure if it was related to the post I made here :)
I will try and add your changes, I'm not the best at using github, but I'm sure I'll find a way lol
I'm using this branch by quarky, the WiiU changes aren't added to the libretro PCSX repo yet.
https://github.com/QuarkTheAwesome/pcsx_rearmed/tree/libretro-wiiu-v2

Again, thank you very much for doing this, if this does fix the fade and cdda issue the core only needs threading and I think it will be pretty much done :D 

Thank You!

**Comment by Ploggy** [comment]
Fruits of your labour :)
(Ear warning there's a crash when I play Gex Deep Cover Gecko)
https://www.youtube.com/watch?v=71hNOcJzf98&feature=youtu.be

CDDA and the fade issue is fixed! thank you.. a side effect of the fade issue fix is it seems to have fixed a graphic issue with the sun flare in Drivr :D Bonus!

**Comment by Ploggy** [comment]
Hi, I been going through alot of games to test with your CDDA changes and so far all CDDA games seem to play fine, but it looks like your changes may have messed up Music/SFX in a couple games. 
In Vagrant Story and Legend of Mana both have no sound at all, neither Music of SFX seem to play, there maybe more games that have this issue but these are two I have found so far.. they are both Square games dunno if that's important or just coincidence.
Audio plays correctly on both games on a build from before your CDDA changes.

**Comment by Ploggy** [comment]
Ha turns out that the issue I was having with no audio in some games was already fixed by you by the time i posted my post above.
I wasn't able to test your latest source at the time but now that I have I can say its fixed.. So please disregard my post above Thank You :)

**Comment by notaz** [comment]
Closing because other projects are taking care of this.
