### ISSUE TITLE
#215 broke Vib-Ribbon

### ISSUE THREAD

**Issue by bslenul** [notaz/pcsx_rearmed#239]
Pretty much the same issue as the Libretro core: https://github.com/libretro/pcsx_rearmed/issues/590 basically in Vib-Ribbon the music isn't playing (with the in-game musics or an audio CD) and because of that there's only a flat line without any obstacles...

After bisecting standalone as well, here's the first bad commit: f4627eb3cb482fa3786b63e9ff4c9723ac792ce1

**Comment by notaz** [comment]
Pushed some things that should help (both here and the libretro).

**Comment by bslenul** [comment]
Thank you, just tested and yup it seems to work fine now! 👍 

Closing!

**Comment by CometHunter92** [comment]
That solved https://github.com/libretro/pcsx_rearmed/issues/593 too, beside Dino Crisis "stuttering speech" and the "engine noise stuck in pause menu" issue. 
Thanks!
