### ISSUE TITLE
ERROR: Segmentation fault in recompiled code: invalid load/store at address 0x16c1b49c

### ISSUE THREAD

**Issue by Bommel24** [notaz/pcsx_rearmed#240]
In Retroarch (PCSX-ReARMed r24l 12fc127)  in "Crash Bandicoot 2 - Cortex Strikes Back" (SCES00967) - On Windows 64bit.
I tested this specifically during the N.Gin Bossfight.
To reproduce: 
Save a savestate.
Close the emulator.
Restart the emulator and load the savestate.
Wait 10 seconds and the core crashes with a Segmentation fault.

**Comment by notaz** [comment]
Windows 64bit? Unless you mean arm64 it will be lightrec which was never submitted here.
