### ISSUE TITLE
RetroArch AA64 Core Crashing

### ISSUE THREAD

**Issue by GilesMarchand** [notaz/pcsx_rearmed#243]
After today’s nightly while playing FF7 on Disc 2, I’m stuck on the world map, as loading an area causes a crash. This has only become an issue in the last two days transferring my save to another device with an older version of the same Core allows me to continue playing. Converting the save to use with another emulator also allows me to continue playing as well. I have checked all my options and it’s caused by the update.

**Comment by CometHunter92** [comment]
maybe it's better to open the issue in the libretro repo
https://github.com/libretro/pcsx_rearmed/issues
(and maybe upload the save file too)

**Comment by CometHunter92** [comment]
however maybe it's this that breaks the aarch64 dynarec
https://github.com/libretro/pcsx_rearmed/commit/641d7badb70e58c4fbab04fa70212e6e7b7cdaaa

**Comment by notaz** [comment]
This issue is expected to be fixed in the latest version. Feel free to reopen if it's not.
