### ISSUE TITLE
Fix up soul blade hidden characters and edge master mode and main menu

### ISSUE THREAD

**Issue by Jackmath5** [notaz/pcsx_rearmed#246]
Can you fix soul blade main menu, edge master mode battles, hidden characters such as han myong, sophitia!, Sophitia!! And Siegfried!, Also fix up tai Fu the wrath of tiger, transformers beast wars transmetals, also fix up battle arena toshiden 1 chd, fix up mortal Kombat 4, fix up street fighter games for ps1?

**Comment by notaz** [comment]
At least some of the games you listed are now fixed. If something is still not working please open separate issues for each game.
