### ISSUE TITLE
Some resource leak bugs

### ISSUE THREAD

**Issue by ryancaicse** [notaz/pcsx_rearmed#249]
Hi, there are some minor resource leak bugs in the program.

Files referenced by `fin` and `fout` are not closed before Line 59, 73, 84, 91, 98.

https://github.com/notaz/pcsx_rearmed/blob/fbf19ce6b6c02da47a67f58e23d8294cfcd18f55/tools/psxcimg.c#L56-L114

File referenced by `fout` is not closed before Line 137.
https://github.com/notaz/pcsx_rearmed/blob/fbf19ce6b6c02da47a67f58e23d8294cfcd18f55/tools/psxcimg.c#L126-L139

**Comment by notaz** [comment]
The leaks don't matter since it's exiting the whole program with failure anyway. If someone wants to send a patch I don't mind though.

**Comment by ryancaicse** [comment]
Thanks, I would send patches soon

**Comment by notaz** [comment]
Closing as per previous explanation.
