### ISSUE TITLE
Final Fantasy VIII - Missing sound effects with standard audio plugin, new verison of the plugin 'available'

### ISSUE THREAD

**Issue by OmegaPhil** [notaz/pcsx_rearmed#25]
As audio is the only remaining significant thing I can find wrong with rearmed emulation since I started using it some months ago (thanks!), I'm finally making a ticket to at least gather some information.

I originally mentioned it [in my other ticket](https://github.com/notaz/pcsx_rearmed/issues/17#issuecomment-15546907) - currently summoning Guardian Forces (e.g.  Quezacotl) makes it 'look' like the current audio code drops sound effects when it gets overwhelmed - faster examples are casting the Dispel and Blind magics - being a long-time player I can tell the sound is pretty mangled.

Some searching shows that [this is discussed elsewhere too](http://forum.themaister.net/viewtopic.php?id=828) - apparently there is an improved version of the audio plugin, [v1.10b](http://www.ngemu.com/forums/showthread.php?t=140191), but it is Windows-only.

I have had a quick look at the code, and clearly there is still GNU/Linux code there (ALSA source in a 'Windows only' build??) - I have a little C/C++ experience, am wondering how stupid I would be to think of porting this as a possible future 'fun' project, since I have no emulation, embedded or sound experience ;)

Aside from that, do you have any plans to improve the audio plugin based on the above? Has your source already diverged too much from the original?

Thanks for any feedback.

**Comment by notaz** [comment]
This is an old report, non-trivial thing to check, and there were lots of changes in SPU so I'm going to naively assume it's fixed. Feel free to reopen if not.
