### ISSUE TITLE
Ps1 audio slowdown, stutter and slowdown eg tomba 2

### ISSUE THREAD

**Issue by CloudTF25** [notaz/pcsx_rearmed#253]
So when you play the first level and allow the music to change to a different track after a minute. The new track will stutter and slowdown

ps: i'm using thepsxonpsp660.bin and a clean dump of the game in CHD format.

video below shows the issue in action

https://user-images.githubusercontent.com/67326185/173455293-de14fbdb-1c10-460a-9324-b41a14cb86e8.mp4

This same issue happens excantly the same on my raspberry pi 4, so it definitely isn't a issue with my miyoo mini that runs on the same core

**Comment by schmurtzm** [comment]
I confirm the behavior (on freshly compiled Retroarch and PCSX Rearmed core) : when the song change a lot of sound stuttering but framerate seems to stay good.
Same behavior on PCSX Rearmed standalone (better framerate globally but still a lot of sound stuttering after the first song).

**Comment by schmurtzm** [comment]
Same result with Retroarch on Windows. So it's not a lack of power from the Miyoo Mini.
On real PS1 and on others PSX cores it's always the same first track which is played (we when arrive at the end, the same track start again). With pcsx, it starts another track with a lot of stuttering. It's like if it tries to play a wrong track.

**Comment by schmurtzm** [comment]
Seems to works better now !  Now the first audio track restart at the end.
Thanks @notaz  !
