### ISSUE TITLE
Alien Resurrection (USA) in CHD format crashed then start "New game" on New Nintendo 2ds XL

### ISSUE THREAD

**Issue by Maxcimkj** [notaz/pcsx_rearmed#257]
Hi!
I use pcsx_rearmed emulator on New Nintendo 2ds XL with retroarch. Alien Resurrection (USA) in CHD format crashed then click start "New game" after loading. 
PBP image of  Alien Resurrection (USA) work fine with good fps !!!

Game screenshot before crash:
![Alien Resurrection (USA)-220723-055759](https://user-images.githubusercontent.com/31892550/180611771-35d0ba11-e28a-4906-bf42-429259643439.png)

Screenshot with error:
![error_screen](https://user-images.githubusercontent.com/31892550/180611937-c3c852b1-3e76-47e8-a558-b833b8708db2.jpg)

Error dump:
[crash_dump_00000002.zip](https://github.com/notaz/pcsx_rearmed/files/9174073/crash_dump_00000002.zip)
Alien Resurrection CHD image:
https://disk.yandex.com/d/YzXErNYZ9Qx6Nw

System info:
New Nintendo 2ds xl - Firmware 11.15.0-47E
Luma3DS v11.0

Retroarch info:
![retroarch_info](https://user-images.githubusercontent.com/31892550/180612351-f9c17884-42db-40e9-96a6-b2a21467a5a0.jpg)
![pcsx_rearmed_core_info](https://user-images.githubusercontent.com/31892550/180612356-11da9ea7-c1c9-4409-9408-c8286d7d3bfa.jpg)
Core settings:
[PCSX-ReARMed.zip](https://github.com/notaz/pcsx_rearmed/files/9174198/PCSX-ReARMed.zip)

**Comment by Maxcimkj** [comment]
PBP image of  Alien Resurrection (USA) work fine with good fps

**Comment by notaz** [comment]
It works on raspberry-pi4 but crashes hare in system libraries, so probably can't be fixed without the device.

**Comment by mahirahman** [comment]
Try Quick Menu -> Options, set CD Access Method to Sync and restart the core

**Comment by notaz** [comment]
Assuming this works now, feel free to reopen if not.

**Comment by notaz** [comment]
No, there are even new functions now that ignore the async code altogether and would crash if it's enabled.

Is this threaded cdrom stuff actually that useful? If it's for .chd slowness there is now zstd support that should decompress faster.

**Comment by pcercuei** [comment]
@notaz I see you added physical CD-Rom support recently, it might be useful for that, no?

**Comment by notaz** [comment]
The physical cdrom stuff has it's own cache/read-ahead. It could probably be refactored to apply for cdriso too in favor of the other design simply because it's my own and easier for me to maintain (not that I have any proof that my design is actually better). But I'm not convinced this is needed for image file formats as the OS should be doing things like readahead anyway (except console OSes maybe?).

**Comment by pcercuei** [comment]
Ok. I have long-term plans to get it running on the Dreamcast (I added SH4 support in Lightning), so having physical CD-Rom support is great.

If this is not needed for image files, then maybe drop the threaded code - so that nobody else asks :)

**Comment by notaz** [comment]
Seems like it was added in libretro/pcsx_rearmed#391 by @justinweiss for the 3DS and reportedly also helped slow Android devices. But it's more than a year since this code has been disabled and nobody complained so IDK...

**Comment by justinweiss** [comment]
Yeah — the 3DS had extremely slow SD access, and games that streamed from disc were really badly affected by it. It was much less of a problem with CHD files.
