### ISSUE TITLE
WipEout 3 (USA) in CHD format crached then click Close content in Retroarch Quick menu on New Nintendo 2ds XL

### ISSUE THREAD

**Issue by Maxcimkj** [notaz/pcsx_rearmed#258]
Hi!
I use pcsx_rearmed emulator on New Nintendo 2ds XL with retroarch. WipEout 3 (USA) SLUS00865 in CHD format crashed then click Close content in Retroarch Quick menu after loading. 
PBP image of  WipEout 3 (USA) work fine with good fps !!!

Retroarch screenshot before crash:
![retroarch_close_content](https://user-images.githubusercontent.com/31892550/180613464-e1200ba9-42c3-41ab-b445-003dffb6f746.jpg)
Screenshot with error:
![error_screenshot](https://user-images.githubusercontent.com/31892550/180613546-6c0d6ea8-0ae1-4112-ba04-422b35dd046a.jpg)
Error dump:
[crash_dump_00000004.zip](https://github.com/notaz/pcsx_rearmed/files/9174139/crash_dump_00000004.zip)
WipEout 3 (USA)  CHD image:
https://disk.yandex.com/d/6br43ZmN2CZGZQ

System info:
New Nintendo 2ds xl - Firmware 11.15.0-47E
Luma3DS v11.0

Retroarch info:
https://user-images.githubusercontent.com/31892550/180612351-f9c17884-42db-40e9-96a6-b2a21467a5a0.jpg
https://user-images.githubusercontent.com/31892550/180612356-11da9ea7-c1c9-4409-9408-c8286d7d3bfa.jpg
Core settings:
[PCSX-ReARMed.zip](https://github.com/notaz/pcsx_rearmed/files/9174199/PCSX-ReARMed.zip)

**Comment by notaz** [comment]
Is this still an issue?

**Comment by notaz** [comment]
There were some CHD updates and it all works on PC and r-pi on ARM, so I assume it is fixed.
