### ISSUE TITLE
WipEout 3 - Special Edition (Europe)  in PBP format didn't work with any emulator version

### ISSUE THREAD

**Issue by Maxcimkj** [notaz/pcsx_rearmed#259]
WipEout 3 - Special Edition (Europe) - SCES-02845  in PBP format didn't work with any emulator version. Retroarch just close up after starting the game.
PBP image to WipEout 3 - Special Edition (Europe):
https://disk.yandex.com/d/MwG8J91a2arkkQ

USA version SLUS00865 in PBP format working fine!!
PBP image WipEout 3 (USA):
https://disk.yandex.com/d/SpVTgrPqPRV9RA

**Comment by notaz** [comment]
Both are working here, so maybe this was fixed. Closing.
