### ISSUE TITLE
(Pcsx-ReArmed in Retroarch Android)List of Sound Effects that are emulated inaccurately or are Missing in FF VII-IX

### ISSUE THREAD

**Issue by mckimiaklopa** [notaz/pcsx_rearmed#26]
Since notaz requested a list of the sound problems,here it goes:
FF7 
Sound:
*Cursor sound-not whole and sometimes sound is diff. for each movement(sound should be the same) 
*The sound produced when  equipping materia also is not whole
*At very beginning of the game when the train stops,the sound of steam or pressure is missing
In battle:
*Tifa's punches- sound is so 8-bit.It is supposed to sound like a punch
*Yuffie's attacks-the sound produced is only similar to a single 'tinkle'.It is supposed to sound like a slash.
*Machine gun sounds(from Barret and from some enemies)-it is missing an explosion-like sound at the end.
*Sound while the character summons-a sound effect is missing
*Sound while character is casting a spell-i think it is missing reverb? IDK but something is missing
*Majority of spells(especially fire and bolt spells)-missing explosion like sounds,electricity sounds and other stuff
Music in general-Missing reverb

FF8:
nearly the same as FF7
a sound effect when using diamond dust is missing

FF9:
Similar to FF8
The sound produced when equipping an ability is a bit short and silent(should be whole and loud)

sorry if i could not list all problems

**Comment by mckimiaklopa** [comment]
as of r22,most if not all sound effects are now emulated accurately and this applies to other games beside FF games.

Music is now close to psx levels of accuracy but it is still pretty much imperfect.All instruments are now present unlike before where some instruments are missing,reverb and interpolation are now added and music now plays very smoothly unlike before where the timing of some instruments are off.
Unfortunately,music is still missing some reverb?/pitch effect?/echo?/filter?/layer/interpolation?(not really sure).To put it in a way,the music  tries hard to be like the psx but ultimately comes off as fakish.

**Comment by notaz** [comment]
There are some new core filter options that you can try.

Note that the sound output also depends on the device you're listening on, it can never be 100% like the real thing.

**Comment by mckimiaklopa** [comment]
you mean the audio filters or the sound interpolation?


What i was trying to say above is that the reverb in some instruments does not sound "reverbed" enough making the overall music feel empty at times

thanks for the suggestion though

**Comment by notaz** [comment]
Is this still an issue after all these years?

**Comment by notaz** [comment]
Closing, you can open new issues if needed.
