### ISSUE TITLE
[Feature Request] Open Kaillera implementation 

### ISSUE THREAD

**Issue by ZzackKbin** [notaz/pcsx_rearmed#260]
Hi 
Is possible add open kaillera module for core PCSX rearmed ? Netplay in retroarch is unplayable full of teleports. 
Kaillera Roborn Project: 
https://kaillerareborn.github.io/
https://emulinker.org/web/links/
https://emulinker.org/web/downloads/

I tested open kaillera supraclient with emulinker servers and games like Tekken 3, Winning Eleven are smoothly and input lag is low.

**Comment by notaz** [comment]
I have no plans to work on this, and doubt anyone else has.

**Comment by ZzackKbin** [comment]
hello 
Is unofficial pcsxrearmed with kaillera
https://kaillerareborn.github.io/
