### ISSUE TITLE
BIN/IMG support broke recently

### ISSUE THREAD

**Issue by DrUm78** [notaz/pcsx_rearmed#261]
Software: PCSX fork: https://github.com/DrUm78/pcsx_rearmed
Hardware: FunKey S handheld device with armv7 NEON

Not sure what commit broke it but ROMs with .cue/.bin or .cue/.img format does not load anymore, the user is just sent back to the desktop. Nothing relevant in the logs I got from GMenu2X. Maybe that's a side effect of the PBP fixes?
It worked for sure before this one (does not mean it's the culprit though): [d9e2b173fb11fea4976fb0a6c5feda6b654b4b46](https://github.com/notaz/pcsx_rearmed/commit/d9e2b173fb11fea4976fb0a6c5feda6b654b4b46).
.PBP and .CHD still work however. Does .BIN work for you?

Steps:
1. Try to load any ROM with .cue/.bin or .cue/.img format
2. Notice that you are sent back to the desktop

**Comment by notaz** [comment]
Pushed something, if it doesn't help you'll have to bisect the bad commit. It always worked for me as I test with .cue/.bin, so either FunKey does something different (maybe has alignment checks enabled) or your compiler does.

**Comment by DrUm78** [comment]
Still the same issue with your last commit. Will bisect to find the culprit commit. 👍

**Comment by DrUm78** [comment]
Seems that's an issue on my side, which I cannot explain... .bin/.img have never worked for me in fact (tested with old code) but I managed to get them working again with a weird workaround: I compile the binary inside the FunKey OS. So not sure you can do something on your side.

**Comment by DrUm78** [comment]
@notaz The culprit is the last libchdr update after https://github.com/rtissera/libchdr/commit/045f2a7f23f5ac10c0122f6f56e42023dfb71e2a commit. Restoring this commit fixes the issue. I close this ticket and will open one on the libchdr repo. Thanks for your help. 👍

**Comment by DrUm78** [comment]
@notaz One remark though: I just noticed that last commit of libchdr works well with .bin/.img on PicoDrive (myrepo: https://github.com/DrUm78/picodrive-funkey). Could this be that PCSXR implements this submodule a different way and causes this issue?

**Comment by pcercuei** [comment]
@notaz the fix will break things for big-endian systems...

**Comment by DrUm78** [comment]
I bisected libchdr commits and the one that breaks .bin/.img support (and .cso for PicoDrive) is https://github.com/rtissera/libchdr/commit/40ec221c8a35a2fb90dc640a1e4e9fd6524506e8.
