### ISSUE TITLE
"Gear Fighter Dendoh" wont load

### ISSUE THREAD

**Issue by schmurtzm** [notaz/pcsx_rearmed#262]
Hi, "Gear Fighter Dendoh" wont load.
I tried on Miyoo Mini (PCSX Rearmed Standalone up to date and same result with RA core) and on PC / Windows. (RA core).
Sometime it just wont load (nothing seems to happens in logs), on Windows with retroarch it crash.
Tried different bios too.
The logs doesn't display any particular error. 

I don't know if it can help but this version of pcsx is able to load the game : https://git.crowdedwood.com/pcsx_rearmed

**Comment by notaz** [comment]
Try a build with the latest commits.

**Comment by schmurtzm** [comment]
Thanks a lot @notaz , not only does it work perfectly on PCSX Rearmed standalone but it also works on pcsx Rearmed libretro core  ! 
That's the best support that we can expect on a core 😄 
It will be integrated in our "[Onion OS](https://github.com/OnionUI/Onion)" for the little handheld "Miyoo Mini"

**Comment by schmurtzm** [comment]
Thanks to your fix I can say that other Bandai games works fine now like “Gundam Battle Assault 2” .
Thank you :)
