### ISSUE TITLE
T'ai Fu: Wrath of the Tiger gets stuck on initial loading screen

### ISSUE THREAD

**Issue by Snowbro88** [notaz/pcsx_rearmed#267]
This game has this problem on PCSX, apparently there are reports that after many minutes it loads, but it is not possible to play it this way, tested on PS Vita with the latest stable version of retroarch.

Could you try to fix it? or is there any particular configuration to solve it?, thanks in advance

**Comment by notaz** [comment]
Seems like a timing issue. Those are difficult to fix.

**Comment by DrUm78** [comment]
Tested on armv7 32-bit and it works fine now, thanks again.

**Comment by Snowbro88** [comment]
Great I'll try it on PS Vita with the latest retroarch nightly, thanks for your attention I'll try to continue reporting other games with problems in this core.
