### ISSUE TITLE
Wing Commander 4 French PAL

### ISSUE THREAD

**Issue by Overflask** [notaz/pcsx_rearmed#270]
At the beginning after the title screen, the game freezes. I can get into the RetroArch menu, but if I go back to the game, the last screen gets imprinted (Quick menu/Resume). I can go to the Game Launcher and it'll save with the last pic which is the frozen menu. If I go back to the game from the game launcher, the screen refreshes and stays black

**Comment by notaz** [comment]
On which platform? On PC it works for me but only with real BIOS.

**Comment by Overflask** [comment]
> On which platform? On PC it works for me but only with real BIOS.

Actually, Schmurtz helped me with it. It works now. But now there's a new issue, changing disks doesn't work. RetroArch identifies disk 2 correctly but the game still asks for CD2

**Comment by notaz** [comment]
How to reproduce that?
Booting from CD2, selecting new game to get it to ask CD1 and then changing CD works for me.

**Comment by Overflask** [comment]
> How to reproduce that? Booting from CD2, selecting new game to get it to ask CD1 and then changing CD works for me.

Ok, nevermind. It works now. The issue seems to have vanished after troubleshooting the game. However, it remains on another RetroArch device (RG503) where the manip you tried would just prompt the game to keep asking for CD1 even if the disk tray shows it already mounted. Do you know by any chance what settings could have caused that?

**Comment by notaz** [comment]
Maybe it runs an older core? This CD change thing was patched quite recently.

**Comment by Overflask** [comment]
> Maybe it runs an older core? This CD change thing was patched quite recently.

I was told to update about last week. But you know what? I'm tinkering with 3 different devices. Let me do some proper tests and I'll report back here. Does PCSX Rearmed Plays well with pbp?

**Comment by Overflask** [comment]
To know what? I understand what happened. The Miyoo uses PCSX Rearmed core, the RG503 Arkos was using  
the PPSSPP core, and the one that works the best is the Duckstation core. For running this game, I recommend the Duckstation core. It fixes every issues
