### ISSUE TITLE
Monkey Hero severe graphical issues.

### ISSUE THREAD

**Issue by Snowbro88** [notaz/pcsx_rearmed#271]
Thanks to the dev @notaz for his incredible work, I hope not to abuse requests but I would like to propose one of the games known as the most problematic to emulate from the entire Play Station catalog, it is Monkey Hero.

The problem that this game presents are severe graphical errors on the title screen and in the gameplay, a solution in this case would be very interesting although I have read that it is extremely complicated, thanks in advance.

**Comment by notaz** [comment]
Push something that should help (referenced a wrong libretro/pcsx_rearmed#271 issue by mistake).

Nothing too special with this game, it's just something no other game does so it wasn't implemented.

**Comment by Snowbro88** [comment]
Well, incredible as always, thanks for the interest @notaz, I really don't remember any more games with problems in pcsx than those that interest me personally, greetings.

**Comment by Snowbro88** [comment]
Tested with the latest nightly, everything works perfectly, thanks, I proceed to close the issue

**Comment by DrUm78** [comment]
@notaz Although it's fixed on x86_64, It's not on armv7 32-bit (GPU NEON). It's better than before but there are now some mosaic effects that appear in some places and dialog boxes are usually empty (see the video below):
https://drive.google.com/file/d/1Z-APeusjdu280D6xjpEddNgLet0RbovO/view?usp=share_link

Do you thiunk it's related to Ari64 dynarec or NEON GPU?

**Comment by swosho** [comment]
On my end (PS Vita, so ARMv7 GPU NEON) there are no graphical issues pictured above.
However, the game doesn't play back any sound effects at all, the only sound produced is the BGM.

**Comment by DrUm78** [comment]
PS Vita is amrv9, maybe with Neon too though.

btw, I have the same sound effect bug too on armv7.

**Comment by Snowbro88** [comment]
The truth is that I had not noticed the lack of sounds in this game, I had never played it because it is not compatible with most emus.

Named the dev @notaz so if you haven't seen these posts you might be interested in reviewing this issue.

On Vita I recommend playing the PAL version so that it goes to 50 fps and reaches stable full speed, in NTSC the music crackles a bit.

**Comment by notaz** [comment]
Closing this one as #315 was opened for remaining sound issues.
