### ISSUE TITLE
[CHD] Sound is broken in several games

### ISSUE THREAD

**Issue by DrUm78** [notaz/pcsx_rearmed#272]
Software: PCSX compiled for Linux 20.04
ROMs: Tekken 1 USA, Lomax USA, Toshinden 1 USA

Games like Tekken 1, Lomax or Battle of Toshinden 1 have their sound broken, just launch the games and you should hear the garbled sound during the intro (for Tekken 1 it starts on the character selection screen). Not sure what commit made this happen, seems to be the last weeks as I did not notice it before.

If you cannot reproduce it, I can send you a video.

**Comment by DrUm78** [comment]
@notaz Ok that seems to happen only with .chd games, I tried the same with .cue/.bin format and there is no garbled sound. I tried the same libchdr commit as you and still the same issue. FYI I convert my .cue/.bin with CHDMAN.

Also, I know that .cue/.bin are broken from this commit of libchdr: [40ec221c8a35a2fb90dc640a1e4e9fd6524506e8](https://github.com/rtissera/libchdr/commit/40ec221c8a35a2fb90dc640a1e4e9fd6524506e8) but rtissera does not seem to be able to reproduce it, so I sent them a gdb stack.

So I guess that's not something you can fix on your side then? Anyway, can you reproduce it?

**Comment by DrUm78** [comment]
Ok I restored PCSX to some code pushed in August with the same libchdr revision and the bug does not occur anymore, so that seems definitely on your side. I keep the ticket open then.

**Comment by DrUm78** [comment]
@notaz I identified the culprit commit: https://github.com/notaz/pcsx_rearmed/commit/9afc3b574dbe79c7a4c615986beb503cc5435864. It worked fine before this commit, not after.

**Comment by schmurtzm** [comment]
I confirm, same observation with chd of pong or GTA.
Tested on libretro core and standalone on the Miyoo Mini.

**Comment by DrUm78** [comment]
Fixed in https://github.com/notaz/pcsx_rearmed/commit/cbd88286c7e8473e1062fbe740ec59a302031531, thanks notaz. 👍

**Comment by schmurtzm** [comment]
Awesome ! Thank you notaz for the incredible reactivity 🥇
