### ISSUE TITLE
PS1 BIOS taken from PS3 Firmware crashes emulator

### ISSUE THREAD

**Issue by teconmoon** [notaz/pcsx_rearmed#273]
Good evening all,

The only Sony console I own is a PlayStation 3, which is also where I purchased most of my original PS1 games. I dumped / extracted all of my purchased PS1 games in addition to the PS1 BIOS utilized by the PS3.

Name: ps1_rom.bin
CRC32: 2F53B852
MD5: 81BBE60BA7A3D1CEA1D48C14CBCC647B
SHA-1: C40146361EB8CF670B19FDC9759190257803CAB7

I tried renaming this BIOS dump to SCPH_PS3.bin and feeding it into RetroArch, however the emulator crashes when trying to utilize this BIOS. I tested this in DuckStation also, but the BIOS works without issues there.

Normally I'd stick with the HLE BIOS, but one of my games hangs when trying to load from a memory card without a real BIOS (Animetic Story Game 1: Cardcaptor Sakura, the only game I own on disc instead of digital!)

I tested this problem in RetroArch for Switch and also Windows. Let me know if there's any other information I can provide. Thanks!

**Comment by DrUm78** [comment]
Same here, I got this error:
```
write_biu: unexpected val: 00000cc4
write_biu: unexpected val: 00000cc0
write_biu: unexpected val: 00000c04
Compile at bogus memory address: 03400008
Jump in the delay slot.  This is probably a bug.
```

**Comment by newhinton** [comment]
I have a very similar error on retroarch:
```
write_biu: unexpected val: 00000cc4
write_biu: unexpected val: 00000cc0
write_biu: unexpected val: 00000c04
```

After that it is just stuck.


_However:_

if i compile the standalone version from git for my pc, the bios runs just fine.

**Comment by DrUm78** [comment]
Yeah PS1 bios now works for me too. 👍
