### ISSUE TITLE
Ari64 dynarec running on x86_x64 (and even potentially 32bit)

### ISSUE THREAD

**Issue by LibretroAdmin** [notaz/pcsx_rearmed#275]
This would make the PCSX ReARMed core the fastest PS1 emulator overnight on x86 systems. And it'd also be helpful since neither SwanStation or Beetle PSX have a HLE BIOS like PCSX ReARMed. For many, this is still the most easy to use entry level emulator available through RetroArch. Ari64 dynarec being as fast as possible would give it a considerable legup in all departments, especially now that the NEON GPU plugin works on x86.

**Comment by notaz** [comment]
It's too much work for too little reward, and it's even unclear if it would even beat lightrec as it (Ari64) has been tuned for ARM mostly. If you think HLE is important lightrec could probably be much easier patched to handle the fake opcodes that PCSX's HLE needs, but that would need figuring out lightrec's internals and mess up @pcercuei's efforts to keep lightrec in sync with upstream. In either case it's far more than the usual evening project that I can commit to.

**Comment by pcercuei** [comment]
HLE is on my TODO list, I just didn't bother yet to see what needs to be done in Lightrec to support it.

**Comment by notaz** [comment]
Lightrec now can do HLE and has good compatibility. Closing.
