### ISSUE TITLE
[REQ] Make Unai Big Endian Compatible.

### ISSUE THREAD

**Issue by Ploggy** [notaz/pcsx_rearmed#279]
This is a request to patch Unai to make it Big-Endian compatible.
Currently the WiiU uses Peops which works fine but isn't as efficient as Unai. 
If Unai were to be made Big-Endian compatible that could provide the boost to speed which the WiiU needs. 

Thanks.

**Comment by Ploggy** [comment]
Update on this :)

Unai has successfully been ported to support Big Endian and speed is up on WiiU!! but there is a couple small issues I've noticed..
There is a shimmer when Dithering is enabled, It's especially noticeable at the Load Save Game screen.
https://www.youtube.com/watch?v=aZ-ZjmRSwvI
The other issue is you can see the texture joins (also noticeable in the vid) It makes the water stages in Crash Bandicoot 3 look awful but I haven't got a vid of that part.
I don't know if this is because the Unai is less accurate so cuts corners to get extra speed from the plugin.
I've compiled a Unai Pcsx_Reamed.dll for PC if you want to see for yourself.
[pcsx_rearmed_libretro.zip](https://github.com/notaz/pcsx_rearmed/files/12700226/pcsx_rearmed_libretro.zip)

**Comment by saulfabregwiivc** [comment]
If UNAI is big-endian compatible now and if runs pretty great on Wii U, can this be ported to the Wii too?

So we can also get benefitied of the speed improvements :)

**Comment by Ploggy** [comment]
I think the plan is to get Unai running on WiiSX and the GC port of PCSX, so I imagine its only a matter of time before it makes its way to Wiistation too :)

**Comment by notaz** [comment]
I'm closing this as AFAIK the big endian conversion is done now.
