### ISSUE TITLE
Run dynarec tasks in separate thread

### ISSUE THREAD

**Issue by inactive123** [notaz/pcsx_rearmed#28]
iOS and Android both have main UI threads that can't be interrupted for too long by any other process/thread. If some thread is blocking, an "Application Not Responding" errror can occur on Android, and in iOS' case, the UI thread will simply kill the entire app.

The source of all problems with people who cannot get PCSX ReARMed to work on iOS even though they can run the code and they have a dynarec-capable jailbreak is to do with the fact that a dynarec task is blocking the UI thread.

One way around this would be to run the dynarec code on a thread so that the dynarec tasks can never block the main thread.

Windows Phone/RT works in a similar way and demands that all tasks be asynchronous for the same reasons (ie. a main thread that can never be blocked for too long). So this affects all mobile platforms post-Pandora really.

**Comment by notaz** [comment]
The recompilation slowdowns have been greatly reduced some time ago so I think this should be no longer an issue unless the device is barely fast enough to run the emu at all.
