### ISSUE TITLE
[REQUEST] Add .m3u support for multi-disk CHD

### ISSUE THREAD

**Issue by Vexnik** [notaz/pcsx_rearmed#280]
I have a large library of .chd files and the majority of them are multi-disk games, it would be neat to have them managed in a .m3u file and launched in one go.

**Comment by notaz** [comment]
I assume you're using the libretro version? That is supposed to have m3u support, doesn't it work?

**Comment by vaguerant** [comment]
Works here. I don't have any multi-disc games so I just did this:

`multi-disc.m3u`
```
Ape Escape (USA).chd
Pac-Man World (USA) (Demo).chd
```
Placed that file in a folder with the two mentioned `.chd` files and I can swap between discs at will. It "works" in the sense that I can swap discs from the PS1 BIOS screen to change which game boots up.

Possibly user is confused by the [libretro docs](https://docs.libretro.com/library/pcsx_rearmed/#multiple-disk-games), which do **specifically** tell you to put all your `.cue` files into an `.m3u`:

> Create a text file and save it as `foo.m3u`. Then enter your game's .cue files on it.

**Comment by notaz** [comment]
Thanks for testing, closing.
