### ISSUE TITLE
FYI: Xcode compatible ARM64 dynanrec ASM attached

### ISSUE THREAD

**Issue by JoeMatt** [notaz/pcsx_rearmed#281]
Hi,

This isn't so much a "issue" as it is a note/bookmark for devs or anyone else interested in pcsx_rearmed with dynarec on iOS.

The ASM format doesn't work with Apple's asm parser, and the perl script in the project to convert wasn't working for me.
For my app Provenance, I'm working on getting this to run on iOS so I bit the bullet and manually converted the asm to XCode compatible format.

So I'm linking that here if anyone would want it.

https://github.com/Provenance-Emu/pcsx_rearmed/blob/d5e63a76999d4ef11ac437d4a02babb95df37dba/libpcsxcore/new_dynarec/linkage_arm64.S

**Comment by notaz** [comment]
I've updated the asm to work on both gcc and apple clang, so this should no longer be needed.
