### ISSUE TITLE
Setup custom scaler: Numerical values + usage hint are badly visible

### ISSUE THREAD

**Issue by porg** [notaz/pcsx_rearmed#283]
## Environment
- PCSX ReARMed r23
- Device: OpenPandora (800 x 640 pixels)
- OS: SuperZaxxon v1.76 update 3

## Reproduction
- Menu > Options > Display > Setup custom scaler.

## Usability Issues
1. Numerical values + usage hint are on the lowest layer (lowest z-index).
    - Hence invisible if the content is above it which happens when the content fills ca 80-100% of the viewport.
    - → Fix: Put it on the topmost layer.
2. Numerical values + usage hint are in white font.
    - Will be invisible if on lighter screen content.
    - → Fix: White font with black outline. Visible on any background.

**Comment by notaz** [comment]
Should be fixed by 96867f0e3c8f3a78ac3b9e34ba8bee757ecbc1d0.

**Comment by porg** [comment]
Please add a short human readable explanation by what measures the text is now guaranteed to be readable on different color background situations. Thanks!

**Comment by notaz** [comment]
Can you try this dev build and see for yourself?
https://notaz.gp2x.de/tmp/pcsx_rearmed_r23-360-g42dde520.pnd

**Comment by porg** [comment]
I'm ofc willing to test and give feedback.

In order to know what changes I shall test: Does this your build only include the changes of this particular issue here, or also all the other issues for which you offered fixes in these last days?

**Comment by notaz** [comment]
It's sort of a release candidate with everything, I don't really plan any more frontend changes for the next release.

**Comment by porg** [comment]
Ok, so I will test all the recent changes and report them here and in the other respective issues.
