### ISSUE TITLE
Setup custom scaler: Move operation not working with key combination "R + D-Pad" as hint says

### ISSUE THREAD

**Issue by porg** [notaz/pcsx_rearmed#284]
## Environment
- PCSX ReARMed r23
- Device: OpenPandora (800 x 640 pixels)
- OS: SuperZaxxon v1.76 update 3

## Reproduction
- Menu > Options > Display > Setup custom scaler.
- Under circumstances: #283 
- If you happen to see them, you still have a problem:
- Hint says: `d-pad resize. R+d-pad move.`
   - D-Pad: →  ✅ Indeed resizes.
   - Pressing right-shoulder button + D-Pad: →  ❌ Does not move but just resize.
     - My right-shoulder button is definitely not broken, works elsewhere in PCSX.
     - Also tried all other modifier keys, and the literal "R" key. → None of them caused a move operation.
- I do not know whether just the key binding is broken or whether the move operation itself is broken. But I guess it is rather the key binding, because the D-Pad part of it still triggers. So I guess just the modifier key part is not working.

**Comment by notaz** [comment]
Should be fixed by 96867f0e3c8f3a78ac3b9e34ba8bee757ecbc1d0.
