### ISSUE TITLE
Numerical values in config files are hexadecimal and without prefix

### ISSUE THREAD

**Issue by porg** [notaz/pcsx_rearmed#285]
## Problem
- In the rom `.cfg` config files numerical values are hexadecimal.
- Suboptimal user experience for inspecting/editing manually.
- Even worse: No hexadecimal prefix `0x` to instantly recognize them as hexadecimal values at first sight.
  - If you happen to read such a config file for the first time with hex values which solely consist of 0-9 without any A-F in them you may mistake them as decimal. Only later in the process — when cause/effect make no sense — you will realize this.

## Considerations
- The majority of pcsx users likely will never interact with these config files directly.
- But a few users may do: To learn how it works, and maybe achieve a tweaks which are not possible (yet) via GUI, or for batch-changes.
- For those users this UX kinda sucks. You need to convert back and forth to decimal.
- Although most values concerns numbers such as display metrics, CPU speed, etc, which we are used to in decimal.

## Path forward (if you are willing to change at all)
- Given that PCSX has been around for a while now and users amassed .cfg files over time, you cannot simply change the convention.

### Approach: Update dialog each user needs to answer once
  - When shipped it ships with a "dirty flag" as a file or value in the config, like `hex2dec-conversion=ran-never`
  - When pcsx launches and detects hex2dec-conversion == ran-never it shows a dialog like this:
```
    APP WAS UPDATED, USER ACTION IS NEEDED:
    In version r24 config files changes their value storage
    from hexadecimal to decimal notation for easier human readability.
    You seem to have not yet converted your configuration files.
    How would you like to proceed?
    
    [ Quit ]   [ I already converted by other means ]  [ CONVERT ALL NOW ]
    
    Info: https://www.notaz.gp2x.de/pcsx_rearmed/2023/03/r24-config-files-use-decimal-values-for-numbers
```
  - CONVERT ALL NOW (primary button) → hex2dec-conversion=ran-update-script
  - I already converted them by other means → hex2dec-conversion=skipped

## Opt-in: Users who want decimal notation run a one-time conversion

  $ pcsx --update-script hex2dec
  
- the main config gets a new entry: config-numerical-values=decimal
- A one time conversion script runs over all your .cfg files.

**Comment by porg** [comment]
This has a low priority.
But I wanted to note it down at least.
And cross-reference when/where-ever this is (a bit of) an issue.

**Comment by notaz** [comment]
The config files were not designed with user modification in mind. And like you said very few ever need it (out of very few that are still using pandora). Your ideas might be good but in the current situation it's not worth spending time on IMO.

Also the .pnd is arranged in such a way that you can have multiple versions of the emulator at once so that you can run an older version in case of regressions. Your one-time conversion would cause problems with that.

In the end the only change I've done is to add the `0x` prefix which the old versions can also understand.

**Comment by porg** [comment]
Thanks that as a minimal improvement the `0x` prefix is added and reverse compatible. That way those who tinker with it at least know immediately that this is a hexadecimal value.
