### ISSUE TITLE
Bedlam (SLES-00334) severe graphical issues.

### ISSUE THREAD

**Issue by Snowbro88** [notaz/pcsx_rearmed#288]
The 3rd person shooter arcade game called Bedlam (SLES-00334) exclusive in Europe for PS1 doesn't work properly on PCSX core, has serious graphical bugs, basically doesn't show anything correctly when trying to play, would it be possible to check it out?, thanks in advance.

**Comment by saulfabregwiivc** [comment]
This was fixed as of https://github.com/libretro/pcsx_rearmed/commit/b524c6713370c79574d69b0dba4601040c39a27c.
