### ISSUE TITLE
V-Rally 2 stuck on loading screen (with interpreter)

### ISSUE THREAD

**Issue by pcercuei** [notaz/pcsx_rearmed#291]
I thought this was a bug in Lightrec at first, but I can reproduce it with the interpreter with your latest master (8987ee20).

Just select "1 player start", "new driver", and "game mode" set to "time  trial". You will arrive at a never-ending loading screen.

**Comment by Snowbro88** [comment]
Use sbi file, is a protected game.

**Comment by pcercuei** [comment]
@Snowbro88 That was it, thanks!
