### ISSUE TITLE
X Games Pro Boarder music looping (ntsc)

### ISSUE THREAD

**Issue by stoniemahonie** [notaz/pcsx_rearmed#295]
When ingame, using whatever gamemode and the race starts, music starts playing. The music will constantly loop like every 5 seconds in a weird way, so it is not always the same part of the track and will progress a little but always loop like a few seconds again the same part. This is a bug, that also other emulators have/had years ago. No options that i know can fix it.

To repdroduce, only need to press x all the time until it enters the half pipe and the music starts playing after the 3,2,1 counddown.

Happens on retropie and windows using the latest available build. Works with duckstation/beetle emulators on windows.

**Comment by notaz** [comment]
Should be fixed now.
