### ISSUE TITLE
V-Rally 2 analog/rumble problems (pal)

### ISSUE THREAD

**Issue by stoniemahonie** [notaz/pcsx_rearmed#296]
In general, analog can work and rumble can also work. But i couldn't get both to work at the same time. To make rumble work, i have to first set the game to dualshock, save the option as a game-remap through retroarch quick menu and restart the game. So i close the game and start it again. When i go ingame, rumble works now (but only in a race/time trial, there is also the option to try a car in the main menu right from the start, but there is no rumble), but steering only works through the dpad. If i want analog steering to work, i have to set the game in the port 1 control options to something else and then switch back to dualshock. Then i can steer with the left analog stick just fine. But now rumble does not work anymore, no response at all.

In this game, you can configure the controllers only before the last point before entering a race, there you have the "driving options" where you can rebind etc. You can only rebind the analog sticks, in example for the right analog stick to use as gas/brake if you do the switch sth else and then back to dualshock as previously mentioned. Only then it registers the analog sticks in the rebind options and ingame at all.

In duckstation both can work at the same time (in windows). Only when changing ingame to sth else and back, rumble is also gone there too.

Im using a dualshock 4 controller on a raspberry pie and and on windows, so i don't think its a problem exclusive to the controller. Other games work just fine with rumble. Atleast the ones i played and i'm aware that rumble in general is not always working perfectly.

**Comment by notaz** [comment]
This seems to work now after recent input rewrites. Loading the game with dualshock enabled gives both analog steering and rumble (according to custom trace logs, I don't have any actual rumble device).
