### ISSUE TITLE
Some Minor Graphic issues on the Neon Gpu

### ISSUE THREAD

**Issue by mckimiaklopa** [notaz/pcsx_rearmed#30]
Some issues with the default settings using the neon gpu

1.)Threads of fate has some weird polygon syndrome(play a new game using the girl)

2.)The battle transition in Final fantasy VIII is not rendered corretcly while the battle swirl in Final Fantasy VII is very inaccurate

3.)ON a battle in Final fantasy VII,every time
a.a characyer or enemy attacks,
b.The number indicating the damage or incured or the hp recovered is shown,

the dithering in the background disappears.This does not certainly happen on a psx console

4.)This one is not really an issue but is a request

Dithering is missing on scenes with pre-rendered backgrounds(I noticed it in Final fantasy IX on the prima vista crash site but is still found on other games) and on FMVs.On a real psx,there is dithering on the said scenes

**Comment by notaz** [comment]
I think these issues should be fixed by now. Feel free to reopen if not.
