### ISSUE TITLE
Issues with Championship Motocross 2001 Featuring Ricky Carmichael randomly crashing

### ISSUE THREAD

**Issue by aorin1** [notaz/pcsx_rearmed#300]
After testing many games without issues, Championship Motocross 2001 Featuring Ricky Carmichael crashes randomly, sometimes in the Options but more often during gameplay. There are no graphics issues and the gameplay performs really well, no options changed inside the emulator.
The game doesn't have this issue with other emulators such as Mednafen or Duckstation, for instance.

Platform: Android

**Comment by notaz** [comment]
Did you use HLE bios? With the real bios I could not reproduce this, but HLE indeed has such an issue, which I just patched.

**Comment by aorin1** [comment]
Yes, HLE BIOS. Thanks for taking a look and fixing the issue!
