### ISSUE TITLE
Soukyuu Gurentai: Oubushutsugeki only starts in Arcade Mode

### ISSUE THREAD

**Issue by aorin1** [notaz/pcsx_rearmed#302]
As stated on the title, the game defaults to Special Mode スペシャル・モード and you have to press Select on the "Press Start" screen to change options, but after selecting your character, the game goes into a black screen with the soundtrack playing.
It only works when selecting Arcade Mode アーケード・モード, then after selecting your character, the game starts normally.

Tested on Windows and Android.

Edit: Special Mode ads an extra ship, extra level, etc.

**Comment by notaz** [comment]
So you mean if you just hit start at the title screen and select a character it hangs? If so, I'm unable to reproduce. Which version are you using?

I've also tried アーケードモード and ハイスコアバトルモード and those also work for me.

**Comment by aorin1** [comment]
You're correct, the game does work fine, the issue is that in Special Mode, the version I've tried has all videos and voices removed, but the full Redump version starts Special Mode without issues.
The only thing that made me consider it an issue is that the ripped version works fine in Special Mode using Swanstation (Libretro) but on both Android and Windows versions of PCSX-ReARMed (Libretro) the game won't start.

So it's not exactly an issue with the core/emulator, but a behavior when using this specific ripped game, it just won't start Special Mode.

**Comment by notaz** [comment]
Unless it's known that the ripped version works on the real hardware I'd prefer not to put any effort debugging this.

**Comment by aorin1** [comment]
> Unless it's known that the ripped version works on the r

> Unless it's known that the ripped version works on the real hardware I'd prefer not to put any effort debugging this.

It does work fine in Duckstation, the issue mentioned is exclusive to PCSX-R. I forgot mentioning that when opening this.

The ripped game doesn't have any videos, the voices in Special Mode are absent too.
Would it help if I upload this dump for easier access/testing?

**Comment by aorin1** [comment]
Here's a link for the sample for testing, I've also retried the game on Swanstation and it indeed works fine whereas in PCSX-R, just starting the game, which by default is Special Mode won't work. I'll remove this sample once confirmed.

Thanks again!

https://mega.nz/folder/QJNw2K7S#MbwFG7RwylpcYg6hzcNpUA

**Comment by notaz** [comment]
I'm quite sure this wouldn't work on the real hardware, as the game wants to play a track that's missing altogether in the ripped version. It gets the tracklist, but that's just 1 track in the ripped chd, still it reads some entry of the track it wants to play and that ends up behind the end of the list, so it just picks some garbage left by the bios there and sends it to CDC, retrying infinitely on failure. I don't think that can work.

Still I know people will bother me since it works in other emulators so I've added a hack. But if there are any signs that it causes trouble it will be swiftly reverted.

**Comment by aorin1** [comment]
> I'm quite sure this wouldn't work on the real hardware, as the game wants to play a track that's missing altogether in the ripped version. It gets the tracklist, but that's just 1 track in the ripped chd, still it reads some entry of the track it wants to play and that ends up behind the end of the list, so it just picks some garbage left by the bios there and sends it to CDC, retrying infinitely on failure. I don't think that can work.
> 
> Still I know people will bother me since it works in other emulators so I've added a hack. But if there are any signs that it causes trouble it will be swiftly reverted.

Unfortunately I don't have a real PS1 or PS2/PS3 to test this rip, I only requested to take a look into it because Duckstation had no issues with it and since it's deemed as one of the most accurate PS emulators around, I thought it would be interesting to take a look. I didn't know it required a hack to make it work in PCSX-R, if you belive it can cause issues in other games, I'll understand if you want to revert the change.
Like always, I can only thank you for the quick support and fixes you've been adding.
