### ISSUE TITLE
Can't access "Configuration" menu in Option - Tuning Car Battle Spec R

### ISSUE THREAD

**Issue by aorin1** [notaz/pcsx_rearmed#303]
As stated in the title, accessing Configuration leads to a black screen with the music playing in the background.
The game is a Japanese exclusive and it's in CHD.
While it stays in a black screen, you can press the directional and buttons to go back to the Main Menu, but changing configuration is virtually impossible.

It was tested in both Android and Windows latest versions of the PCSX-R core, and Swanstation/Duckstation accesses the menu without issues.

**Comment by notaz** [comment]
This issue is considered fixed in the latest version. Feel free to reopen if that's not the case.
