### ISSUE TITLE
Widescreen GameShark codes crashing Retroarch on Medal of Honor games

### ISSUE THREAD

**Issue by aorin1** [notaz/pcsx_rearmed#306]
I've been using many widescreen codes in the last years and they all basically work across all PS1 cores and according to the PCSX2 forums, users state these codes work fine in either original hardware or using a PS2 console with the OPL Loader or something similar to that.
In PCSX-R, I've had few issues but most of the codes work fine, recently the codes for both Medal of Honor titles were updated as the originals needed some more work, and while these work fine in either Beetle PSX or Swanstation (Screenshot is from Beetle), PCSX-R crashes right before going into the game, it almost loads the stage entirely but crashes, it happens on both games in a similar fashion, and both codes and games load fine in the other cores as well.

This is the link of the thread to the codes:
https://forums.pcsx2.net/Thread-PSOne-Widescreen-Patches?pid=636336#pid636336

I've converted the codes so Retroarch will load them, and to confirm they work, the above is true for both Bettle PSX and Swanstation, meaning the codes themselves are fine, or they seem to be, otherwise the other cores would probably crash the game as well.

Medal of Honor (USA) (Widescreen)
https://pastebin.com/CNciaGUa

Medal of Honor: Underground (USA) (Widescreen)
https://pastebin.com/g18ecqjX

The screenshots show the code for Underground working fine in Beetle PSX (I didn't take a screenshot from Swanstation), or as fine it can, making the 3D assets look OK when in a 16:9 display, and while the 2D assets are stretched, it's a small price to pay. The other screenshot shows the stretched image for comparison.

<img src="https://i.ibb.co/ckNZH9q/Medal-of-Honor-Underground-USA-230909-221405.png" alt="Medal-of-Honor-Underground-USA-230909-221405" border="0">
<img src="https://i.ibb.co/KjNf15m/Medal-of-Honor-Underground-USA-230909-223107.png" alt="Medal-of-Honor-Underground-USA-230909-223107" border="0">

**Comment by notaz** [comment]
There was a problem caused by the fact that the cheat is very long, it should work now.
