### ISSUE TITLE
BallBlazer Champions crashing on Android

### ISSUE THREAD

**Issue by aorin1** [notaz/pcsx_rearmed#307]
I've tried this game using PCSX-R core on Windows and Duckstation/Swanstation, the game works fine but crashes on Android in the menus, I couldn't reach gameplay and tried both US and PAL versions to make sure it wasn't a bad dump.
I'm still not sure whether this is an issue with the core itself as even Beetle PSX seemed to crash as well (Android), still, since it works on Windows and I tested about 200 titles on Android without issues (PCSX-R), I believe it's worth checking it out to see if this is reproducible.

**Comment by notaz** [comment]
This issue is considered fixed in the latest version. Feel free to reopen if that's not the case.
