### ISSUE TITLE
Blood Omen Legacy of Kain graphic glitch

### ISSUE THREAD

**Issue by Reideldm** [notaz/pcsx_rearmed#308]
in blood omen when you drink from a source of blood to acquire an ability the blood is shown without animation and when it has to turn black it disappears, breaking the graphics 

![20230914_165459](https://github.com/notaz/pcsx_rearmed/assets/137739449/a5c851d0-4134-4576-8c22-fe694f7e437c)

**Comment by notaz** [comment]
Can you post a savestate or a memcard save? It should be before the breakage because it can get saved in the savestate.

**Comment by Reideldm** [comment]
here it is my friend I hope it helps
[Blood Omen Legacy Of Kain.zip](https://github.com/notaz/pcsx_rearmed/files/12796809/Blood.Omen.Legacy.Of.Kain.zip)

**Comment by Reideldm** [comment]
You just have to press circle to see the graphic error in the bloody font

**Comment by Reideldm** [comment]
Friend I finally managed to update the core in version r23I e34ef5a I checked that this issue is fixed

**Comment by Reideldm** [comment]
![20231003_183907](https://github.com/notaz/pcsx_rearmed/assets/137739449/0de4b206-728e-414b-9802-12e27af6a51a)
here it is already solved
