### ISSUE TITLE
Resident evil 1 2 3 problem with dualshock vibration

### ISSUE THREAD

**Issue by Reideldm** [notaz/pcsx_rearmed#309]
resident evil 3 with the controller configured as dualshock  it does not vibrate however when you get to the violent content warning screen you open the retroarch quick menu and reset and the game vibrates correctly, the same happens with resident evil 1 and 2 dualshock edition

**Comment by notaz** [comment]
This issue is considered fixed in the latest version. Feel free to reopen if that's not the case.

**Comment by Reideldm** [comment]
Thank you for the extraordinary work you do for passionate PS1 fans.
