### ISSUE TITLE
Intellivision Classics and Blaster Master:Blasting Again - Black Screen after Intros

### ISSUE THREAD

**Issue by SavedByZero** [notaz/pcsx_rearmed#310]
Both games show a black screen and halt after the splash intro.  I have a RPi 3, the correct bios, and this verbose output: 
`Parameters: 
Executing: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-pcsx-rearmed/pcsx_rearmed_libretro.so --config /opt/retropie/configs/psx/retroarch.cfg "/home/pi/RetroPie/roms/psx/Intellivision Classic Games (USA).cue" --verbose --appendconfig /dev/shm/retroarch.cfg
[WARN] [GameMode]: GameMode cannot be enabled on this system ("dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory.") https://github.com/FeralInteractive/gamemode needs to be installed.
[WARN] [Config]: GameMode unsupported - disabling..
[INFO] RetroArch 1.15.0 (Git 1e5b1ba)
[INFO] === Build =======================================
[INFO] CPU Model Name: ARMv7 Processor rev 4 (v7l)

[INFO] Capabilities: NEON VFPv3 VFPv4
[INFO] Built: Apr  9 2023
[INFO] Version: 1.15.0
[INFO] Git: 1e5b1ba
[INFO] =================================================
[INFO] [Input]: Found input driver: "udev".
[INFO] [Core]: Loading dynamic libretro core from: "/opt/retropie/libretrocores/lr-pcsx-rearmed/pcsx_rearmed_libretro.so"
[INFO] [Config]: Loading config: "/opt/retropie/configs/psx/retroarch.cfg".
[INFO] [Config]: Appending config: "/dev/shm/retroarch.cfg".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL.
[INFO] [Overrides]: Redirecting save file to "/home/pi/RetroPie/roms/psx/Intellivision Classic Games (USA).srm".
[INFO] [Overrides]: Redirecting save state to "/home/pi/RetroPie/roms/psx/Intellivision Classic Games (USA).state".
[INFO] [Environ]: GET_MESSAGE_INTERFACE_VERSION.
[libretro INFO] Memcard 2: disabled
[libretro INFO] Starting PCSX-ReARMed c1114bf
[libretro INFO] Running PCSX Version 1.9 (Sep 19 2023).
[libretro INFO] psxMap: warning: wanted to map @80000000, got 0x6e1b8000
[libretro INFO] Init new dynarec, ndrc size 1001000
[libretro INFO] (0x6e438a0c) testing if we can run recompiled code @0x6e8da000...
[libretro INFO] test passed.
[libretro INFO] warning: RAM is not directly mapped, performance will suffer
[libretro INFO] Mapped (RAM/scrp/ROM/LUTs/TC):
[libretro INFO] 0x77000000/0x1f800000/0x1fc00000/(nil)/0x6e8da000
[INFO] [Environ]: SYSTEM_DIRECTORY: "/home/pi/RetroPie/BIOS".
[libretro INFO] found BIOS file: SCPH1001.BIN
[INFO] [Environ]: GET_CAN_DUPE: true
[INFO] [Environ]: GET_DISK_CONTROL_INTERFACE_VERSION.
[INFO] [Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
[INFO] [Environ]: GET_RUMBLE_INTERFACE.
[INFO] [Environ]: PERFORMANCE_LEVEL: 6.
[INFO] [Content]: Content loading skipped. Implementation will load it on its own.
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[libretro INFO] RGB565 supported, using it
[ERROR] [Environ]: GET_VARIABLE: pcsx_rearmed_async_cd - Invalid value.
[libretro INFO] plugin: plugins/builtin_gpu
[libretro INFO] plugin: plugins/builtin_spu
[libretro INFO] plugin: plugins/builtin_pad
[libretro INFO] plugin: plugins/builtin_pad
[libretro INFO] Plugins loaded.
[libretro INFO] Loaded CD Image: /home/pi/RetroPie/roms/psx/Intellivision Classic Games (USA).cue[+cue].
[libretro INFO] Track 01 (DATA) - Start 00:02:00, Length 25:56:01
[libretro INFO] Track 02 (AUDIO) - Start 26:00:01, Length 00:28:13
[libretro INFO] Track 03 (AUDIO) - Start 26:30:14, Length 03:03:00
[libretro INFO] CD-ROM Label: SLUS00906                       
[libretro INFO] CD-ROM ID: SLUS00906
[libretro INFO] CD-ROM EXE Name: SLUS_009.06;1
[INFO] [Environ]: SET_AUDIO_BUFFER_STATUS_CALLBACK.
[INFO] [Replay]: Found last replay slot: #0
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 44100.00 Hz.
[INFO] [Video]: Set video size to: 960x720.
[INFO] [Video]: Starting threaded video driver..
[INFO] [EGL] Falling back to eglGetDisplay
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Current context: 0x1.
[INFO] [GL]: Found GL context: "egl_videocore".
[INFO] [GL]: Detecting screen resolution: 640x480.
[INFO] [GL]: Vendor: Broadcom, Renderer: VideoCore IV HW.
[INFO] [GL]: Version: OpenGL ES 2.0.
[INFO] Querying EGL extension: KHR_image => exists
[INFO] [GL]: Using resolution 640x480.
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[WARN] [udev]: Full-screen pointer won't be available.
[INFO] [udev]: Pad #0 (/dev/input/event6) supports 0 force feedback effects.
[INFO] [Autoconf]: DragonRise Inc.   Generic   USB  Joystick   configured in port 1.
[INFO] [udev]: Pad #1 (/dev/input/event7) supports 0 force feedback effects.
[INFO] [Autoconf]: DragonRise Inc.   Generic   USB  Joystick   configured in port 2.
[INFO] [udev]: Pad #2 (/dev/input/event3) supports 0 force feedback effects.
[INFO] [Autoconf]: USB,2-axis 8-button gamepad   configured in port 3.
[INFO] [udev]: Pad #3 (/dev/input/event5) supports force feedback.
[INFO] [udev]: Pad #3 (/dev/input/event5) supports 16 force feedback effects.
[INFO] [Autoconf]: Sony PLAYSTATION(R)3 Controller configured in port 4.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Video]: Found display server: "null".
[INFO] ALSA: Using floating point format.
[INFO] ALSA: Period size: 480 frames
[INFO] ALSA: Buffer size: 1536 frames
[INFO] [Display]: Found display driver: "gl".
[libretro INFO] port: 1  device: standard
[libretro INFO] port: 2  device: standard
[libretro INFO] port: 3  device: standard
[libretro INFO] port: 4  device: standard
[libretro INFO] port: 5  device: standard
[libretro INFO] port: 6  device: none
[libretro INFO] port: 7  device: none
[libretro INFO] port: 8  device: none
[INFO] [Playlist]: Loading history file: "/opt/retropie/configs/psx/content_history.lpl".
[INFO] [Playlist]: Loading history file: "/opt/retropie/configs/psx/content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "/opt/retropie/configs/psx/content_video_history.lpl".
[INFO] [Playlist]: Loading history file: "/opt/retropie/configs/psx/content_image_history.lpl".
[INFO] [Playlist]: Loading favorites file: "/opt/retropie/configs/psx/content_favorites.lpl".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_MINIMUM_AUDIO_LATENCY.
[INFO] [Environ]: SET_GEOMETRY: 256x240, Aspect: 1.333.
[INFO] [Environ]: SET_GEOMETRY: 640x480, Aspect: 1.333.
[INFO] [Environ]: SET_GEOMETRY: 256x240, Aspect: 1.333.
[INFO] [Environ]: SET_GEOMETRY: 320x240, Aspect: 1.333.
[INFO] [Environ]: SET_GEOMETRY: 256x240, Aspect: 1.333.
[INFO] [Environ]: SET_GEOMETRY: 320x240, Aspect: 1.333.
[INFO] [Environ]: SET_GEOMETRY: 640x480, Aspect: 1.333.
[libretro INFO] Compile at bogus memory address: 248438b4`

**Comment by SavedByZero** [comment]
This is still occuring with this morning's update, same verbose output.  I tried disabling the boot logo, but no difference.  I also have the 3 extra bios files for localization being recognized by the core.

**Comment by SavedByZero** [comment]
Here's a second verbose log from the other game (the above was for Intellivision Classics, this one is for Blaster Master: Blasting again).  I'm beginning to suspect this is the culprit, but I have no idea of how to be sure: `[ERROR] [Environ]: GET_VARIABLE: pcsx_rearmed_async_cd - Invalid value.`

  `Parameters: 
Executing: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-pcsx-rearmed/pcsx_rearmed_libretro.so --config /opt/retropie/configs/psx/retroarch.cfg "/home/pi/RetroPie/roms/psx/Blaster Master - Blasting Again.cue" --verbose --appendconfig /dev/shm/retroarch.cfg
[WARN] [GameMode]: GameMode cannot be enabled on this system ("dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory.") https://github.com/FeralInteractive/gamemode needs to be installed.
[WARN] [Config]: GameMode unsupported - disabling..
[INFO] RetroArch 1.15.0 (Git 1e5b1ba)
[INFO] === Build =======================================
[INFO] CPU Model Name: ARMv7 Processor rev 4 (v7l)

[INFO] Capabilities: NEON VFPv3 VFPv4
[INFO] Built: Apr  9 2023
[INFO] Version: 1.15.0
[INFO] Git: 1e5b1ba
[INFO] =================================================
[INFO] [Input]: Found input driver: "udev".
[INFO] [Core]: Loading dynamic libretro core from: "/opt/retropie/libretrocores/lr-pcsx-rearmed/pcsx_rearmed_libretro.so"
[INFO] [Config]: Loading config: "/opt/retropie/configs/psx/retroarch.cfg".
[INFO] [Config]: Appending config: "/dev/shm/retroarch.cfg".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL.
[INFO] [Overrides]: Redirecting save file to "/home/pi/RetroPie/roms/psx/Blaster Master - Blasting Again.srm".
[INFO] [Overrides]: Redirecting save state to "/home/pi/RetroPie/roms/psx/Blaster Master - Blasting Again.state".
[INFO] [Environ]: GET_MESSAGE_INTERFACE_VERSION.
[libretro INFO] Memcard 2: enabled
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[libretro INFO] Use memcard 2: /home/pi/RetroPie/roms/psx//pcsx-card2.mcd
[libretro INFO] Starting PCSX-ReARMed 3b55b1a
[libretro INFO] Running PCSX Version 1.9 (Sep 21 2023).
[libretro INFO] psxMap: warning: wanted to map @80000000, got 0x6e14d000
[libretro INFO] Init new dynarec, ndrc size 1001000
[libretro INFO] (0x6e3cdb48) testing if we can run recompiled code @0x6e86f000...
[libretro INFO] test passed.
[libretro INFO] warning: RAM is not directly mapped, performance will suffer
[libretro INFO] Mapped (RAM/scrp/ROM/LUTs/TC):
[libretro INFO] 0x77000000/0x1f800000/0x1fc00000/(nil)/0x6e86f000
[libretro INFO] Loading memory card /home/pi/RetroPie/roms/psx//pcsx-card2.mcd
[INFO] [Environ]: SYSTEM_DIRECTORY: "/home/pi/RetroPie/BIOS".
[libretro INFO] found BIOS file: scph5501.bin
[INFO] [Environ]: GET_CAN_DUPE: true
[INFO] [Environ]: GET_DISK_CONTROL_INTERFACE_VERSION.
[INFO] [Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
[INFO] [Environ]: GET_RUMBLE_INTERFACE.
[INFO] [Environ]: PERFORMANCE_LEVEL: 6.
[INFO] [Content]: Content loading skipped. Implementation will load it on its own.
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[libretro INFO] RGB565 supported, using it
[ERROR] [Environ]: GET_VARIABLE: pcsx_rearmed_async_cd - Invalid value.
[libretro INFO] plugin: plugins/builtin_gpu
[libretro INFO] plugin: plugins/builtin_spu
[libretro INFO] plugin: plugins/builtin_pad
[libretro INFO] plugin: plugins/builtin_pad
[libretro INFO] Plugins loaded.
[libretro INFO] Loaded CD Image: /home/pi/RetroPie/roms/psx/Blaster Master - Blasting Again.cue[+cue].
[libretro INFO] Track 01 (DATA) - Start 00:02:00, Length 50:29:55
[libretro INFO] Track 02 (AUDIO) - Start 50:33:55, Length 03:34:00
[libretro INFO] CD-ROM Label: SLUS01031                       
[libretro INFO] CD-ROM ID: SLUS01031
[libretro INFO] CD-ROM EXE Name: SLUS_010.31;1
[INFO] [Environ]: SET_AUDIO_BUFFER_STATUS_CALLBACK.
[INFO] [Replay]: Found last replay slot: #0
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 44100.00 Hz.
[INFO] [Video]: Set video size to: 960x720.
[INFO] [Video]: Starting threaded video driver..
[INFO] [EGL] Falling back to eglGetDisplay
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Current context: 0x1.
[INFO] [GL]: Found GL context: "egl_videocore".
[INFO] [GL]: Detecting screen resolution: 1366x768.
[INFO] [GL]: Vendor: Broadcom, Renderer: VideoCore IV HW.
[INFO] [GL]: Version: OpenGL ES 2.0.
[INFO] Querying EGL extension: KHR_image => exists
[INFO] [GL]: Using resolution 1366x768.
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: Compiled
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[WARN] [udev]: Full-screen pointer won't be available.
[INFO] [udev]: Pad #0 (/dev/input/event4) supports 0 force feedback effects.
[INFO] [Autoconf]: DragonRise Inc.   Generic   USB  Joystick   configured in port 1.
[INFO] [udev]: Pad #1 (/dev/input/event5) supports 0 force feedback effects.
[INFO] [Autoconf]: DragonRise Inc.   Generic   USB  Joystick   configured in port 2.
[INFO] [udev]: Pad #2 (/dev/input/event3) supports 0 force feedback effects.
[INFO] [Autoconf]: USB,2-axis 8-button gamepad   configured in port 3.
[INFO] [udev]: Pad #3 (/dev/input/event7) supports force feedback.
[INFO] [udev]: Pad #3 (/dev/input/event7) supports 16 force feedback effects.
[INFO] [Autoconf]: Sony PLAYSTATION(R)3 Controller configured in port 4.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Video]: Found display server: "null".
[INFO] ALSA: Using floating point format.
[INFO] ALSA: Period size: 480 frames
[INFO] ALSA: Buffer size: 1536 frames
[INFO] [Display]: Found display driver: "gl".
[libretro INFO] port: 1  device: standard
[libretro INFO] port: 2  device: standard
[libretro INFO] port: 3  device: standard
[libretro INFO] port: 4  device: standard
[libretro INFO] port: 5  device: standard
[libretro INFO] port: 6  device: none
[libretro INFO] port: 7  device: none
[libretro INFO] port: 8  device: none
[INFO] [Playlist]: Loading history file: "/opt/retropie/configs/psx/content_history.lpl".
[INFO] [Playlist]: Loading history file: "/opt/retropie/configs/psx/content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "/opt/retropie/configs/psx/content_video_history.lpl".
[INFO] [Playlist]: Loading history file: "/opt/retropie/configs/psx/content_image_history.lpl".
[INFO] [Playlist]: Loading favorites file: "/opt/retropie/configs/psx/content_favorites.lpl".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_MINIMUM_AUDIO_LATENCY.
[INFO] [Environ]: Setting audio latency to 128 ms.
[INFO] [Audio]: Set audio input rate to: 44100.00 Hz.
[INFO] ALSA: Using floating point format.
[INFO] ALSA: Period size: 768 frames
[INFO] ALSA: Buffer size: 3072 frames
[INFO] [Display]: Found display driver: "gl".
[WARN] [udev]: Mouse grab/ungrab feature unavailable.
[INFO] [Input]: Game Focus => OFF
[INFO] [Environ]: SET_GEOMETRY: 640x480, Aspect: 1.333.
[INFO] [Environ]: SET_GEOMETRY: 256x240, Aspect: 1.333.`

**Comment by notaz** [comment]
Both work fine for me on my rpi4, so IDK.

> This is still occuring with this morning's update

Well nobody said the commits were related to this issue.

>  I'm beginning to suspect this is the culprit, but I have no idea of how to be sure: [ERROR] [Environ]: GET_VARIABLE: pcsx_rearmed_async_cd - Invalid value.

This one is completely harmless.

Perhaps something in your config, try deleting `~/.config/retroarch/config/PCSX-ReARMed/PCSX-ReARMed.opt`. Or maybe your disk images are bad, confirm your checksums with known good ones like ones at http://redump.org/disc/6728/ . Also try disabling the dynarec to see if you can get past the hang.

**Comment by SavedByZero** [comment]
> Both work fine for me on my rpi4, so IDK.
> 
I have a pi3b.  Should this not work on there anymore?

**Comment by notaz** [comment]
From the emulator's perspective rpi3 and rpi4 are identical, only performance differs, so it should work. The games work even without BIOS (with HLE) for me. If disabling the dynarec doesn't help it must be something else with your setup, maybe your SD card got corrupted or something.

**Comment by SavedByZero** [comment]
Nope — brand new SD card. Who knows at this point…Sent from my iPhoneOn Sep 21, 2023, at 5:47 PM, notaz ***@***.***> wrote:﻿
From the emulator's perspective rpi3 and rpi4 are identical, only performance differs, so it should work. The games work even without BIOS (with HLE) for me. If disabling the dynarec doesn't help it must be something else with your setup, maybe your SD card got corrupted or something.

**Comment by notaz** [comment]
I'll have to close this since there is nothing I can do unless you can find something that causes this issue to appear.
