### ISSUE TITLE
Colin McRae 2.0 Not Booting

### ISSUE THREAD

**Issue by aorin1** [notaz/pcsx_rearmed#311]
Windows:

The game hangs on the disclaimer screen, which is the first screen shown after the BIOS. Though it runs fine in Beetle PSX and Duckstation.

Tried both the US and JP versions and PCSX-R hangs on both.

Android:
Strangely enough, the game boots fine and I've checked the Core Options on Windows and they were using default values, so it doesn't seem something I messed up there.

Still on Android, not sure if this occurs on Windows, I could only properly use analog controls when I set the game to Left Handed, it wasn't behaving as expected, so I needed to create a specific remap under Control options to get it working as it should. In short, this is to circumvent the issue, but it still needs confirmation and more testing, can you reproduce this?

**Comment by notaz** [comment]
Boots for me on 64bit Linux. 32bit or 64bit Windows? Can you post the logs?

Didn't quite understand what exactly was wrong with analogs. Both sticks are processed exactly the same way so it'd be strange if only one works.

**Comment by aorin1** [comment]
Strange, yes, it didn't boot only on Windows x64 but does on Android, same iso, and it boots fine in other cores. The analog behavior on the android core like I mentioned is a bit weird, but it's ok if I use a custom remap and setting the in-game options to left-handed.

**Comment by notaz** [comment]
I've set up a Windows VM and it still works there. Maybe it's something in your settings, you can try deleting `config/PCSX-ReARMed/` and maybe `retroarch.cfg` to get into the default state.

**Comment by aorin1** [comment]
Yes, when it happens I often use a clean Retroarch download in a fresh folder to make sure. Still, after the last commits the game boots fine on Windows, not sure why it wasn't before.
I'm still not sure how the game analog controls actually work, it's a bit weird, though.
I'm closing it and thanks for checking it again!
