### ISSUE TITLE
Final Fantasy VIII dualshock configuration not working

### ISSUE THREAD

**Issue by Reideldm** [notaz/pcsx_rearmed#314]
Final Fantasy VIII dualshock configuration not working
everything configured as a dualshock control but it does not vibrate, many other games tested with the same configuration vibrate perfectly

I leave savestate on the first cd in battle mode it should vibrate when using the attack command or using the gf command during the summon synematics

[Final Fantasy VIII (USA) (Disc 1).zip](https://github.com/notaz/pcsx_rearmed/files/12807751/Final.Fantasy.VIII.USA.Disc.1.zip)

**Comment by notaz** [comment]
I've fixed the vibration during summons. However during normal attacks the game doesn't seem to be sending any vibration commands. Is it really supposed to be there?

**Comment by Reideldm** [comment]
I'm sorry for not being more specific, during the normal attack it vibrates when you press the R1 button at the same moment that the character hits the monster, I remember that it is with the squal character that it is what would be called firing the gun saber, I think it already works during the invocations it is completely fixed, you are incredible friend

**Comment by Reideldm** [comment]
You are doing an impressive job. I congratulate you. I would like to be able to help you more. I will continue reporting.

**Comment by Reideldm** [comment]
I am updating the core from this repo https://github.com/christianhaitian/retroarch-cores/blob/master/arm7hf/pcsx_rearmed_libretro.so.zip because the platform I use is the ps1 classic  Do you know of any other site where I can update more frequently?

**Comment by notaz** [comment]
From what I understand this is fixed.

And if anyone ends up here looking for newer ARM builds, they can be found here:
https://github.com/notaz/pcsx_rearmed/releases/tag/libretro-devbuild

**Comment by Reideldm** [comment]
Thank you very much, I will keep myself updated to avoid confusion. I really appreciate your time.
