### ISSUE TITLE
Monkey Hero missing sound effects.

### ISSUE THREAD

**Issue by Snowbro88** [notaz/pcsx_rearmed#315]
Hello, I want to report that the game Monkey Hero, which is currently compatible with PCSX rearmed (finally does not present graphic problems), however I can notice another problem, it does not have sound effects, only the music in the game.

It would be great if it could be checked, maybe it's an audio plugin issue?

Tested on latest stable version of PS Vita retroarch.

Thank you.

**Comment by notaz** [comment]
This should work now in the latest version.
