### ISSUE TITLE
Audio reverb effects inverted in R4: Ridge Racer Type 4

### ISSUE THREAD

**Issue by vaguerant** [notaz/pcsx_rearmed#316]
# Issue

Reverb behavior seems to be inverted or otherwise incorrect, with louder, more echo-y engine sounds when out in the open suddenly cutting to normal engine sounds when entering any remotely enclosed area of the track. See attached video:

https://github.com/notaz/pcsx_rearmed/assets/5259025/9527cd02-6770-48ac-858c-a24649d6ba3a

In addition to being inverted, the transitions seem abrupt; I don't think this is accurate to the game either (as compared with other emulators e.g. DuckStation), but could just be a side effect of whatever is going wrong with reverb in the first place.

# Intended behavior

The way reverb is supposed to work in R4 is that vehicles have normal engine sounds when out in the open air, then a reverb effect is added when moving into more enclosed sections of the track, i.e. the sound of the player's vehicle echoing back at them from the tunnel walls. 

# Workaround

Disabling reverb from the core options (Audio > Reverb Effects OFF) "prevents" this issue from occurring, which is probably preferable in the short term but obviously not an actual solution, since it's just wrong in a different way.

# Additional info

* for easier sound effect testing, R4: Ridge Racer Type 4 includes a setting in its in-game Options menu (Options > Adjust audio > B.G.M.) where you can mute the background music
* for reproduction, the video demonstration was recorded with a blank save in Time Attack mode on the first track (Helter Skelter) with the default car (Preset D1)

# Versions tested

* 85d4a83 on Windows
about a week old but appears to be the current nightly on libretro's end

* a7bc6451 on Wii U
about a month old, so it's not an overwhelmingly recent issue

**Comment by notaz** [comment]
Should be fixed now.
