### ISSUE TITLE
Segfault in non neon libretro core

### ISSUE THREAD

**Issue by sergiobenrocha2** [notaz/pcsx_rearmed#32]
I'm getting segfault with the non neon libretro core, ubuntu 14.04 for arm (odroid u3)

RetroArch [ERROR] :: dylib_load :: dylib_load() failed: "/usr/lib/libretro/pcsx_rearmed_libretro.so: undefined symbol: gteMVMVA_part_neon".
Segmentation fault

Builded with make -f Makefile.libretro platform="armv hardfloat"

**Comment by notaz** [comment]
Assuming toolchain issue, closing.
