### ISSUE TITLE
You can see games texture joins/seams when using the Unai Plugin.

### ISSUE THREAD

**Issue by Ploggy** [notaz/pcsx_rearmed#320]
On the Unai Plugin you can see the texture seams or joins? it only happens whrn playing games with the Unai Plugin.
This is a Pic of the issue, you can see it alot when playing Crash Bandicoot 3 usually in the Sky or the water in Jetski Stages:
![Crash Bandicoot 3 - Warped (USA)-231015-012211](https://github.com/notaz/pcsx_rearmed/assets/1160255/c5670f99-f5fa-44a7-bed7-040908165d10)
This is how its supposed to look:
![Crash Bandicoot 3 - Warped (USA)-231015-012325](https://github.com/notaz/pcsx_rearmed/assets/1160255/a8ddda3b-4a76-4288-ac5a-e802d99f8e73)

**Comment by notaz** [comment]
I think it was always like that with unai, it might be by design using lower precision to get more speed. I don't plan working on this plugin except maybe fixing obvious regressions like the one with dithering before.

IIRC the plugin came from the `psx4all` project (or was it `pcsx4all`?) so you may want to check if they have any fixes or maybe try contacting the authors for a comment. Also @gameblabla and @justinweiss seem to have worked in this area an could have some comments.

**Comment by Ploggy** [comment]
Thanks for the explanation, zcrc said pretty much the same thing :P I'll wait to see if gameblala or justinweiss has anything to add if not I will just put it down to.. it has to be like that for speed reasons and close the issue :)

**Comment by justinweiss** [comment]
From the readme for the updated unai, it sounded like it’s mostly a precision issue, along with some other changes: https://github.com/libretro/pcsx_rearmed/blob/master/plugins/gpu_unai/README_senquack.txt

**Comment by Ploggy** [comment]
I think I read about that earlier, The dev Senquack started working on upgrading Unai for a while a couple years back but hasn't worked on it since, then Gameblabla made a pr with it for this repo? but it was found to be slower than the regular Unai plugin so it was made into its own plugin which was merged here but I don't think that has made its way to the Libretro repo?

The WiiU needs all the fps it can get so I dont think Gameblabla's plugin merger would help WiiU (unless we can somehow just rip out the fix for the texture join issue if there is one) :P

**Comment by Ploggy** [comment]
Thankyou pcercuei! Water and Sky in Crash Bandicoot 3 looks as good as on Pepos now! speed is essentially the same also :)

Big Thanks.

Closing.
