### ISSUE TITLE
dual shock stick and dpad duplicate functionality 

### ISSUE THREAD

**Issue by Reideldm** [notaz/pcsx_rearmed#323]
Several games that use the analog stick in DualShock mode have a problem, the dpad that is normally assigned to secondary functions does nothing and these functions are duplicated on the analog stick. for example in delta force urban warfare if you run forward it changes between the different night vision modes which is what the dpad up should do if you turn left or right it changes weapons making it unplayable, in alone in the dark 4 the control of the movement and flashlight control are combined in acecombat 3, camera control and plane control are combined

[Delta Force Urban Warfare (USA) (En-Fr-Es).zip](https://github.com/notaz/pcsx_rearmed/files/13049206/Delta.Force.Urban.Warfare.USA.En-Fr-Es.zip)

**Comment by Reideldm** [comment]
https://github.com/notaz/pcsx_rearmed/assets/137739449/7206c80e-842c-460e-b9b0-8de907d4a365

**Comment by notaz** [comment]
Works correctly here with a Logitech pad. What you show here happens if "Analog to digital" is set in config, and perhaps the dpad buttons got unbound. I suggest trying a fresh install.

**Comment by Reideldm** [comment]
thanks for the feedback

**Comment by Reideldm** [comment]
I found the problem in the auto config folder, there is the cfg file of the twin usb adapter that I use to connect the PS1 controller that I have and these lines were not there

input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
