### ISSUE TITLE
Sound Scope CDDA visualizer in PSX BIOS locks up emulator

### ISSUE THREAD

**Issue by vaguerant** [notaz/pcsx_rearmed#327]
### PCSX-ReARMed Version

r23l 2636d7c

### Your device

PC

### Operating System of your device

Windows

### CPU architecture

x86-64 (64bit Intel, AMD, etc.)

### Issue description

Loading up an audio CD then pressing the emulated PlayStation Select button to switch to the Sound Scope mode (music visualizer bundled into SCPH-700x+ BIOSes) causes the emulated console to stop functioning. The CDDA continues playing, but there is no response to further input and the screen stops updating. The CD can continue on to additional tracks, so the system does not appear to be locked up, but it is completely unresponsive.

### Step-by-step reproduction and logs

In RetroArch:
1. Enable Quick Menu > Options >System > Show BIOS Boot logo
2. Load a normal PlayStation game disc
3. During the BIOS boot animation, return to the RetroArch menu's Quick Menu > Disc Control > Load New Disc and load a disc image of an audio CD (I'm using a `cue`+`wav` for testing)
4. Start the CD playing (will probably vary by BIOS, but press X on the Play icon in western BIOSes)
5. Press the Select button to switch to Sound Scope mode/lock up emulator

I haven't attached a log because nothing is appended to the log when switching to Sound Scope mode.

### Additional notes

I'm pretty sure this is a heavily unintended use of pcsx-reARMed, so if you don't consider this an issue because it's just not something you're supposed to be doing with pcsx-reARMed, then that's fine. I wouldn't ordinarily be trying this hard to do things the emulator doesn't really expose except that it affects downstream emulators which more readily expose the BIOS CD player functionality; I only went out of my way in order to confirm that it's an issue that comes from upstream.

**Comment by notaz** [comment]
This should work now in all configurations.
