### ISSUE TITLE
Can't compile [RaspberryPi/Arch]

### ISSUE THREAD

**Issue by gyeben** [notaz/pcsx_rearmed#33]
I tried compiling pcsx_rearmed on a Raspberry Pi, but I got the following error message:

g++ -o pcsx libpcsxcore/cdriso.o libpcsxcore/cdrom.o libpcsxcore/cheat.o libpcsxcore/debug.o libpcsxcore/decode_xa.o libpcsxcore/disr3000a.o libpcsxcore/mdec.o libpcsxcore/misc.o libpcsxcore/plugins.o libpcsxcore/ppf.o libpcsxcore/psxbios.o libpcsxcore/psxcommon.o libpcsxcore/psxcounters.o libpcsxcore/psxdma.o libpcsxcore/psxhle.o libpcsxcore/psxhw.o libpcsxcore/psxinterpreter.o libpcsxcore/psxmem.o libpcsxcore/r3000a.o libpcsxcore/sio.o libpcsxcore/socket.o libpcsxcore/spu.o libpcsxcore/gte.o libpcsxcore/gte_nf.o libpcsxcore/gte_divider.o libpcsxcore/gte_arm.o libpcsxcore/new_dynarec/new_dynarec.o libpcsxcore/new_dynarec/linkage_arm.o libpcsxcore/new_dynarec/pcsxmem.o libpcsxcore/new_dynarec/emu_if.o plugins/dfsound/dma.o plugins/dfsound/freeze.o plugins/dfsound/registers.o plugins/dfsound/spu.o plugins/dfsound/out.o plugins/dfsound/nullsnd.o plugins/dfsound/arm_utils.o plugins/dfsound/oss.o plugins/dfsound/alsa.o plugins/dfsound/sdl.o plugins/dfsound/pulseaudio.o plugins/gpulib/gpu.o plugins/gpulib/vout_pl.o plugins/gpu_unai/gpulib_if.o plugins/gpu_unai/gpu_arm.o plugins/cdrcimg/cdrcimg.o plugins/dfinput/main.o plugins/dfinput/pad.o plugins/dfinput/guncon.o frontend/cspace.o frontend/cspace_arm.o frontend/libpicofe/in_sdl.o frontend/libpicofe/plat_sdl.o frontend/libpicofe/plat_dummy.o frontend/libpicofe/linux/in_evdev.o frontend/plat_sdl.o frontend/libpicofe/gl.o frontend/libpicofe/gl_platform.o frontend/plugin_lib.o frontend/libpicofe/linux/plat.o frontend/libpicofe/readpng.o frontend/libpicofe/fonts.o frontend/menu.o frontend/libpicofe/input.o frontend/main.o frontend/plugin.o   -L/usr/lib -lSDL -lpthread -lpulse -lasound -lpng  -ldl -lm -lpthread -lz -lasound -lEGL -lGLESv1_CM  -L/opt/vc/lib -Wl,-Map=pcsx.map
frontend/libpicofe/gl_platform.o: In function `gl_platform_init':
/home/gyeben/pcsx_rearmed/frontend/libpicofe/gl_platform.c:113: undefined reference to `bcm_host_init'
frontend/libpicofe/gl_platform.o: In function `get_window_rect':
/home/gyeben/pcsx_rearmed/frontend/libpicofe/gl_platform.c:39: undefined reference to `graphics_get_display_size'
frontend/libpicofe/gl_platform.o: In function `submit_rect':
/home/gyeben/pcsx_rearmed/frontend/libpicofe/gl_platform.c:81: undefined reference to `vc_dispmanx_display_open'
/home/gyeben/pcsx_rearmed/frontend/libpicofe/gl_platform.c:82: undefined reference to `vc_dispmanx_update_start'
/home/gyeben/pcsx_rearmed/frontend/libpicofe/gl_platform.c:84: undefined reference to `vc_dispmanx_element_add'
/home/gyeben/pcsx_rearmed/frontend/libpicofe/gl_platform.c:92: undefined reference to `vc_dispmanx_update_submit_sync'
frontend/libpicofe/gl_platform.o: In function `gl_platform_finish':
/home/gyeben/pcsx_rearmed/frontend/libpicofe/gl_platform.c:125: undefined reference to `vc_dispmanx_display_close'
/home/gyeben/pcsx_rearmed/frontend/libpicofe/gl_platform.c:126: undefined reference to `bcm_host_deinit'
collect2: error: ld returned 1 exit status
Makefile:249: recipe for target 'pcsx' failed
make: *** [pcsx] Error 1

**Comment by notaz** [comment]
Try current git and run ./configure again.

**Comment by gyeben** [comment]
I successfully compiled pcsx_rearmed, but now I get a black screen when I start it.

**Comment by ssilverm** [comment]
I get the same issue.  Using dispmanx solved the black screen.
