### ISSUE TITLE
yu gi oh forbidden memories graphical glitch

### ISSUE THREAD

**Issue by Reideldm** [notaz/pcsx_rearmed#330]
### PCSX-ReARMed Version

162bbc5

### Your device

PS Classic

### Operating System of your device

Other (consoles, etc.)

### CPU architecture

None

### Issue description

The game has a black screen and the image appears and disappears in a blink, making it unplayable.

### Step-by-step reproduction and logs

The problem appears from the beginning of the game, only the cinematics are displayed correctly

**Comment by saulfabregwiivc** [comment]
BTW, there was a similar issue with **Gran Turismo (USA)** where it crashed at a black screen soon after it finish loading a race, but with the commit from notaz it seems fixed.

BTW, thanks @notaz!
