### ISSUE TITLE
Stuttering/slowdown issues in FF7

### ISSUE THREAD

**Issue by medeirosT** [notaz/pcsx_rearmed#336]
### PCSX-ReARMed Version

8412166f53abb220b85e0aff47924c04724abfa4

### Your device

Anbernic RG351P

### Operating System of your device

Linux (or Linux-based like RetroPie etc.)

### CPU architecture

ARM 64bit (AArch64)

### Issue description

Basically there are certain battles in FF7 where there are noticeable slowdowns where there weren't any (To a point where even the music slows down, cursor SFX in-battle time-stretches, etc..)

the cursor also flickers when moving between battle actions

The previous commit does not have this issue.

### Step-by-step reproduction and logs

When entering certain battles, the game might slowdown (Audio as well)
Moving the cursor in-battle flickers when changing options

**Comment by notaz** [comment]
Could you be more specific when does this exactly happen? A savestate or memcard file from just before starting such a battle would help.

**Comment by medeirosT** [comment]
[Final Fantasy 7.zip](https://github.com/notaz/pcsx_rearmed/files/14729926/Final.Fantasy.7.zip)
I've attached a save file where the main character finally starts running in the world map. 

A good example is by running around the muddy area:

![image](https://github.com/notaz/pcsx_rearmed/assets/1336826/b23bfc0d-bb43-4366-a505-47f7f61e1c96)

until you say, fight these guys:

![image](https://github.com/notaz/pcsx_rearmed/assets/1336826/2fb7d838-0dab-4549-ab4f-f132b5b38fc5)

By moving around the cursor in battle it looks like it is flickering, and there are noticeable slowdowns with the music/game

**Comment by notaz** [comment]
I think I've fixed the flickering, but do check for the slowdowns as I haven't noticed any before.

**Comment by medeirosT** [comment]
I'll compile the latest commit and let you know!!

**Comment by medeirosT** [comment]
Latest commit fixes all issues! Thanks for the support!
