### ISSUE TITLE
Monkey Hero – Gradual texture corruption | PS Vita / ARM 32bit, NEON

### ISSUE THREAD

**Issue by swosho** [notaz/pcsx_rearmed#337]
### PCSX-ReARMed Version

r24l 2b2ac30d

### Your device

PS Vita

### Operating System of your device

Other (consoles, etc.)

### CPU architecture

ARM 32bit

### Issue description

Monkey Hero exhibits the same texture corruption / mosaic effect as reported and demonstrated by @DrUm78 back in https://github.com/notaz/pcsx_rearmed/issues/271#issuecomment-1319309349, which doesn't seem to occur on the n3DS (Unai renderer?).
The effect messes up the textboxes, ground and object textures, but seemingly leaves the sprites alone.
I briefly tested the game before the sound effects playback was fixed and there didn't seem to be any graphical issues at the time, but now the sound is fully working, the performance is improved by 15-20% (completely full speed now on the Vita!), and this thing has appeared.

![2024-03-22-150822](https://github.com/notaz/pcsx_rearmed/assets/5187034/cff553e9-814b-4e7d-83e4-2b6919eb8e96)
![2024-03-22-150522](https://github.com/notaz/pcsx_rearmed/assets/5187034/9aaa3c5f-c0a2-4d22-93f2-3d19558e8ac5)

### Step-by-step reproduction and logs

Simply play the game as normal and the glitch will show up before long, sometimes the game even boots into the main menu with the floor glitched from the get-go. If you want to observe the effect quickly: enter the options room from the main menu and walk forward until the screen flashes and the first corruptions manifest, then leave the options and start the new game.

**Comment by notaz** [comment]
You need to disable frameskip for this game. Because of the weird way this game sends commands to the GPU frameskip can't work properly.

**Comment by notaz** [comment]
Nevermind fixed the frameskip (assuming that's the problem you're seeing and not something else).

**Comment by swosho** [comment]
You're right, it was the frameskip all along! The frameskip was usually non-functional or unavailable in the Vita builds of libretro cores, so I didn't pay attention to it, my bad...
Toggling it from "auto" to "off" resolved the glitch immediately on r24l 2b2ac30 (the performance is still great, too), and r24l bbb7cde has no problems with the auto frameskip now. Thanks a lot!
