### ISSUE TITLE
MTV Music Generator can't sample Audio CDs. 

### ISSUE THREAD

**Issue by shoddydev** [notaz/pcsx_rearmed#338]
MTV Music Generator aka Music 2000 has a feature that let's user sample audio cds to create custom riffs. When we hit the record button the progress bar doesn't move. I've tested it on both ISO and Physical cds.

![mtv](https://github.com/notaz/pcsx_rearmed/assets/42045893/99159704-da33-4640-a432-4ab9cecf6dc0)

**Comment by notaz** [comment]
Should be fixed now, closing.

**Comment by shoddydev** [comment]
Thank you! it works. the game is rather confusing when it comes to sampling but I figured it out
