### ISSUE TITLE
Tekken 3 gets stuck on the vs screen

### ISSUE THREAD

**Issue by Reideldm** [notaz/pcsx_rearmed#343]
### PCSX-ReARMed Version

r24l 459f02a

### Your device

PS Classic

### Operating System of your device

None

### CPU architecture

None

### Issue description

tekken 3 gets stuck on vs screen when facing nina willians

### Step-by-step reproduction and logs

play in arcade mode if you face nina the game gets stuck on vs screen

**Comment by Reideldm** [comment]
[tekken 3.zip](https://github.com/user-attachments/files/16044022/tekken.3.zip)

**Comment by papparappa** [comment]
I was also having this issue on Switch up until recently, but as of the latest release of https://github.com/libretro/pcsx_rearmed (19f1a7d2de3a136810a84341db77d4f5eb8f3361)
This no longer seems to happen and i can get past Nina without problems

**Comment by notaz** [comment]
Indeed this seems to be the same issue as libretro#840 which was fixed. Closing.
