### ISSUE TITLE
Performance Differences

### ISSUE THREAD

**Issue by mikhaelcool7** [notaz/pcsx_rearmed#346]
### PCSX-ReARMed Version

r24l 237887e

### Your device

Miyoo Mini Plus

### Operating System of your device

Linux (or Linux-based like RetroPie etc.)

### CPU architecture

ARM 32bit

### Issue description

Drastically worse performance using https://github.com/notaz/pcsx_rearmed/releases/download/libretro-devbuild/pcsx_rearmed_libretro_arm32_miyoo.zip than https://github.com/notaz/pcsx_rearmed/releases/download/libretro-devbuild/pcsx_rearmed_libretro_arm32_classic_armv7_a7.zip on the Miyoo Mini Plus. The Miyoo build also has Downsampling by default which breaks textures in some games. Disabling the feature, halves the performance. Using the regular A7 build does not have any of these issues and runs better or as expected. Running MinUI 20240924-2.

**Comment by notaz** [comment]
Well Miyoo support was added in ad32ae1720d53421222038f25c0d4a344aacb371 by @jSTE0 as an ARM9 device. ARM9 is pretty ancient CPU without NEON and can't use many optimizations of this emulator, so they are disabled in that build.

Maybe it's for some old version of the device? Is there a list of all Miyoo devices and CPUs they have? I've tried a quick search but couldn't find it.

**Comment by jSTE0** [comment]
Miyoo is a brand that rebadges all sort of devices. In this context, Miyoo refers to the devices supported by [TriForceX/MiyooCFW](https://github.com/TriForceX/MiyooCFW) and includes BittBoy, PocketGo, PowKiddy V90-Q90-Q20, all powered by the Allwinner F1C100s which has an ARM926EJ-S CPU.
The Miyoo Mini, including the Plus (which AIUI has a larger screen), uses a Sigmastar SSD202D which has a dual-core Cortex-A7 so it should use the ARMv7 build.

**Comment by notaz** [comment]
The build in question is now named miyoo_arm926 to avoid confusion, closing.
