### ISSUE TITLE
eagle one harrier attack freezes

### ISSUE THREAD

**Issue by Reideldm** [notaz/pcsx_rearmed#347]
### PCSX-ReARMed Version

r241237887e

### Your device

PS Classic

### Operating System of your device

Other (consoles, etc.)

### CPU architecture

ARM 32bit

### Issue description

eagle one harrier attack freezes after pressing the star button in-game

### Step-by-step reproduction and logs

Choose the mission once you start the mission press star and the game freezes with only the background music playing

**Comment by notaz** [comment]
I think this should be fixed by now. You can reopen if not.

**Comment by Reideldm** [comment]
works perfect
