### ISSUE TITLE
Latest version Of pcsx rearmed on retroarch runs too fast

### ISSUE THREAD

**Issue by mckimiaklopa** [notaz/pcsx_rearmed#35]
pls close if false.

SOME games(I tested ff7 and ff9) ran faster(or maybe it was the music that ran too fast.unsure) than it should.It ran around 61-63 frames per second.

**Comment by notaz** [comment]
Frame rate is controlled by RetroArch, not the emu core, you need to report this to RetroArch project along with details of the device that you're using.

**Comment by mckimiaklopa** [comment]
actually,it was more of a timing problem
After some testing,I have found out that on FF7-9,the sound will suddenly an  randomlyspeed up than go to normal speeds on a battles sometimes even crashing(something which happened in FF7 for me many times).Speaking of crashes,Loading FF7 will sometimes crash it(right before or during the FMV that plays before the new game screen).Other games that crash are :Castlevania SOTN(similar to ff7) and School rivals(it sometimes refuses to load the gym stage)
Device:Galaxy S Duos 2
1.2 ghz
pcsx reamed version r21

i noticed that r22 has become available.Maybe the fixes applied to r22 might remove the issues i mentioned

**Comment by notaz** [comment]
Yeah there was a crash bug in r21. As for the sound, I don't have multicore Android devices to test, but could reproduce and fix similar issues on PC build.
Try r22 when it's available and report back.

**Comment by mckimiaklopa** [comment]
i have tested r22 and i can tell you that the crashes i mentioned are now non-existent and the music in the Final Fantasy games now play at normal speed

**Comment by notaz** [comment]
That's good to hear, closing.
