### ISSUE TITLE
Black Borders on the NTSC versions of Final Fantasy VII

### ISSUE THREAD

**Issue by mckimiaklopa** [notaz/pcsx_rearmed#36]
This is a very minor nitpick but it is still a legit issue.

The NTSC versions of Final fantasy VII have black top and bottom borders on all parts except  on the world map(this also happens on other ps1 emus like epsxe and fpse).On the transition from the world map into a field or on battle,the screen suddenly squishes to make room for the black borders.Pictures below is PCSX-ReArmed on android
![retroarch-0209-200626](https://cloud.githubusercontent.com/assets/5818289/6106283/1e2aa332-b09b-11e4-8056-5168d794f138.jpg) 

This is not what happens on a real console or on much more accurate emus like Mednafen's(shown below.Notice how everything seems taller)
![ff7](https://cloud.githubusercontent.com/assets/5818289/6106306/50731928-b09b-11e4-84fd-173bd91a64e4.jpg)

The black Borders are normal on the PAL version of the game though.This is quite annoying since it squishes the graphics

**Comment by mckimiaklopa** [comment]
also happens on crash bandicoot 1-3 whereinbthe borders are too big

**Comment by mckimiaklopa** [comment]
also happens on crash bandicoot 1-3 wherein the borders are too big

**Comment by mckimiaklopa** [comment]
Some observations:
1.In the PAL version of final fantasy VII on Pcsx Rearmed,the aspect ratio is consistent in every screen which is the correct behavior in both the NTSc and PAL versions.As stated above,the NTSC version when played on PCsx rearmed has inconsistencies on aspect ratio wherein the world map mode has the correct screen size while other modes(battle,field,menu) have incorrect aspect ratios.

2.The PAL version of crash bandicoot on PCSX rearmed has no borders which is how it supposed to be(this game is really optimized for PAL unlike FF7).
It seems that the NTSC version really displays an incorrect aspect ratio(due to the black borders) when played on pcsx rearmed because because from what I have observed,the ntsc and Pal version is supposed to have nearly the same aspect ratio.
the ntsc version just looks really squished compared to PAL.

I know that i can adjust the aspect ratio myself but it is not really a permanent solution.

**Comment by notaz** [comment]
The borders related code has been rewritten so at least FF7 should be behaving consistent now.
