### ISSUE TITLE
Restart content does not work for pcsx-rearmed in Retroarch

### ISSUE THREAD

**Issue by mckimiaklopa** [notaz/pcsx_rearmed#38]
selecting the "restart content" option on retroarch while pcsx-rearmed is running freezes the app.I have tested many versions of retroarch old and new it always happens with pcsx-rearmed r22 (i copied the .so file of pcsx-rearmed r22 on the root directory of retroarch.)

r19 works fine though

**Comment by sergiobenrocha2** [comment]
I can confirm that.

**Comment by sergiobenrocha2** [comment]
It was fixed in the libretro fork
