### ISSUE TITLE
Internal Slow Down on RIdge Racer Turbo

### ISSUE THREAD

**Issue by mckimiaklopa** [notaz/pcsx_rearmed#39]
When playing Ridge Racer turbo,the internal frame in the game would dip from 60 in-game fps to 20 and below fps.It is supposed to run at a constant 60 fps.It's as if pcsx is runing an underclocked playstation when  running this game.It is running at constant 100% on pcsx though(the framerate is just emulated incorrectly)

**Comment by Kelduum** [comment]
I've noticed this as well and spent a while identifying a fix - it looks to be that the default config (for the version in the current RetroPie) uses a 57% CPU clock rate, which can be adjusted in the settings - once increased to 100%, this seems to fix the problem entirely.

The same issue also affects the original version of Ridge Racer, but less obviously, resulting in the whole game slowing down slightly (more noticeably with the 'Turbo' version when culling is happening, for example when exiting the tunnel after the start-finish straight, or at a number of points during the 'construction' zone on the longer tracks - you can confirm this by looking at the rate the lap timer and time limit are updating, which slows notably.

This also effects the lr-pcsx-rearmed build, but as that is missing the settings for the CPU overclock, there's no option to work around there at the moment.

**Comment by notaz** [comment]
There are such timing problems due to design of this emulator. If somebody has a clock setting that matches the hardware better please post it here and it can be added to the defaults. Closing for now.
