### ISSUE TITLE
Speed Punks/Speed Freaks - Black textures

### ISSUE THREAD

**Issue by ghost** [notaz/pcsx_rearmed#40]
Hello,
When playing Speed Punks, most of the textures are black.
It's probably a ligthning problem because, when inrace, most textures are overbright.

**Comment by notaz** [comment]
What platform?
Seems to be fine on ARM+NEON.

**Comment by marespiaut** [comment]
It does so on x86_64.

**Comment by notaz** [comment]
This should be fixed since x86_64 is also using the NEON plugin now. Feel free to reopen if not.
