### ISSUE TITLE
Segfaults on Raspberry Pi 2

### ISSUE THREAD

**Issue by steevp** [notaz/pcsx_rearmed#42]
PCSX ReARMed isn't working on the Raspberry Pi 2. The libretro core works, but not the standalone version. 

stingray101 from the Raspberry Pi forums found that it works after changing a memory address in psxmem.c, but doesn't know why:
http://www.raspberrypi.org/forums/viewtopic.php?p=722911#p722911

Any ideas?

**Comment by notaz** [comment]
Could you post the terminal output for the case when it crashes?

**Comment by steevp** [comment]
Here's the output (Running under X since when it crashes on the framebuffer I'm stuck with a black screen)

    Starting program: /home/steven/src/pcsx_rearmed/pcsx 
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/usr/lib/libthread_db.so.1".
    plat_sdl: using 1280x720 as fullscreen resolution
    plat_sdl: overlay: fmt 59565955, planes: 1, pitch: 1280, hw: 0
    warning: video overlay is not hardware accelerated, not going to use it.
    libEGL warning: DRI2: failed to authenticate
    Unable to create EGL surface (3003)
    input: new device #0 "sdl:keys"
    input: new device #1 "sdl:Microsoft X-Box 360 pad"
    input: async-only devices detected..
    # drv probed binds name
    0   0      y     y sdl:keys
    1   0      y     y sdl:Microsoft X-Box 360 pad
    found skin.txt
    menu_load_config: failed to open: ./.pcsx/pcsx.cfg
    frontend/libpicofe/readpng.c: failed to open: /home/steven/.picodrive/skin/background.png
    me_id2offset: id 28 not found
    Starting PCSX-ReARMed r22-2-g663fc55
    Running PCSX Version 1.9 (Mar 23 2015).
    warning: failed to do hugetlb mmap (0x80000000, 2162688): 22
    psxMap: warning: wanted to map @80000000, got (nil)
    [New Thread 0x70794450 (LWP 1761)]
    [New Thread 0x70f94450 (LWP 1760)]
    [New Thread 0x71794450 (LWP 1759)]
    [New Thread 0x71f94450 (LWP 1758)]
    [New Thread 0x74cff450 (LWP 1756)]
    [New Thread 0x754ff450 (LWP 1755)]
    [New Thread 0x75cff450 (LWP 1754)]
    [New Thread 0x7662f450 (LWP 1753)]
    
    Program received signal SIGSEGV, Segmentation fault.
    0x0011bf8c in plat_munmap (ptr=0x76fe557c <_dl_runtime_resolve+24>, size=0)
        at frontend/libpicofe/linux/plat.c:224
    224		ret = munmap(ptr, size);

**Comment by ssilverm** [comment]
Hey Notaz,
can confirm, not working on Pi2.  Get blankscreen and lose all input.  Can still SSH into box.

Changing 0x80000000 to 0x70000000 in psxMemInit() in pcxmem.c seems to fix it.

**Comment by notaz** [comment]
Should be fixed by 85f2398236b54db46340dad14330102f281ca4f3

**Comment by steevp** [comment]
Yep it works now. Thanks

**Comment by reedlove** [comment]
Can someone please confirm that this does in fact work from terminal and not just X?
I've compiled the most current source on a Raspberry Pi 2 running Arch Linux ARM and when I run pcsx it just kills the screen. The system is still running, as I can SSH in to it, but I can't recover the terminal unless I restart.
