### ISSUE TITLE
Android 5 Lollipop crash

### ISSUE THREAD

**Issue by mi1s0n** [notaz/pcsx_rearmed#44]
Hi,Tnx for great work
Pcsx rearmed isn't working on Android 5 devices.here is the logcat log

I/RetroArch(16856): Creating Native Activity: 0xb85fab28
I/RetroArch(16856): Waiting for Android Native Window to be initialized ...
I/RetroArch(16856): Creating Native Activity: 0xb8618600
I/RetroArch(16856): Waiting for Android Native Window to be initialized ...
I/RetroArch(16856): Start: 0xb8618600
I/RetroArch(16856): Resume: 0xb8618600
I/RetroArch(16856): InputQueueCreated: 0xb8618600 -- 0xb861b080
I/RetroArch(16856): Attaching input queue to looper
I/RetroArch(16856): NativeWindowCreated: 0xb8618600 -- 0xb861bf30
I/RetroArch(16856): Android Native Window initialized.
I/RetroArch(16856): WindowFocusChanged: 0xb8618600 -- 1
W/System.err(16856): java.lang.NoSuchMethodError: no non-static method "Lsoorena/cooloop/EmulatorActivity;.onRetroArchExit()V"
I/RetroArch(16856): Checking arguments passed from intent ...
I/RetroArch(16856): Config file: [/storage/emulated/0/Cooloop/consoles/config.cfg].
I/RetroArch(16856): Libretro path: [/data/app/soorena.cooloop-1/lib/arm/libplaystation.so].
I/RetroArch(16856): Auto-start game /storage/emulated/0/Cooloop/roms/3527/3527.cue.
I/RetroArch(16856): start state path: [/storage/emulated/0/Cooloop/roms/3527/start.state].
I/RetroArch(16856): temp state path: [/storage/emulated/0/Cooloop/temp/temp.state].
W/Bundle  (16856): Key isMultiplayer expected Integer but value was a java.lang.Boolean.  The default value 0 was returned.
W/Bundle  (16856): Attempt to cast generated internal exception:
W/Bundle  (16856): java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Integer
W/Bundle  (16856): at android.os.BaseBundle.getInt(BaseBundle.java:800)
W/Bundle  (16856): at android.content.Intent.getIntExtra(Intent.java:4746)
W/IInputConnectionWrapper(13756): showStatusIcon on inactive InputConnection
I/RetroArch(16856): Using content: /storage/emulated/0/Cooloop/roms/3527/3527.cue.
I/RetroArch(16856): cpuinfo_len is (401):
I/RetroArch(16856): Processor	: ARMv7 Processor rev 2 (v7l)
I/RetroArch(16856): processor	: 0
I/RetroArch(16856): BogoMIPS	: 13.53
I/RetroArch(16856): 
I/RetroArch(16856): processor	: 1
I/RetroArch(16856): BogoMIPS	: 13.53
I/RetroArch(16856): 
I/RetroArch(16856): processor	: 2
I/RetroArch(16856): BogoMIPS	: 13.53
I/RetroArch(16856): 
I/RetroArch(16856): processor	: 3
I/RetroArch(16856): BogoMIPS	: 13.53
I/RetroArch(16856): 
I/RetroArch(16856): Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 
I/RetroArch(16856): CPU implementer	: 0x51
I/RetroArch(16856): CPU architecture: 7
I/RetroArch(16856): CPU variant	: 0x0
I/RetroArch(16856): CPU part	: 0x06f
I/RetroArch(16856): CPU revision	: 2
I/RetroArch(16856): 
I/RetroArch(16856): Hardware	: QCT APQ8064 MAKO
I/RetroArch(16856): Revision	: 000b
I/RetroArch(16856): Serial	: 0000000000000000
I/RetroArch(16856): 
I/RetroArch(16856): found cpuCount = 4
I/RetroArch(16856): found cpuArch = '7'
I/RetroArch(16856): found cpuProc = 'ARMv7 Processor rev 2 (v7l)'
I/RetroArch(16856): found cpuFeatures = 'swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 '
I/RetroArch(16856): [CPUID]: Features: NEON
I/RetroArch(16856): Loading config from: /storage/emulated/0/Cooloop/consoles/config.cfg.
I/ActivityManager(  547): Displayed soorena.cooloop/.EmulatorActivity: +404ms
I/WindowManager(  547): Screen frozen for +264ms due to Window{17e57527 u0 Starting soorena.cooloop}
I/RetroArch(16856): Loading dynamic libretro from: "/data/app/soorena.cooloop-1/lib/arm/libplaystation.so"
W/linker  (16856): libplaystation.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
I/RetroArch(16856): Environ SET_VARIABLES.
I/RetroArch(16856): Version of libretro API: 1
I/RetroArch(16856): Compiled against API: 1
I/PCSX    (16856): Starting PCSX-ReARMed r15-369-g1b88529
I/PCSX    (16856): Running PCSX Version 1.9 (Mar  9 2014).
I/PCSX    (16856): psxMap: warning: wanted to map @1f800000, got 0xb3d22000
I/PCSX    (16856): psxMap: warning: wanted to map @1fc00000, got 0xa4e12000
I/PCSX    (16856): psxMap: warning: wanted to map @a5000000, got 0xa4e12000
I/PCSX    (16856): Error allocating memory!
I/PCSX    (16856): PSX emulator couldn't be initialized.
I/PCSX    (16856): PCSX init failed.
I/WindowState(  547): WIN DEATH: Window{2e69e21f u0 soorena.cooloop/soorena.cooloop.EmulatorActivity}
I/Zygote  (  197): Process 16856 exited cleanly (1)
I/ActivityManager(  547): Process soorena.cooloop:emulator (pid 16856) has died
W/ActivityManager(  547): Force removing ActivityRecord{29f52f4b u0 soorena.cooloop/.EmulatorActivity t2526}: app died, no saved state
W/art     (13756): Attempt to remove local handle scope entry from IRT, ignoring

**Comment by notaz** [comment]
You are using an outdated version, more than a year old, from long before Android 5 existed. This has since been fixed.

I don't know why RetroArch still ships this old version on Play store.
