### ISSUE TITLE
Need For Speed: High Stakes - dropped inputs on r22 under Retroarch (Android)

### ISSUE THREAD

**Issue by ice445** [notaz/pcsx_rearmed#45]
As the title suggests, there's a strange issue that only seems to occur on the latest version. I went back to r19 and the game plays flawlessly.

Basically, a guaranteed way to reproduce this is to load up a test drive on the "Route Adonf" track using a Porsche 911 or Ferrari F50. Select manual transmission, and try playing. Many inputs are either delayed or lost entirely. Shifts, changing camera, steering, it's all affected. Audio and video are perfect, which is what baffles me. Possible issue of how it was packed into a libretro core? I tried playing with the emulator's settings and doing things like turning off Vsync and threaded rendering. Nothing I did made a difference. It does seem like it's something to do with the internal timing of the game, because sometimes it can't attain 30FPS (like many PS1 titles). I also tried turning off the new Reverb effects (and sound entirely) to no avail.

Please investigate and see if you can reproduce the issue, thanks.

**Comment by notaz** [comment]
The input code has since been rewritten and the issue is likely fixed. Feel free to reopen if not.
