### ISSUE TITLE
Analog controls do not reach the full range of the "up" axis for the left and right joysticks.

### ISSUE THREAD

**Issue by GriffinCreativeStudios** [notaz/pcsx_rearmed#46]
Hi there. I am running the version of PCSX-Rearmed that ships with RetroPie v 2.6.

I am attempting to play Ape Escape (using a wireless xbox360 pad using xboxdrv run as a daemon) and when trying to run forward (hold the left joystick up) or swing my weapon forward (hold the right joystick up) these actions are not fully recognized.

After doing some research, this is a problem in many emulators (particularly ePSXe, though) where the controller input isn't being mapped to the full range of the axis.

According to my research, Ape escape requires the left stick's y axis to be at 100% to reach a full run, otherwise it allows for analog control of walking speeds, and presumably the right stick's y axis must reach 100% to swing.

I am able to reach the full range of the left stick from the1 o'clock position all the way around to about the 11 o'clock position. It is only when purely trying to press the y axis all the way "up" that it doesn't work.

This is a common issue with this game, but I am wondering if anyone is aware of this issue, as Ape Escape is really "the" game when it comes to analog controls on the PS1.

Everything about this project is awesome, and I love you guys for it!

**Comment by swrrga** [comment]
I can confirm this bug - running to a slight diagonal allows for full speed movement, but when pressed directly forwards the character only walks.

**Comment by thorst** [comment]
Im running the current version of retropie 4.0.3 and its still having this same issue

**Comment by mitchellcairns** [comment]
I'm on the current version available as of December 2nd, 2016 and this issue still persists.

**Comment by notaz** [comment]
Are you sure retropie is building from this source and not https://github.com/libretro/pcsx_rearmed/ ?
The libretro fork has merged many questionable changes and I've long lost track of what they are doing there.

**Comment by mitchellcairns** [comment]
Good point...

**Comment by mitchellcairns** [comment]
I'll have to double check whether the issue occurs on the non-libretro version

**Comment by notaz** [comment]
After all there years, a quick try doesn't reproduce this issue, so somebody probably fixed it. Closing.
