### ISSUE TITLE
Player 2 controls ignored (Armored Core Master of Arena)

### ISSUE THREAD

**Issue by t1ddlyw1nks** [notaz/pcsx_rearmed#47]
I've built the latest (r22) version of pcsx_rearmed libretro core on my odroid c1 and input from a second controller is ignored.  I have tried numerous controllers and setups and it is only the second player's controller whose input is always ignored.  I know both controllers works and the retroarch config files are set up properly as removing a single controller has things work again.

Any help is appreciated.

**Comment by mschatzgithub** [comment]
Weird, this only appears to be an issue with Armored Core Master of Arena.  I tried Tekken 3 and everything worked as expected.  Thanks.

**Comment by notaz** [comment]
The input code has since been rewritten and the issue is likely fixed. Feel free to reopen if not.
