### ISSUE TITLE
latest not working on Raspberry Pi without X

### ISSUE THREAD

**Issue by havardge** [notaz/pcsx_rearmed#48]
This is what works: If I first run startx, and then head into the terminal and launch pcsx, the emulator launches successfully. But when I try starting it, without X, I only get a black screen and the following terminal output:

/lib/libts-0.0.so.0: cannot open shared object file: No such file or directory
Could not open touchscreen warning: video overlay is not hardware accelerated, not going to use it.

Device: Raspberry Pi Model B+
OS: Raspbian (latest, released: 2015-05-05)

**Comment by reedlove** [comment]
Also appears to hang the framebuffer when ran directly from the terminal, outside of X. =/
I'd be really happy to get this working.

**Comment by notaz** [comment]
The r-pi standalone is no longer maintained, use some libretro frontend instead.
