### ISSUE TITLE
Multi disc pbp files

### ISSUE THREAD

**Issue by i30817** [notaz/pcsx_rearmed#49]
I'm just going to leave here the same thing i left on the pcsxr project page, because as far as i can see the code for this is the same:

Apparently, although the project supports pbp, you can't actually choose the internal iso to use when selecting a pbp file in the 'Switch ISO' option.

This is probably because it's always selecting the first. I looked at the libpcsxcore/cdriso.c:handlepbp function and i frankly don't understand it, but it looks like since it takes no parameter besides the filename, either it's building a index array of all the underlying img files inside the pbp or selecting a 'default one' or both.

Therefore if it's both, there is a user facing operation missing, where the user can ask to select another internal iso instead of always the default (first i think).

As for GUI, i'd prefer if instead of overloading the 'Switch ISO' for pbp files adding a multiselect entry (like the save state entry below) that is only enabled for .pbp where you could choose any of the multiple imgs inside the pbp as 'selected'.
This would allow either changing the file itself (if someone is using multiple formats per multidisc game or segmented multiple disc pbps for some reason) or just choosing another image in the same pbp file.

Or you could be lazy and have a specialized popup in addition (after selecting the pbp on the 'Switch ISO') or replacing the filechooser (if you don't care about multiple format segmentation with pbp).
I'd prefer the first option for obvious reasons.

Notice that epsxe has a popup, and it only works in windows (so in practice the result is the same in linux).

**Comment by notaz** [comment]
I really don't know why are you reporting this here, this fork is mostly used as a libretro backend and has no GUI to speak of, except text-based one that may work on R-Pi and pandora. There are no filechoosers or popups here that you are talking about, I don't think I can help you here.

**Comment by i30817** [comment]
Oh, i should have reported this to libretro itself maybe.

**Comment by i30817** [comment]
Well i opened it there and i was punted to the cores. Looks like this is a hot-potato thing. To be honest, i think that saying that you support pbp when the actual use of this format (single file multi disc compression) is unusuable looks... optimistic to me.

I get that pcsx_rearmed can't do the GUI part, but you can do the API that the GUI will need to actually use the option, that is, list the isos inside the file and change them. That is one of the building blocks needed.

**Comment by notaz** [comment]
If this is still relevant please report at the libretro fork: https://github.com/libretro/pcsx_rearmed/issues

**Comment by i30817** [comment]
I use m3u autocreated from cd filenames with a cmd line utility these days. Also, my computer is broken, so I can't verify anything.
