### ISSUE TITLE
Koudelka CD1 disc image compressed with .ecm appears to blackscreen

### ISSUE THREAD

**Issue by i30817** [notaz/pcsx_rearmed#51]
Tested this out today, seems like the runtime .ecm uncompress procedure makes something disagree with the emulation.
The same .ecm uncompressed and turned into a .img it works fine. I used the ubuntu ecm package to compress and uncompress.

This is regardless of another compression on top like zip or 7z or not.

**Comment by i30817** [comment]
A small hint.... it seems that i simulate psx bios instead of using a real bios ( SCPH101.bin ) it boots.

**Comment by i30817** [comment]
I posted a bug report on upstream too, https://pcsxr.codeplex.com/workitem/12151

But upstream is dead ;)

**Comment by notaz** [comment]
No .7z or .ecm support here.
