### ISSUE TITLE
Koudelka has issues changing discs if they're .ecm'ed

### ISSUE THREAD

**Issue by i30817** [notaz/pcsx_rearmed#52]
As the other bug report says, the only way to use .ecm with this 4 disc game now is to simulate the bios. In addition, whenever you need to change discs, it will not recognize the new disc as valid if it's a .ecm. Since only the simulate bios option works, no other bios was tested.

You can test this by making a savegame on disc 1 (a while into the game), booting disc 2 and then trying to load the savegame (while using .ecms). It will try to load, ask to change disc, but blackscreen forever. If you try to insert a normal img on the disc change (even if using a .ecm for the boot disc), it will load.

**Comment by i30817** [comment]
upstream bug https://pcsxr.codeplex.com/workitem/12152

**Comment by notaz** [comment]
This fork has no ecm support.
