### ISSUE TITLE
Analog gamepad mode glitches FF8 battle menus

### ISSUE THREAD

**Issue by TomFrost** [notaz/pcsx_rearmed#54]
Setting pcsx_rearmed_pad1type to "standard", I have no issues in any game I've tried.

Setting it to "analog", however, makes controlling Final Fantasy VIII battle menus a nightmare. The directionals (even the hat) and action buttons on the gamepad are registered anywhere from 0-2 times per press. Navigation and intentional selections are near impossible.  But strangely enough, this is _only_ in the battle menus, and _only_ with pad1type set to analog. All other menus are fine, battles are fine in standard mode. This appears to be specific to pcsx_rearmed as this doesn't happen in any other RetroArch system under the same input config, however I don't have another PSX core to test against.

RetroArch on a Raspberry Pi 2 B (via RetroPie v3.0). This happens on two different Logitech gamepads, as well as keyboard controls.

**Comment by notaz** [comment]
The input code has since been rewritten and the issue is likely fixed. Feel free to reopen if not.

**Comment by Metzli-Cilalti** [comment]
It seems something in the new update to the core made this bug reappear (playing this on Anbernic RG353M and on Steam Deck, both have this issue)

**Comment by notaz** [comment]
Which game and version of the core exactly? Tried FF8 battles and it behaves correctly with all controller types. Could also be caused by old savestates if you're using that.

**Comment by Metzli-Cilalti** [comment]
Final Fantasy 8 NTSC Rom, core version r23 e34ef5a, I do not use savestates. The thumbstick behaves like this: left and right bring the cursor either up or down, it's not only in the battles, it's in every menu, up and down axis does nothing at all. If I am roaming the map it's fine and the character goes exactly where I tell them to go. Rumble functionality also seems to be completely gone (the game does recognize that I have set it to dualshock and I did set vibration to "On" in the in-game settings too).

**Comment by notaz** [comment]
That version has broken rumble in ff8, you need to update. As for the menus, I think I saw something similar to what you describe (but it all is quite different from OP's report). If you use an ARM device you can get a fresh build here:
https://github.com/notaz/pcsx_rearmed/releases/tag/libretro-devbuild

**Comment by Metzli-Cilalti** [comment]
Rumble was actually working fine for me before Retroarch updated the cores, I'll do some more research and I'll try maybe the PAL Rom.

**Comment by Metzli-Cilalti** [comment]
Little update: EU Rom doesn't get past the BIOS screen so I can't test this on the PAL games on my device. I also am unable to update past that version of the core because I got it through Retroarch's Online Updater in ArkOs (it's linked to christianhaitian's github) and that appears to be the latest version, maybe something is wrong with which version is being provided there and that's why I'm suddenly having this old issue again?

**Comment by notaz** [comment]
The EU version of FF8 is copy protected, relies on subchannel data that's usually not in CD images. See here:
https://psxdatacenter.com/sbifiles.html

I can't tell what ArkOS is doing and why are they providing `_libretro` and `_rumble_libretro` versions of the same core when there is a core option to turn runble on/off. Maybe they have some patches or something. It's quite unfortunate when forks do strange things, provide outdated versions and people start reporting bugs here.
