### ISSUE TITLE
[RPI2] [BUG] MGS Graphic Glitch

### ISSUE THREAD

**Issue by nemo93** [notaz/pcsx_rearmed#56]
Not sure if I have to report such issue here or on another place. So please forgive me if I posted at the wrong location. I come in peace :)

This issue is about Metal Gear Solid. It's pretty easy to reproduce. Instead of the white flash which usually announces/opens a cut scene there is a pixel mess with a kind of stroboscopic effect. Really weird. Let me attach a screenshot as it's worth a thousand words I guess. The first time you face it is right after the very first elevator, after Snake takes his swimsuit off. It appears again just a few seconds later when Snake stares at the Hind-D. Pixel mess every time for sure.

I'm using a RP2, latest Retropie version (3.0 final), this core (https://github.com/libretro/pcsx1-libretro) freshly built (but same behavior with the rearmed core). Core options all by default/auto. No video enhancement turned on or something. I'm using bios SCPH1001.BIN but it makes no difference as same behavior occurs with any other bioses.

Being french I'm playing with the FR version of the game (not the Integral or Special version of the game). Didn't try with another version but I could do so if that helps.

Thanks for your help and assistance.

![mgs_retroarch-0831-223744](https://cloud.githubusercontent.com/assets/8100500/9590497/54a8b63a-5035-11e5-9423-056e2b85e2f8.png)

**Comment by John0Doe** [comment]
I am using Recalbox 4.0.0 with RPI 3, SCPH1001.BIN and the pcsx version r22. I have the Same glitches, they are always at the same scenes. Tested with the US, EUR and G Version of the game.

**Comment by notaz** [comment]
I suspect this one is fixed by now. Feel free to reopen if not.
