### ISSUE TITLE
[RPI2] [BUG] Parasite Eve 2 FR freezing

### ISSUE THREAD

**Issue by nemo93** [notaz/pcsx_rearmed#57]
Again not sure if it's the right place to post such stuff. Apologize if I'm at the wrong location...

This time an issue with Parasite Eve 2 and only with the FR version. Indeed both the Euro (UK) and US versions do work! I mean that at least I could pass the very first screen and access the shooting range tutorial. With the FR version I just can't go beyond this "introduction" screen right after selecting New Game on the main title screen. It just sits there forever... Screenshot enclosed to that post for the sake of clarity. 

I've tried with and without the Core Option PE2 fix turned on or off. Same outcome. I tried also to apply a patch to my ISO as this game was heavily copy-protected but same result as well... 

I'm using a RP2, latest Retropie version (3.0 final), this core freshly built (but same behavior with the other rearmed core). Core options all by default/auto. No video enhancement turned on or something. I'm using bios SCPH1001.BIN but it makes no difference as same behavior occurs with any other bios'. Maybe it's worth mentioning too that I tried with both regular cue/bin, ccd/img images as well as a compressed pbp. Same result each time :(

One fix is for me to go to hell with my french and plays the UK/US versions :) That's for sure but first french is nice and then maybe this issue could be somewhat related to the one @barbudreadmon is talking about here ( #53 ). Again thanks a lot for the hard work and if I can do anything to help give me a shout I'll be happy to assist. 
cheers,

![pe2_retroarch-0831-223119](https://cloud.githubusercontent.com/assets/8100500/9590889/c64bff20-5037-11e5-83b6-5dde1a4543e2.png)

**Comment by Megido6** [comment]
i too have this error
game freeze when enabled  Dynamic recompiler. But without decompiler game have more lags

**Comment by zcstrife** [comment]
We need a fix for and of this great game! I'll patreon anyone who would be willing to work on this.

**Comment by notaz** [comment]
It's a known timing issue, would need cache timing emulation which is hard to do on a dynarec. It's possible to add hacks, but they will break other games.

In standalone build, there is "PSX CPU clock" option, increasing that and reloading the game should help.
In libretro build, this option is not currently exposed.

**Comment by Sidordroid** [comment]
My Parasite Eve 2 also freezes at the very beginning

**Comment by Overflask** [comment]
> My Parasite Eve 2 also freezes at the very beginning

Set your CPU clock speed to 70 instead of 57. It worked for me

**Comment by alvariooo99** [comment]
In the Spanish version it also happens but only on my PS2 on my PlayStation 1 can I play normally
