### ISSUE TITLE
[RetroArch for Android] OverBlood character shadow glitches

### ISSUE THREAD

**Issue by 6lackmag3** [notaz/pcsx_rearmed#58]
![retroarch-0917-143013](https://cloud.githubusercontent.com/assets/13922742/9933031/c14ce4e6-5d50-11e5-89a3-03a564e177dd.jpg)
![retroarch-0917-143018](https://cloud.githubusercontent.com/assets/13922742/9933035/ca8321a6-5d50-11e5-99d7-4e25ed334151.jpg)

**Comment by notaz** [comment]
Seems to be ok in the latest version.
