### ISSUE TITLE
"Value too large for defined data type"

### ISSUE THREAD

**Issue by eusi** [notaz/pcsx_rearmed#59]
Hey.

As the title says, it's not able to run a "huge" image (above 2gb).

In my case I tried "Final Fantasy VIII" (as pbp file of 2.2gb) via pcsx_rearmed on RetroPie on my RPi2.

Probably issue and approach to solve this: https://www.gnu.org/software/coreutils/faq/coreutils-faq.html#Value-too-large-for-defined-data-type

Is this fixable?

Greetz
eusi

**Comment by johnweland** [comment]
No leads on this issue yet? I have literally the same exact issue (same .pbp) I was hoping the 64bit CPU of the Pi3 would fix this but without 64bit software the point is moot. I am thinking it just need to be recompiled with largefile support.

**Comment by notaz** [comment]
Pushed.
Could not think of an easy way to actually test it (to make the game read over 2GB from the .pbp).

**Comment by johnweland** [comment]
Awesome! hope I can get my FF8.pbp working.

**Comment by notaz** [comment]
I assume it's fixed, reopen if it isn't.
