### ISSUE TITLE
dynarec crash (SEGV_ACCERR) on Android 5 on Samsumg Phones

### ISSUE THREAD

**Issue by leoqchen** [notaz/pcsx_rearmed#60]
Hi, 

The pcsx_rearmed crash on Android 5 on Samsumg Phones, e.g: Galaxy Note3,  Galaxy Note4, Galaxy S5.
But it work OK on Android 5 on other phones, e.g: Google Nexus, HuaWei, HTC, XiaoMi.

What I have do on the Android 5 on Samsumg Phones:

Step1: 
The interpreter mode work OK, but th dynarec mode always crash immediately after loading game.

Step2:
The crash logcat:
10-20 14:48:18.413: I/PCSX(21375): CheckCdrom()
10-20 14:48:18.413: I/PCSX(21375): CD-ROM Label: SCUS-94154                      
10-20 14:48:18.413: I/PCSX(21375): CD-ROM ID: SCUS94154
10-20 14:48:18.413: I/PCSX(21375): CD-ROM EXE Name: SCUS_941.54;1
.....
10-20 14:48:18.473: A/libc(21375): Fatal signal 11 (SIGSEGV), code 2, fault addr 0x80009001 in tid 21438 (Thread-2060)
10-20 14:48:18.533: I/DEBUG(294): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
10-20 14:48:18.533: I/DEBUG(294): Build fingerprint: 'samsung/h3gzm/hlte:5.0/LRX21V/N9008ZMUGOH2:user/release-keys'
10-20 14:48:18.533: I/DEBUG(294): Revision: '8'
10-20 14:48:18.533: I/DEBUG(294): ABI: 'arm'
10-20 14:48:18.533: I/DEBUG(294): pid: 21375, tid: 21438, name: Thread-2060  >>> com.retroarch <<<
10-20 14:48:18.533: I/DEBUG(294): signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x80009001
10-20 14:48:18.543: I/DEBUG(294):     r0 00000000  r1 00000000  r2 a0009000  r3 a000c160
10-20 14:48:18.543: I/DEBUG(294):     r4 08400000  r5 9ba53000  r6 00000000  r7 00000000
10-20 14:48:18.543: I/DEBUG(294):     r8 fffe0000  r9 00010000  sl ffff21f7  fp 9a424110
10-20 14:48:18.543: I/DEBUG(294):     ip 00000000  sp 9e5fbc30  lr 80009001  pc 9a853aa4  cpsr 300f0010
10-20 14:48:18.543: I/DEBUG(294): backtrace:
10-20 14:48:18.543: I/DEBUG(294):     #00 pc 00000aa4  <unknown>
10-20 14:48:18.543: I/DEBUG(294):     #01 pc 08e5dfff  /dev/ashmem/dalvik-alloc-space-gap (deleted)

I add some dubug print on the dynarec codes, force on mmap/mprotect, get this print out:
10-20 14:45:32.123: I/PCSX(20694): use mprotect: addr=0x9c63a000, length=0x1000000

The fault addr 0x80009001 is out of range of "addr=0x9c63a000, length=0x1000000".

It's a bug on pcsx_rearmed? or it's a bug on Samsung's Android 5?
Any comment will be appreciate.

**Comment by doorbash** [comment]
@leoqchen Could you resolve the issue?
Take a look at this : [https://github.com/notaz/pcsx_rearmed/issues/66](https://github.com/notaz/pcsx_rearmed/issues/66)

**Comment by notaz** [comment]
I'll just assume it's fixed now, create a new issue with logcat output if it's not.
