### ISSUE TITLE
crash  on Android 5 on Samsumg Exynos Octa 7420

### ISSUE THREAD

**Issue by sunshineoflife** [notaz/pcsx_rearmed#61]
Hi,

The pcsx_rearmed crash onSamsumg Exynos Octa 7420(This phone has Cortex-A57 Cortex-A50)
I find it crash in function ari64_execute_until. In fuction ari64_execute_until:
static void ari64_execute_until()
{
	schedule_timeslice();

	evprintf("ari64_execute %08x, %u->%u (%d)\n", psxRegs.pc,
		psxRegs.cycle, next_interupt, next_interupt - psxRegs.cycle);

	new_dyna_start();//crashe here

	evprintf("ari64_execute end %08x, %u->%u (%d)\n", psxRegs.pc,
		psxRegs.cycle, next_interupt, next_interupt - psxRegs.cycle);
}

**Comment by notaz** [comment]
Unfortunately this report isn't really useful, that function is basically doing all the emulation. It might be more useful if you could take the full logcat output just after a crash.

**Comment by sunshineoflife** [comment]
Hi,
The function new_dyna_start is :
FUNCTION(new_dyna_start):
	/* ip is stored to conform EABI alignment */
	stmfd	sp!, {r4, r5, r6, r7, r8, r9, sl, fp, ip, lr}
	load_varadr fp, dynarec_local
	ldr	r0, [fp, #LO_pcaddr]
	bl	get_addr_ht
	ldr	r1, [fp, #LO_next_interupt]
	ldr	r10, [fp, #LO_cycle]
	str	r1, [fp, #LO_last_count]
	sub	r10, r10, r1
	mov	pc, r0
	.size	new_dyna_start, .-new_dyna_start

It's really hard to debug it 

12-21 15:25:02.645: E/CrashReport(32420): # APP VER: 1.5.5
12-21 15:25:02.645: E/CrashReport(32420): # LAUNCH TIME:2015-12-21 15:25:01
12-21 15:25:02.645: E/CrashReport(32420): # CRASH TYPE: NATIVE_CRASH
12-21 15:25:02.645: E/CrashReport(32420): # CRASH TIME: 2015-12-21 15:25:02
12-21 15:25:02.645: E/CrashReport(32420): # CRASH THREAD: Thread-3022
12-21 15:25:02.655: E/CrashReport(32420): # CRASH DEVICE: SM-G9280 ROOTED
12-21 15:25:02.655: E/CrashReport(32420): # RUNTIME AVAIL RAM:1166108000 ROM:17604771840 SD:17583800320
12-21 15:25:02.655: E/CrashReport(32420): # RUNTIME TOTAL RAM:3752376000 ROM:27737153536 SD:27716182016
12-21 15:25:02.655: E/CrashReport(32420): # EXCEPTION FIRED BY KERNEL UNKNOWN(0)
12-21 15:25:02.655: E/CrashReport(32420): # EXCEPTION TYPE: SIGILL(ILL_ILLOPC)
12-21 15:25:02.655: E/CrashReport(32420): # EXCEPTION MSG: 
12-21 15:25:02.655: E/CrashReport(32420): # EXCEPTION STACK:
12-21 15:25:02.655: E/CrashReport(32420):           #00  pc 00000a9c 
12-21 15:25:02.655: E/CrashReport(32420): java:
12-21 15:25:02.655: E/CrashReport(32420): #++++++++++++++++++++++++++++++++++++++++++#

**Comment by notaz** [comment]
No need to post the code, anyone can look it up in the repository. It may look small but it calls almost all of the emulator code, any of it may be actually causing the crash.

Logcat used to give much more output, so either you truncated it or Android has become a lot worse (I don't have any recent device). Some versions of Android make tombstone files, can you get that?

It would be best if you attached the whole files without truncating.

**Comment by sunshineoflife** [comment]
This problem is resolved. Flash the mobile to a new system. 
This is another problem. I want to switch ISO, but can't find how to do it.
