### ISSUE TITLE
I want to switch ISO

### ISSUE THREAD

**Issue by sunshineoflife** [notaz/pcsx_rearmed#62]
I want to switch ISO. This project provide interface for it?

**Comment by notaz** [comment]
I assume you're using RetroArch? The core does support it, but I'm not developing the GUI and I don't use Android, so don't know.

**Comment by sunshineoflife** [comment]
Hi,

When i use RetroArch, 
1、start a game of disk2
2、Append Disk1
3、play new game
RetroArch crashed.

When i try to switch ISO:
1、		retro_reset();
		struct retro_game_info info;
		retro_load_game(&info);
these functions can switch iso, but the game is start at the beginging of the game. 

2、SetIsoFile()
psxCpu->Execute();
these functions can't switch iso

3、i find some interface 
/* multidisk support */
static bool disk_ejected;
static unsigned int disk_current_index;
static unsigned int disk_count;
static struct disks_state {
	char *fname;
	int internal_index; // for multidisk eboots
} disks[8];

static bool disk_set_eject_state(bool ejected)
static bool disk_get_eject_state(void)
static unsigned int disk_get_image_index(void)
static bool disk_set_image_index(unsigned int index)

Unfortunately , i don't konw how to switch ios successfully!
Can you give some ideas or implement of the functions

**Comment by sunshineoflife** [comment]
slove it
