### ISSUE TITLE
[Request] Prevent skipping of bios logos?

### ISSUE THREAD

**Issue by dankcushions** [notaz/pcsx_rearmed#64]
For nostalgia purposes it would be cool to show the PS + SCEE  logo sequence during boot :) i've had a look and I don't think there's an option for this(?). Would it be possible?

PCSX reloaded appears to have an option ("slow boot") that apparently shows the 2 logos during game boot FYI.

Thanks :)

**Comment by objectchris** [comment]
I had a crack at this myself but was unable to get it to work but whilst testing I was getting a compile error 
```
/home/pi/RetroPie-Setup/tmp/build/pcsx-rearmed/frontend/plugin.c:76: undefined reference to `in_a3'
/home/pi/RetroPie-Setup/tmp/build/pcsx-rearmed/frontend/plugin.c:76: undefined reference to `in_a4'
collect2: error: ld returned 1 exit status
```

Fixed it via adding the 3rd line in this block in frontend/plugin_lib.c

```
  int in_type1, in_type2;
  int in_a1[2] = { 127, 127 }, in_a2[2] = { 127, 127 };
  int in_a3[2] = { 127, 127 }, in_a4[2] = { 127, 127 };
  int in_adev[2] = { -1, -1 }, in_adev_axis[2][2] = {{ 0, 1 }, { 0, 1 }};
  int in_adev_is_nublike[2];
  int in_keystate, in_state_gun;
```

Not sure enough that I didn't cause this, or that my change is sensible, so pasting it here so it's searchable in case this is an actual bug :)

**Comment by AmmarkoV** [comment]
Would like to report that this fixes compilation for me also , thanks  dankcushions

**Comment by Hek121** [comment]
Hi,
Any news for this?
For nostalgia purposes it would be very cool! 
@notaz

**Comment by notaz** [comment]
The libretro fork has such an option these days for those who want it.
