### ISSUE TITLE
Final Fantasy VIII freeze after Lunar Cry FMV

### ISSUE THREAD

**Issue by dickroach** [notaz/pcsx_rearmed#65]
I found this old thread while trying to google for a fix to this issue: https://github.com/libretro/RetroArch/issues/228

the button mashing thing just wasn't working, so here's an upload of the save state if anyone could help me out. 
[Final Fantasy VIII (USA).state11.zip](https://github.com/notaz/pcsx_rearmed/files/124136/Final.Fantasy.VIII.USA.state11.zip)

**Comment by davcri** [comment]
I found a fix :smile:  see here : https://github.com/libretro/RetroArch/issues/228#issuecomment-189686206

**Comment by dickroach** [comment]
totally works! thank you!

**Comment by Arrafart** [comment]
After I encountered "The post FMV @Lunar Cry issue" last week, I went to look for a solution online. I eventually found a solution on a different forum which I would like to share here, cause everyone should be a ble to continue the game imo.

I was running FF8 on ePSXe V1.13 and found out it was the emulator causing the problem, or some file within the emulator package from that time. I used a more recent version of the emulator, V2.06 if I'm right, and used "My original memory card file" to load the game.

After the FMV I could now move and the went for a saving spot ASAP. Copy/pasted the new Memory card file back to V1.13 and continued playing.

You could by default use a more recent emulator version to prevent the issue.

Enjoy!

**Comment by gameblabla** [comment]
My PR https://github.com/notaz/pcsx_rearmed/pull/184 fixes that issue.
Libretro already merged it.
