### ISSUE TITLE
 Samsung Galaxy S5 (octa-core)  SM-G900H problem

### ISSUE THREAD

**Issue by doorbash** [notaz/pcsx_rearmed#66]
Hi.Thanks for the great effort you put on this core.
I got this logcat logs from one of my users.PcsxReArmed crashes on his galaxy s5 phone.

[http://pastie.org/private/os1raxbta8k5xka0sbqq](http://pastie.org/private/os1raxbta8k5xka0sbqq)

You can use this online tool to read it easily if you want.

[http://forgottenprojects.com/tools/android/logcat/](http://forgottenprojects.com/tools/android/logcat/)

**Comment by doorbash** [comment]
Sorry but it also not working on Samsung Galaxy S6 (SM-G920F) here is the whole logcat I got:

[http://pastebin.com/Zkv0xhFa](http://pastebin.com/Zkv0xhFa)

**Comment by notaz** [comment]
Pushed something that might help.
I have no way to test it.

**Comment by doorbash** [comment]
Me neither!
Thanks I will add this to next version and put the results here.

**Comment by doorbash** [comment]
It seems the issue is fixed.Thank you notaz you are awesome!
