### ISSUE TITLE
Needs some changes for performance on ARMV8

### ISSUE THREAD

**Issue by joolswills** [notaz/pcsx_rearmed#68]
There is performance lost when building with `-mcpu=cortex-a53` (ARMV8). 

/include/arm_features.h sets a bunch of defined like HAVE_ARMV7 etc, but there are places in the code where they are not used and instead it has

```
#ifdef __ARM_ARCH_7A__ etc
```

In these cases this would not be defined when building for an ARMV8 target. So either they should be switched to use the HAVE_ARMV7 define or the changes should be switched to check the value of __ARM_ARCH >= 7 etc (if this was used, you probably wouldn't need all the logic in /include/arm_features.h

**Comment by notaz** [comment]
Pushed.
__ARM_ARCH is only available on recent compilers, so can't rely on only that.
