### ISSUE TITLE
Small stall and audio dropout in some games (no CPU usage related)

### ISSUE THREAD

**Issue by vanfanel** [notaz/pcsx_rearmed#73]
Hi again,

Having solved the memory mapping mistery with pcsx_rearmed in Raspbian, I felt I should give a go at the last issue I have seen with this great emulator:
In some games, there's a 1-second pause (including sound dropout) when actual gameplay starts for the first time per emulator execution. For example, in Tekken 3, you can see the pause in the first fight, just after the "FIGHT!" voice, and in WipeOut you can see it just before "GO!" in the first race. 
If you keep playing, you NEVER see this pause again: it only happens the first time you enter the first stage, so I guess it's something that is done once and cached while pcsx_rearmed is running.

It happens when using isos from SD, and also when using them from fast USB HDD drives, so it's not because of the slow SD speed on the Pi3: also, a PSX as a 300KB/s CDROM unit so it's unlikely.

Also, it happens with no noticeable CPU usage peaks: top -d1 stays at ~50% CPU usage, and of course there are no other processes eating up CPU when it happens: it always happens at the same point.

Since the pcsx_rearmed core uses dynarec, I looked at cache misses first.
In case of cache misses, it seems the cpu multiplier is decreased, so I played with cycle_multiplier in libretro.c, but it makes no difference.
I also tried increasing the MAXBLOCK and MAX_OUTPUT_BLOCK_SIZE defines in new_dynarec.c, but it makes no difference.

So, maybe it's related to CDROM access cache, but I haven't found any access cache-related defines in cdrom.c/h or cdriso.c/h, so I don't know what could I try. Any ideas?

**Comment by notaz** [comment]
Sounds like delays caused by the dynarec MIPS->ARM recompilation which have since been improved.
