### ISSUE TITLE
Method to make the built-in menufont less big?

### ISSUE THREAD

**Issue by buzztiaan** [notaz/pcsx_rearmed#76]
It's sorta annoying not being able to use the built-in menu on a 480x272 screen ;)

They looked scaled, are they? Could it be configurable somehow?

**Comment by buzztiaan** [comment]
Adding some screenshots here;

![image](https://cloud.githubusercontent.com/assets/940336/20184041/a1313736-a767-11e6-890d-a010296a78f7.png)
![image](https://cloud.githubusercontent.com/assets/940336/20184046/a64f6080-a767-11e6-8d80-370644477b33.png)
![image](https://cloud.githubusercontent.com/assets/940336/20184054/ab133cfe-a767-11e6-83c1-f77dfed698ad.png)

**Comment by buzztiaan** [comment]
this is running on a pocketchip :D works awesome!!

Seems a bit weird to assume any armv7 has hires screen :P but yay!

![image](https://cloud.githubusercontent.com/assets/940336/20184601/82ff67f4-a769-11e6-9030-0e7cb088e6f1.png)

**Comment by notaz** [comment]
Yeah I was too lazy to do runtime detection.
I'll keep this issue open for that.

**Comment by buzztiaan** [comment]
thanks for that \o/

**Comment by notaz** [comment]
If this is still relevant feel free to submit a patch.
