### ISSUE TITLE
lr-pcsx-rearmed not working with libcrypt games

### ISSUE THREAD

**Issue by MJLHThomassen** [notaz/pcsx_rearmed#77]
Hey,

I've been looking around the internet for the past 2 hours trying to figure out why my Spyro 2 - Gatway to Glimmer image is not working on my RetroPie running lr-pcsx-rearmed. After a long google search, I've discovered this is because alot of PAL games (I live in the Netherlands so only have PAL disks) appear to have what is called "libcrypt" encryption. 

Apparantly, this requires a .sbi file being ripped from the disk. Now, I've managed to grab one of these .sbi files belonging to my Spyro 2 disk and put it next to the .bin/.cue in my roms folder, but the game is still crashing (returning to EmulationStation on my RetroPie) when loading one of the levels which are encrypted (any level in the first world).

The readme of pcsx-rearmed lists that libcrypt support has been in there since 2011, however it does not appear to be active when using RetroPie / RetroArch. (Also see dead thread: http://libretro.com/forums/showthread.php?t=3289)

Can anyone help me with this?

**Comment by notaz** [comment]
Probably a file naming issue as this is known to be working. Closing.
