### ISSUE TITLE
Analog controller isn't recognized

### ISSUE THREAD

**Issue by bmn001** [notaz/pcsx_rearmed#79]
Player 1's controller is not recognized as an "analog/dual shock" controller even though "analog" is selected within the RetroArch options menu.

I'm running lr-pcsx-rearmed on the latest version of RetroPie (4.1.8 as of this posting.)  I'm seeing this behavior both on the pcsx binary provided with RetroPie, as well as when I compile the latest from github.

The only way to get the system to recognize the controller as analog is to set **all 8 pads** to analog in the RA options menu.

**Comment by dankcushions** [comment]
this isn't the libetro pcsx repo. you want this one: https://github.com/libretro/pcsx_rearmed

**Comment by bmn001** [comment]
10-4. Thanks.
