### ISSUE TITLE
[Rpi3] Rumble and Analog Support ?

### ISSUE THREAD

**Issue by Aryetis** [notaz/pcsx_rearmed#88]
Hello, 

Is there any sort of rumble controller and/or analog support ? 

About the analogs, I am using a standard Xbox 360 wired controller and I can't get the analogs to work for some reason. All I managed to do is to use the Left joystick as a standard ps1 dpad. Maybe I'm not understanding how the "Analog controls" menu is supposed to work but I tried every option out there and none worked.
And about the rumble. If there is an option out there to enable them I can't find it.

Thanks for reading, sorry and sorry if this is a no brainer. I've just been banging my head on this for a couple of days, and the lr-pcsx-rearmed while functional has trouble running things at full speed sometimes. Any tips, ideas, comments are welcomed. Please ask for more informations if needed.

Specifications : Raspberry Pi 3 , Retropie 4.2.10
pcsx version : binaries and built from source using Retropie_setup.sh (same results)
pcsx.cfg file : https://pastebin.com/q35icuwZ
games tested : Crash Bandicoot 3, Driver, Colin McRae Rally 2.0, Colony Wars, etc

**Comment by notaz** [comment]
AFAIK the libretro fork has some support for that (was not added by me), I don't know what lr-pcsx-rearmed is built from.

**Comment by Aryetis** [comment]
So we have to go throught lr fork to get either rumble and analog ? Why is there an analog option in the options then ?
(thanks for answering fast)

**Comment by Sashbi** [comment]
See @goodpi31 comment on the retropie forum for analog controls. Link provided: 
[https://retropie.org.uk/forum/topic/7358/saving-specific-configurations-for-separate-games/33](url)

This will allow you to set analog controls for games that used the dual analog sticks on PSX. Digital control only games will not work with analog controls turned on. Don't enable for these games, although you can assign the d-pad to the left stick if you want to. Hence why by default it is set to digital.

See here for a list of analog supported games.
[http://www.mobygames.com/browse/games/playstation/tic,9/ti,138/list-games/](url)

**Comment by Aryetis** [comment]
Thanks Sashbi but that thread was about analog support on pcsx-rearmed, NOT on lr-pcsx-rearmed.
Also your first url is malformed, you should remove "33" from its end.

**Comment by notaz** [comment]
libretro fork should have this by now.
