### ISSUE TITLE
[Rpi3] builtin_gpu enhanced resolution causes segmentation fault.

### ISSUE THREAD

**Issue by Aryetis** [notaz/pcsx_rearmed#89]
Hello, 

Well I think everything is said within the title. Whenever I try to turn on "Enhanced resolution (slow)" option from the builtin_gpu plugin the emulator crashes back to Retropie with a segmentation fault error. Depending of the games I tried I can sometimes watch the cutscences, navigate within the main menu, get some very basic 3D elements (eg: car preview from Colin McRae Rally 2.0). But as soon as the real game begins (eg: a race in Colin McRae Rally 2.0) the emulator crashes everytime, at the very same point.

Am I the only one in this situation ?

Thanks for reading, and even more to those answering.

Specifications : Raspberry Pi 3 , Retropie 4.2.10
pcsx version : binaries and built from source using Retropie_setup.sh (same results)
/dev/shm/runcommand.log file (containing the seg fault error message) : https://pastebin.com/LG7aXKrb
games tested : Crash Bandicoot 3, Driver, Colin McRae Rally 2.0, Colony Wars, etc

**Comment by notaz** [comment]
Doesn't reproduce here, maybe a problem introduced by whatever fork Retropie is using.
