### ISSUE TITLE
[Bug] G-Police 2: Weapons of Justice / unplayable on RPI3

### ISSUE THREAD

**Issue by nemo93** [notaz/pcsx_rearmed#92]
Game is launching fine (either US or EU versions) yet you simply can't play the game as after the briefing screens (when the game really starts) it's a graphical mess I can hardly describe. It's like the static image of the previous briefing screen is overlaping with the current 3D game engine. In short, there's still the briefing screen on top of the actual game, you can see nothing.

It's hard to figure out based on the below picture but it's actually the game not a menu.

![g-police2-170910-152814](https://user-images.githubusercontent.com/8100500/30250048-cab99a78-9648-11e7-9f1e-15f0db0e0bd0.png)

To reproduce: simply launch the game, pass the briefing screens and mess should be seen very shortly after.

I'm using a RPI3 with Retropie 4.2.20 + libretro-pcsx_rearmed (latest). All other games do play fine so it's not a conf or setup issue.

**Comment by Darknior** [comment]
You are real i have try on my PI3 with last source update version and same bug :(
Strange because it works perfectly on PC Windows ....
Thanks for the report.

**Comment by notaz** [comment]
Seems to be working now. Feel free to reopen if not.
