### ISSUE TITLE
[Bug?] Ace Combat 3 EU - can't pass langage select screen

### ISSUE THREAD

**Issue by nemo93** [notaz/pcsx_rearmed#93]
Only in the EU version of the game you got this select screen after the initial loading screen and whatever control you've chosen nothing will move there. I've tried with analog, non analog etc with same result. The US/NTSC version of game is playing perfectly fine (although there's no langage selection screen).

I'm using a RPI3 with Retropie 4.2.20 + libretro-pcsx_rearmed (latest). All other games do play fine so it's not a conf or setup issue.

**Comment by notaz** [comment]
Seems to work in the latest version, closing.
