### ISSUE TITLE
[Bug] Z (Europe) Playable but the in game menu flicking 

### ISSUE THREAD

**Issue by Darknior** [notaz/pcsx_rearmed#94]
When you play on PI 3 with Retropie 4.2 and the **last PCSX Rearmed from source** code, all the games are working perfectly. But some time we have some little bugs like this one that make  the game harder to use.

On Z all the game is playable without any problem. The bug is not so hard.
But many images like on Game Loading, or In Game Menu are flicking fast.
You see the menu but an image is draw behind the game ...

![20170910_235718](https://user-images.githubusercontent.com/3703317/30253592-a7d2c774-9688-11e7-85c5-a13d0d1765bb.jpg)

https://github.com/libretro/pcsx_rearmed/issues/141

**Comment by notaz** [comment]
This doesn't happen for me so assuming fixed, closing.
