### ISSUE TITLE
Repeated inputs ignored with Brave Fencer Musashi

### ISSUE THREAD

**Issue by 0uro** [notaz/pcsx_rearmed#96]
Hello,

I've been playing this game and noticed that it's impossible to fill the fusion sword gauge.
For that you have to press repeatedly fast the square button.
In fact, it appears to work until you reach the half and if I press a little bit faster it ignores inputs and goes down.
I originally thought that was related to my bluetooth controller, but using a wired gives the same issue.
Nothing relevant in logs. It works perfectly in FF8 EU (G-Force boost), so it seems related to that specific game.

My setup :
- raspberry pi 3 + genuine 2.5 amps PSU
- retropie 4.1 up-to-date (ES to 2.6.3)

PS : i'm not the kind of guy with "autofire fingers" but it's quite simple to fill that gauge, and I'm not trying to overdo that either.

**Comment by dankcushions** [comment]
I get a similar issue in 'incredible crisis' (during lift button game)

**Comment by jack4455667788** [comment]
I noticed this "bug" as well... Is it possible they simply changed the matrix?

On another forum I saw someone answer this question that the "timing" is important and that button mashing (like we do in ff8 boost) will not work.

My memory of playing the game, like yours and apparently many others, is that button mashing works just fine and I would frequently make use of "turbo" buttons that only mash and did so very effectively.

Anyhow, I just can't figure out if this is the way the game used to work or not (and I can't be bothered to dust off the console and check).  It is certainly playable the way it is now, but very difficult (which is not the way I remember it AT ALL!).  The timing is critical, and there is no room for error.  If you make only one mistaken push (that doesn't register on the gauge), you've wasted too much time and will not be able to fill the gauge before the timeout.

**Comment by lhathcock** [comment]
It's definitely not intended behavior.  I played on actual hardware, and smashing the buttons works just fine.  It isn't timing-dependent.  You can also note that pulling off Fusion combos is more difficult as well.  Interestingly, in the stock PlayStation Classic emulator (which uses PCSC ReARMed), this bug is not present.

**Comment by notaz** [comment]
The input code has since been rewritten, so assuming fixed. Feel free to reopen if not.
