### ISSUE TITLE
Segmentation Fault when selecting `Controls->Player 1` or `Controls->Player 2`

### ISSUE THREAD

**Issue by landesherr** [notaz/pcsx_rearmed#97]
Building from 0e4ad31902f206e2c6945632bb1f558eae941ff1 on Linux chip 4.3.0 using GCC 4.9.2; when attempting to set the controls for either Player 1 or Player 2 controller, a segmentation fault occurs. No special plugins or configuration changes were made prior to encountering this bug. The segfault occurs consistently; never does the menu proceed into the controller configuration.

**Comment by landesherr** [comment]
After some investigation, this appears to be a bug in [libpicofe](https://github.com/notaz/libpicofe):

More specifically, [menu.c , line 1387](https://github.com/notaz/libpicofe/blob/21604a047941b8fe81d381ede0371c75da964afd/menu.c#L1387) is, for some reason, invoking `text_out16` with a negative y value. In my case, what was encountered was (160, -16)

**Comment by notaz** [comment]
Works for me. If there is still an issue, more information is needed like the resolution of your device.

**Comment by landesherr** [comment]
I ended up fixing it way back then: https://github.com/notaz/libpicofe/commit/e7f580052c03fa3f4603051c1b718be4bd8b2db7
Looks like I forgot to close this issue afterwards. Sorry about that.
