### ISSUE TITLE
64-bit ARM support

### ISSUE THREAD

**Issue by joaodriessen** [notaz/pcsx_rearmed#99]
Dear Notaz,

It seems it is currently not possible to compile a PCSX-Rearmed Libretro core for Apple devices running iOS 11+
These devices run in 64-bit mode only.

Is there an easy fix to this issue?
Or would it require a lot work to support?

Hope I'm asking this question in the right place.
(Love PCSX-Rearmed, enjoyed many many hours of gaming)

libretro/pcsx_rearmed#126

**Comment by notaz** [comment]
Commented on the original issue. The emulator should compile, but unfortunately most optimizations are 32-bit only, so the emulator will be much slower...

**Comment by m4xw** [comment]
@notaz Guess I will bump this Issue, we (the retronx team) just ported the core to Retroarch on the Switch (as homebrew).
It nearly hits 60 fps with dithering off, all software rendered (and ofc without dynarec)

Do you have any obvious problem areas to work on that you could point me at or discuss this issue further?

**Comment by notaz** [comment]
I don't think there is anything especially problematic, just needs some tedious work for which I currently lack time and motivation.

**Comment by Panderner** [comment]
It lacks aarch64 dynarec it would be slower for lower end android devices running 64 bit including a Nintendo Switch

**Comment by notaz** [comment]
5 years later it's more or less done, closing.
